### ISSUE TITLE
yabai equivalent to chunkwm tiling::rules

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#10]
As mentioned in https://github.com/koekeishiya/chunkwm/issues/105#issuecomment-312619814, GNU Emacs's main role is an `AXTextField` instead of `AXWindow`, which makes a special handling in chunkwm's config file mandatory.

I would like to have an equivalent of tiling::rules for yabai (maybe I didn't read the docs enough?̊̈ I couldn't find anything similar...)

Are there any plans for this?̊̈
This is the only big issue that is blocking from migrating to yabai fully....
(I'm currently turning on Emacs, and executing `yabai -m window --grid 1:1:20:64:1242:716` manually :-()

**Comment by koekeishiya** [comment]
*window rules* are planned, but I have not yet decided how I want the system to look like. I think I can do better than what *chunkwm* has.

**Comment by koekeishiya** [comment]
Implemented something simple for now. See **Rule** part of the documentation.

**Comment by dominiklohmann** [comment]
Did you change it so quotation marks are handled properly now? E.g. inner quotation marks need to be escaped, but not the outer ones that delimit the passed argument? This has always been a pet peeve of mine with chunkwm, since chunkwm handled arguments different from almost every other command line utility.

**Comment by koekeishiya** [comment]
Yes, outer quotation marks are only necessary if the string itself contains a whitespace and should not be escaped. Inner quotation marks have to be escaped, so that the quote itself gets passed through the shell properly.

e.g: `yabai -m rule --add app="Sp o\"t ify" space=^6` looks like `app=Sp o"t ify` when *yabai* parses it, and the right side of the equality operator is used as the regex pattern.

**Comment by dominiklohmann** [comment]
Way better than the `\"Sp o"t ify\"` syntax chunkwm had 👍
