### ISSUE TITLE
Changing focused display doesn't (quite) work

### ISSUE THREAD

**Issue by chandlerc** [koekeishiya/yabai#1020]
Not sure if this is really fixable, so totally OK if this is closed as infeasible.

I'm trying to use Yabai these days with SIP enabled. A key part of my workflow is using directional keybindings to change spaces. This mean I used `yabai -m space --focus prev` style commands constantly when I had the scripting extension installed.

To work without the scripting extension, I configured macOS level keyboard shortcuts for switching to the next and previous space instead of using the above command ("Mission control" > "Move left a space").

I also have a separate set of spaces for each display.

Once I get here, switching the focused *display* stops working correctly.

The sequence of steps:
1. Switch display with `yabai -m display --focus 1`
2. That display *is* focused. I can interact with the window there.
3. Hit the keyboard shortcut for "Move left a space"
4. The result is that the *previous* display moves left a space (and focus moves back to that display)

I worked around this by enabling mouse-follows-focus, which then warps the mouse to the different display after (1) above. For some reason, that in turn causes (3) to manipulate the focused display's spaces rather than the previous display.

FWIW, I'm reasonably OK with this workaround and am just trying to get mouse-follows-focus to have a few quirks fixed. But in another issue it was raised as maybe a bug and so filing it here.

**Comment by koekeishiya** [comment]
It appears that macOS uses the location of the cursor to decide which display will be affected by the space-switching shortcuts, rather than the display that has the window with key-focus. The conclusion so far is that this is not a bug, and I am not really sure if there is any better workaround than enabling `mouse_follows_focus`, such that when a display is focused, the cursor is moved with it.

Note that it is perfectly possible to run with `mouse_follows_focus` enabled, and `focus_follows_mouse` disabled.

**Comment by chandlerc** [comment]
Closing as this can't be fixed. Hopefully it still provides documentation for anyone stumbling on the same oddity.
