### ISSUE TITLE
Disable SIP 

### ISSUE THREAD

**Issue by ninaw29** [koekeishiya/yabai#1036]
do I need to worry with this warning ?
I actually updated to MacOs Big sur with open core 0.2.3 and tried to disabled SIP and it came out like this . So now i’m worried “that it’s gonna likely to break “ with future updates . 
How can I re-enable it or something like that becuz it’s not actually disabled lol . 

System Integrity Protection status : unknown (Custom Configuration)

Configuration : 
Apple Internal : disabled 
kext Signing : disabled 
Filesystem Protections : disabled 
Debugging Restrictions : enabled 
Dtrace Restrictions:enabled
NVRAM Protections : enabled 
BaseSystem Verification:enable 

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

**Comment by AJAYK-01** [comment]
Hey @koekeishiya I was wondering, can't the yabai features that require SIP to be disabled be done by using applescript to call System Events.app? Like make yabai run an applescript when the action is invoked instead of using script injection to the Dock?

For eg to move a window to the next space and focus the space, I use,

```yabai -m window --space next; osascript -e 'tell application "System Events" to key code 124 using control down'``` 
(it basically passes the keyboard shortcut to focus next space to System Events.app)

instead of,
```yabai -m window --space next; yabai -m space --focus next``` 
because ```yabai -m space --focus next``` needed the script injection

**Comment by koekeishiya** [comment]
In theory yes; I have skid binds set up for that purpose. I don't want it to be something that yabai does automatically, because the user might have different binds configured in their mission-control shortcuts, and we'd have to "guess" what they are, or have more config options for the user to specify them.

Something like this is what I used before:

```
shift + cmd - 1 : yabai -m window --space  1 && skhd -k "ctrl + alt + cmd - 1"
```
