### ISSUE TITLE
Trying to get rid of instance of yabai

### ISSUE THREAD

**Issue by yuvalco** [koekeishiya/yabai#1052]
I have installed previously Yabai and uninstalled it ,and now I want to try it again, so i brew installed it, and trying to run yabai gives me an error that it cannot acquire the lock file, I have searched and found that that means that there is probably another instance of yabai, great than I tried to kill that instance and (after uninstalling yabai again) and it keeps changing it's id before I can kill it.
![image](https://user-images.githubusercontent.com/21064095/142396627-caf7dddf-fa48-401d-a3a7-da540eb4367b.png)

Any method of removing that instance would be great,

edit
after more reading I am not sure that this is the problem as I saw that grep shows me only one instance and the other is by default? (I am new to Mac) , so the problem might be just the "cannot acquire the lock file", any help would be appreciated, thanks!

**Comment by AlexW00** [comment]
SAME problem! Got this process from the latest app under the "release" tab.
No idea how to get rid of it it seems like it's only running for 1ms. This also didn't work:

<img width="688" alt="CleanShot 2021-11-18 at 16 18 57@2x" src="https://user-images.githubusercontent.com/55558407/142443373-9c2a258c-d212-4552-b253-e745548933c8.png">

**Comment by AlexW00** [comment]
this really needs to get fixed, even restarting my machine won't help!

**Comment by es183923** [comment]
try running `brew services stop yabai`

**Comment by AlexW00** [comment]
> try running `brew services stop yabai`

I already uninstalled yabai completely, using all the steps such as stop etc.
I think the process comes from the file found in the releases tab (v3.3.10).

**Comment by koekeishiya** [comment]
Grep is finding itself, that's why the process is not running when you attempt the kill command. Here is the output of an actual grep with yabai running.
<img width="881" alt="Screenshot 2021-11-18 at 16 51 42" src="https://user-images.githubusercontent.com/6175959/142449507-ee97f4f7-4c64-4b2b-ac1b-b26d2343b99b.png">

**Comment by yuvalco** [comment]
> Grep is finding itself, that's why the process is not running when you attempt the kill command. Here is the output of an actual grep with yabai running. <img alt="Screenshot 2021-11-18 at 16 51 42" width="881" src="https://user-images.githubusercontent.com/6175959/142449507-ee97f4f7-4c64-4b2b-ac1b-b26d2343b99b.png">

yes I though that might be the case, than do you have a solution for the cannot acquire the lock file?
thank you for this project btw :).

**Comment by koekeishiya** [comment]
Because I am stupid, yabai uses the `/tmp` directory to hold temporary/session-files, and so the user that yabai is running as needs write access to that folder, although you should have that by default. There may be existing files that are owned by the root user, causing your regular user to not be able to access the files.

You can try to delete these files manually (using sudo if necessary):
```
/tmp/yabai_$USER.socket
/tmp/yabai_$USER.lock
/tmp/yabai-sa_$USER.socket
```
