### ISSUE TITLE
--load-sa broken on Monterey 12.1

### ISSUE THREAD

**Issue by SailorSnoW** [koekeishiya/yabai#1091]
I couldn't use any spaces functionality after the new Monterey update.

Tried to uninstall/update yabai, uninstall/reinstall sa, SIP is disabled.

![image](https://user-images.githubusercontent.com/49660929/145916112-b672fd00-2e9f-4ced-8594-34744270b854.png)

**Comment by peppy** [comment]
Not a helpful reply, but can confirm it stopped working again since the first beta.

**Comment by humberaquino** [comment]
I have the same issue. `sudo yabai --install-sa` and `sudo yabai --load-sa` show the following notification:
<img width="285" alt="" src="https://user-images.githubusercontent.com/703673/145916706-72f43da9-a65b-4688-b217-3aa66678dd4e.png">

Window focus works but space focus stop working again after this upgrade.

**Comment by Liquidmantis** [comment]
The scripting additions are always going to need an update with every OS update, so if you depend on Yabai it's best to check for support before updating.

**Comment by hatf0** [comment]
@donaldguy has a working fork of [yabai](https://github.com/donaldguy/yabai) for 12.1 that works just fine for me. (arm64e)

Though, this makes me wonder... is this a fault of the signatures that are used? With 12.0.1 -> 12.1, the signatures only slightly changed -- dppm's signature went from ```40 21 00 D0 00 00 35 91``` to ```60 21 00 90 00 80 3D 91```

Yabai's offset finding method (via signatures) seem to be *exceedingly* fragile and break at the first sign of `Dock.app` being updated, which leads me to wonder why we don't just use static offsets from the base address instead of trying to use signatures.

**Comment by koekeishiya** [comment]
> Yabai's offset finding method (via signatures) seem to be exceedingly fragile and break at the first sign of Dock.app being updated, which leads me to wonder why we don't just use static offsets from the base address instead of trying to use signatures.

Because it makes it easier/less code to backport versions when a new version is released.

**Comment by koekeishiya** [comment]
Resolved on master and the prebuilt binary provided in #1054.

Signatures are generated by me by hand, which is why they break. I don't know of any tool that takes an array of bytes that can decode the instructions and blank/wildcard the specific bytes of an instruction that are dynamic/prone to change, and the amount of effort it would take for me to write a tool like that is just not worth it.

Having to spend half an hour or less to manually edit the signature once every 4months when Apply push an update is by far the most sensible way to do it imo. Unless someone can provide me with a simple-to-use signature generator that works for both the arm64 and x86-64 architectures.

**Comment by peppy** [comment]
Thanks for the updates.

With a self compiled (f403e609e32b4100494c5afb089d0010e7e4ef91) build on 12.1 (21C52) (x64) I'm still not seeing any response from focus commands. This isn't the first time I've had the issue, so wondering if it's something my end..

Is there any way to get further diagnostics to figure what's going wrong?

```csharp
~/Projects took 3s
❯ sudo yabai --uninstall-sa
  sudo yabai --install-sa
  sudo yabai --load-sa

~/Projects
❯ yabai -m space --focus 2; # doesn't work

~/Projects
❯ yabai -m space --focus 1
cannot focus an already focused space.
```

**Comment by koekeishiya** [comment]
@peppy That sounds weird. Try to stop yabai and pkill Dock. Then delete the temp files for yabai in `/tmp/yabai*`

Check Console.app:

**Debug loading of the scripting-addition:**

You can look for logs in `Console.app`.  Select your device on the left, and filter for "Dock" at the right, as shown in the below screenshot. Make sure no previous injection of the scripting-addition has been attempted; run `pkill Dock` first if it has. Clear the log window first for less noise, then run `sudo yabai --load-sa` and assuming it returns no error, you should see something like the following:

<img width="1771" alt="Screenshot 2021-11-19 at 09 52 49" src="https://user-images.githubusercontent.com/6175959/142594148-b3a8ef41-add1-4288-ad58-6d6c3193696c.png">

**Comment by peppy** [comment]
Following these precise steps did fix the issue, thanks! That said, I do believe I can reproduce it, and it may be related to running the install/uninstall commands too soon before the `load-sa` command (I'll do some further testing).

Also is there any issue with the order of running `load-sa` vs starting `yabai`? Wondering if performing the load before starting `yabai` itself helped at all..

**Comment by koekeishiya** [comment]
> Also is there any issue with the order of running load-sa vs starting yabai? Wondering if performing the load before starting yabai itself helped at all..

Nah order or running one without the other doesn't matter

**Comment by peppy** [comment]
@koekeishiya I've encountered this several more times and discerned that there is definitely a timing issue.

Works:
```sh
sudo yabai --uninstall-sa; sleep 1; sudo yabai --install-sa; sleep 1; sudo yabai --load-sa
```
(Usually) doesn't work:
```sh
sudo yabai --uninstall-sa; sudo yabai --install-sa; sudo yabai --load-sa
```

Not sure if this is something worth fixing or even investigating, will leave that in your hands.

**Comment by koekeishiya** [comment]
Running uninstall isn't necessary, as the install step will perform an uninstall perform installing the new version. The only timing-related thing would be the startup time of Dock.app between execution of install-sa and load-sa. At the end of the install step we force-restart Dock.app, and if you then attempt to load the sa before the Dock.app process is properly relaunched by the system, there is no process for the sa to be injected into, which is probably what you are experiencing. 
The load-sa should return a non-zero exit code in this case.

**Comment by peppy** [comment]
I see, that's got to be it. I've also read that `load-sa` is not required if running yabai afterwards, so I'll adjust my standard troubleshooting script to reflect this 👍 .

**Comment by peppy** [comment]
While I'm here, I'll also mention one more fail case I've recently encountered which I only just figured out a solution to: if you are starting yabai from a screen/tmux session and your macOS login session crashes completely, logging in a second time and then running `yabai` will fail with entitlement errors (even if correctly codesigned). This seems to be due to the ownership of the screen/tmux session not being directly associated with the current login/LoginWindow/whatever.

Running from a new terminal window works fine in this case. Might just be a me-issue, but worth noting in case it helps someone else.
