### ISSUE TITLE
yabai transparency causing flickering

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#11]
When using window transparency, it flickers.

![yabai-flickering](https://user-images.githubusercontent.com/37990858/58384235-7875c580-801a-11e9-82e1-d6375621fbbd.gif)

Sorry for the GIF quality... to not pass the 10MB limit of GitHub, that's the maximum quality :-(

**Comment by koekeishiya** [comment]
I don't think this has anything to do with transparency. I disabled transparency to see how Excel (and Word) behaves and they are really slow and have low responsiveness through the *accessibility API* in general. I don't think this is something that can be fixed.

**Comment by pcr910303** [comment]
@koekeishiya Okay, will turn off transparency then :-(
FYI, There are pretty many glitches in transparency. Not reproducible, but I found plenty of situations where the current active window is transparent :-(

**Comment by koekeishiya** [comment]
I can reproduce some issues with transparency. Sometimes at random all windows on the active space suddenly become invisible, but when moved to a different space they become visible again. No windows (old or new) is ever visible on that particular space again, and I have to destroy and replace it with a newly created one.

Also when an application that is not tracked because it is incorrectly reporting itself as a background process, but it does actually have windows that the user interacts with, switching focusing back and forth with such a window will cause our transparency to not update properly.

I don't observe said flickering that you described in the original comment, but these are some issues with transparency currently. I've disabled this code on master until I have had the time to investigate if these issues are something that can be solved.

**Comment by koekeishiya** [comment]
I'm not fully able to reproduce this issue, but I don't really see what can be done about it either. As the other issues I mentioned have been fixed, I'll be closing this.
