### ISSUE TITLE
Cmd + Shift + 4 (screenshot) crashes Yabai since macOS Monterey

### ISSUE THREAD

**Issue by MPV** [koekeishiya/yabai#1120]
## Steps to reproduce:
1. Press `Cmd` + `Shift` + `4`

## Expected results:
1. Windows staying in place (so I can screenshot them)

## Actual results:
1. Yabai crashes, causing windows to reshuffle, thus breaking ability to screenshot the part of the window that I desired.

## Notes

Using Yabai version `3.3.10`.

**Comment by zakroma** [comment]
I remapped screenshot shortcut in keyboard settings and don't have such an issue.

**Comment by conxr** [comment]
No crashing for me, but I have also needed to remap the keys. For whatever reason, it doesn't appear to register the cmd key when recording a new shortcut.

It's not as though I've lost functionality of the cmd key, however, as it works perfectly otherwise, just was unable to screenshot without remapping the keys.

**Comment by koekeishiya** [comment]
update to v4.0.0.
