### ISSUE TITLE
Problems with unexpected application closure

### ISSUE THREAD

**Issue by devrrior** [koekeishiya/yabai#1126]
Hi. I've had some issues with Yabai, sometimes when I wanna close any app, that crash then I have to force quit. Also when I wanna open another window in my browser, that suddenly close

Chip = M1
Yabai = v4.0.0
MacOS = Monterrey 12.1

![browser close](https://user-images.githubusercontent.com/69869135/149629243-920e3fca-ed9f-4c1c-9563-90dae513137d.gif)
![app crash](https://user-images.githubusercontent.com/69869135/149629463-cf82bf47-fdab-4ede-9b2b-980d0eb33cb4.gif)

**Comment by basbebe** [comment]
I can confirm this on intel.

I can't quit any application when I have some of my hooks set.

Removing / Adding a monitor makes most of my apps crash when Yabai is active.

**Comment by koekeishiya** [comment]
Looks like the border issue described in the pinned issue for Monterey. You really should not be using borders.
I have not yet experienced issues with multiple monitors, but that is likely just due to lack of actual usage with external monitors; not sure why some app would crash because the monitor configuration changes. Yabai is not doing anything that should be able to have that impact in response to those events.

**Comment by peppy** [comment]
I've reproduced this (or sometimes just apps getting stuck in "Not responding") after display mode switches with multiple monitors (I switch modes twice a day as I remote/local to the same PC). I only have borders displaying while in an skhd action layer, so don't believe that should be relevant, but I've disabled borders altogether and will see if I can still reproduce these issues.

**Comment by peppy** [comment]
Reporting back that after disabling borders completely, I have not hit one issue.

**Comment by basbebe** [comment]
> Reporting back that after disabling borders completely, I have not hit one issue.

+1

**Comment by koekeishiya** [comment]
update to v4.0.0 for working borders.
