### ISSUE TITLE
yabai space commands cannot be used in Mission Control

### ISSUE THREAD

**Issue by taupiqueur** [koekeishiya/yabai#1136]
Shell commands to reproduce:

``` sh
yabai --message space --create
yabai --message space --toggle mission-control
sleep 1
yabai --message space --focus next
# cannot focus space because mission-control is active.
```

Native space commands (exposed on `Control + Left` and `Control + Right` by default) can be used in Mission Control.

**Comment by SxC97** [comment]
I ran into the same issue. I fixed it in my dotfiles by adding a condition to my `fast focus left/right` binding in my `.skhdrc` so that if the command fails, it executes the command for _native_ space switching.

https://github.com/SxC97/dotfiles/blob/1564f33b925d4ec18c0928a6bd960fdc7dd8f69d/.skhdrc#L226

These command work because I have `ctrl + left/right` for yabai's fast focus and `ctrl + cmd + left/right` set as `Move a space left/right` in `System Preferences -> Keyboard -> Shortcuts`.
