### ISSUE TITLE
Autocomplete interpreted as own window and tiled thereafter

### ISSUE THREAD

**Issue by torgeir** [koekeishiya/yabai#1150]
Sometimes (?) popups like mouseovers in Slack are interpreted as their own windows and tiled according to the yabai configuration. This is confusing, and most of all annoying, as their presence is often time limited which makes the window layout "flicker" before returning to its normal state, when the popup dissappears.

An example from this morning:

![lMwCMnZI](https://user-images.githubusercontent.com/118202/152942294-ae465c63-48ef-4544-9412-53704a76ef3b.png)

Explanation:
- Green circle: where I hovered the mouse
- Red circle: the window that should not be tiled
- Yellow rect: the area the tiled window takes up (this is not shown that well, I know,  as I had several floating windows on top of it) 

I have also seen similar issues in Emacs, where the e.g. the company mode autocomplete window is considered its own window and is tiled accordingly.

To resolve the latter one, I suspect being able to create rules that match on e.g. role could be useful to target these windows specifically. This is also easier to debug. For the Slack issue I have no idea how to go about it, nor how to debug it as it appears kinda out of the blue.

Suggestions appreciated!

**Comment by yqrashawn** [comment]
same things happends in chrome on my side

**Comment by torgeir** [comment]
I'm still seeing this, btw. How do you guys handle/cope with this 😅 Or is it just because I am running yabai with SIP still disabled?

**Comment by koekeishiya** [comment]
Make sure you do not have any rules that set `manage=on` globally for the Slack application.

**Comment by torgeir** [comment]
I see this from a lot of apps, also e.g. Chrome on all hover boxes that pop up (e.g. hoverin over timestamps here on github). 

Just to make sure I understand, are you suggesting I disable yabai's management of all these apps completely and toggle it back on with a shortcut? Or are there other rules to e.g. catch browser tab windows specifically, so I can turn it on for all those windows automatically?

**Comment by koekeishiya** [comment]
yabai will automatically detect if a window should be managed or not, when the layout is set to bsp/stack. `manage=on` exists so that the user can force windows that misbehave, to tile (as written in the docss -- e.g Emacs and other cross platform applications where macOS is not the primary platform usually have these issues).

If you absolutely need/want to use `manage=on` in your setup even though the applications do not misbehave originally, at least add a filter for `role=AXWindow` and `subrole=AXStandardWindow` to limit the kinds of windows that you are telling yabai to mange. On macOS everything on screen is a window; a menu is a window, a tooltip is a window, a context menu is a window, etc.

https://developer.apple.com/documentation/applicationservices/carbon_accessibility/roles?language=objc

https://developer.apple.com/documentation/applicationservices/carbon_accessibility/subroles?language=objc

**Comment by torgeir** [comment]
Seems like I at some point in time started expanding my yabairc file, that initially was just a bunch of manage=off combined with layout bsp, to also add a bunch of manage=on that seems to be the cause of this issue.

After removing all manage=on and rather removing management conditionally for windows that I don't want the default bsp layout for in yabairc, this issue goes away.

Thanks!
