### ISSUE TITLE
Chrome CPU goes to 100% and crashes

### ISSUE THREAD

**Issue by eyalerez-tmrw** [koekeishiya/yabai#1169]
Hi,

I'm using the latest dev version of Yabai (as of this moment).  When Chrome runs for a few minutes, its CPU jumps to 100% and then crashes.  When Yabai is stopped this does not happen.  It is very consistent and it makes Yabai unusable.

Is there anything I can do to fix this?

**Comment by eyalerez-tmrw** [comment]
This happens in Opera as well, but not Safari.

**Comment by z20240** [comment]
Same.

**Comment by oneself** [comment]
This makes yabai almost unusable. Is there any additional information needed to move this forward?

**Comment by koekeishiya** [comment]
Probably same as https://github.com/koekeishiya/yabai/issues/204

**Comment by farzadmf** [comment]
I can also confirm that `yabai` seems to be the issue here (or at least something happening when it's running along with Chrome). If I stop the `yabai` service, everything is "back to normal"

**Comment by napcs** [comment]
Can confirm that Yabai breaks this way for me since around Chrome 96. I've had to drop Yabai and swich to Amethyst since I need Chrome for work.

Unfortunately it all looks like something Chrome needs to fix. According to #204 this is patched in the Chrome dev channel, so we may be back in luck again soon.

**Comment by farzadmf** [comment]
> I've had to drop Yabai and swich to Amethyst

For me, personally, Amethyst was basicall impossible to use, especially with its "focus follows mouse" feature.

So, I've created a shortcut to basically _toggle_ `yabai` when I know I'm going to web pages with potential issues. There will be issues when:
- I basically forget that I'm going to that page and need to basically kill Chrome
- I can't use `yabai` when I open those pages (I _think_ I can enable `yabai` once the page loads, but I can't say for sure)

And with all these inconveniences, I won't go back to Amethyst because basically it was driving me crazy 🙁

**Comment by napcs** [comment]
@farzadmf :) It's not ideal - all I did to make amethyst work was have two modes - full screen and bsp, and then made a key binding to move forward between those modes which basically gives me full screen and bsp. I disabled the mouse features. It's not perfect but it's good enough until Yabai works again.

Back on topic, the pages that *always* crash for me are any of the things in the Google suite where it actually launches a Chrome app. Sheets, Docs, Meet, Gmail, Calendar.  So disabling yabai meant disabling it full time. :(

**Comment by farzadmf** [comment]
> any of the things in the Google suite where it actually launches a Chrome app

Same for me and good to know why it's crashing (opens a Chrome app)

I think it was fine when I did this (needs to be confirmed since I haven't tried it much): I _think_ if I disable `yabai`, open the page, let it load, and then enable `yabai`, it doesn't crash

And compared to Amethyst, one thing I really like is that features are opt-in; with Amethyst, it happened to me a lot that I was like: "what happened to this shortcut I have? why isn't it working?" only to realize that Amethyst is overriding it and I need to disable it

Overall, if you're happy with Amethyst, good for you 🙂 . I come from using `i3` on Linux, so unfortunately, these apps are far from perfect when compared to that 🙁

**Comment by napcs** [comment]
> Overall, if you're happy with Amethyst, good for you

Definitely not saying I'm happy with it. :)

**Comment by farzadmf** [comment]
> Definitely not saying I'm happy with it

😆 

And, unfortunately, I confirmed that, even if I start `yabai` after the page has loaded, it causes Chrome to crash 🙁

**Comment by napcs** [comment]
I'm following up on this and with Version 103.0.5060.134 (Official Build), Yabai no longer has problems with Chrome for me on the following systems:

* Mojave
* Catalina
* Mojave

Super happy to be able to turn Yabai on again.
