### ISSUE TITLE
Is it possible to float Chrome Incognito windows?

### ISSUE THREAD

**Issue by hello-party** [koekeishiya/yabai#1171]
In the query it lists the following, but when I try to float those windows automatically, it won't go. I've tried a few variations without success.

```
"app":"Google Chrome",
"title":"New Tab - Google Chrome (Incognito)",
```

Any help is appreciated.

**Comment by Tweoss** [comment]
@hello-party 
Hello, could you share the command that you're using to float the windows?

I did some quick testing, using `yabai -m config layout bsp` then adding rules. 

` yabai -m rule --add app="Brave Browser" title="New Tab - Brave \(Private\)" manage=off`
This works for me, you might have forgotten to escape the parentheses (I certainly did the first time) since the title field is a regular expression. For reference, here's the [part in the wiki](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#66-rule) that covers rules.

**Comment by hello-party** [comment]
That's perfect! Specifying the app seems to be the fix. Thanks for this!

```
yabai -m rule --add app="Google Chrome" title="New Tab - Google Chrome \(Incognito\)" manage=off
```
