### ISSUE TITLE
Workspace Switch Animation

### ISSUE THREAD

**Issue by MONO77** [koekeishiya/yabai#1195]
Hi folks, 

First, thank you guys very much for making this awesome software which brings me back to my favourite macOS, from struggling with Linux GUI. 

The reason why I open this issue is that I am wondering if there is anyway we can enable the native macOS workspace switching animation ([demo video found on reddit](https://preview.redd.it/xm259hqx0qz71.gif?format=mp4&s=1549ed329cb6d286918a4d1102f1c8390285399c)). 

Any idea is appreciated. Thanks.

**Comment by peppy** [comment]
I'm guessing you mean for the space `--focus` command?

There's a few ways you can make the animation work:

- Focus a window rather than the space, ie. `yabai -m window --focus (yabai -m query --windows |jq '.[] | select (.app  | contains("Rider")) | .id');`
- Use sytem-level shortcuts for switching space instead of yabai (if you have one-to-one mapping of hotkeys): 

![System Preferences 2022-03-17 at 02 53 17](https://user-images.githubusercontent.com/191335/158727050-629a1d15-13da-4328-9a82-91ec15333fe1.png)

**Comment by TheNoim** [comment]
This is one of the primary reasons why I use yabai. You just need to remap the keys with yabai commands.

**Comment by MONO77** [comment]
Oh hey, thanks very much @peppy. Switching to window instead of workspace is a brilliant idea.
