### ISSUE TITLE
Switching between Emacs and first space does not focus the application on the first space

### ISSUE THREAD

**Issue by dmitrym0** [koekeishiya/yabai#1197]
I've got the following arrangement:

- Space 1: Safari
- Space 2: iTerm
- Space 3: Emacs 

So I can switch pretty quickly between edit/test/run.  When I switch between emacs and safari (via `yabai -m space --focus 1` and `yabai -m space --focus 3`). Safari does not get focused so I have to click manually to focus the window.

Steps to repro:

1. Go to Space 3 (Emacs); emacs becomes focused.
2. Go to Space 1 (Safari); safari is **NOT** focused, emacs still focused.
3. Go to space 3 again (Emacs); emacs still focused.
4. Go to space 2 (iTerm); iTerm is focused.

I spent some time testing it and _looks like there's something about space 1 that's causing this behaviour, it's not a safari issue_. If I move iTerm from space 2 to 1; iTerm will then not get focus on space 1.  If I move safari to a different space, switching between spaces focuses Safari just fine. 

I tried looking at space config (`yabai -m query --spaces`) but I don't see anything specific about space 1. Thoughts?

**Comment by seonjunn** [comment]
Having similar issue after mac update. (Monterey 12.3)
Every time I switch between spaces, focus is somewhat broken : Focus is not given to the window at that space.
I roughly confirmed that this is yabai related problem by observing that issue is gone when turns yabai service off.

It even happens when I switch space with native ways (trackpad gesture, ctrl + arrow, etc.)
Though menu bar shows as if focus is given to right application, window bar isn't activated. That is, three buttons (close, minimize, full screen) is in gray color.
Only way to recover proper focus is by clicking, which is quite annoying.
Currently I am just using `yabai -m config focus_follows_mouse autoraise` and moving mouse a bit after space switch as a quick fix.

**Comment by seonjunn** [comment]
Found out that my problem was actually xbar related. 
I used
`yabai -m signal --add event=space_changed action="sh somescript.sh"`,
and the script's role was to query number of currently focused space and referesh all plugins of xbar to show that number at menu bar.
Removing this refreshing command solved my issue.

**Comment by dmitrym0** [comment]
I just confirmed that it's likely **not** yabai related. Killed Yabai and used keyboard shortcuts to switch desktops as in the original post. Emacs still holds on to the focus. 🤷

**Comment by searene** [comment]
I have the same problem, all the other apps work fine.

**Comment by searene** [comment]
In case anyone needs, I added the following code to my Emacs' config file:

```lisp
(menu-bar-mode t)
```

Then the problem disappeared.

**Comment by dmitrym0** [comment]
> In case anyone needs, I added the following code to my Emacs' config file:
> 
> ```lisp
> (menu-bar-mode t)
> ```
> 
> Then the problem disappeared.

How did you narrow it down to this? Not working for me :(

**Comment by dmitrym0** [comment]
Alright, this is the darnedest thing -- I removed the space where Safari lived and added a new one. Now everything works.

**Comment by chu-** [comment]
> 



> I have the same problem, all the other apps work fine. Not only that, I've assigned Emacs to only show up in space 3:
> 
> ```shell
> yabai -m rule --add app="^Emacs$" space=3
> ```
> 
> But Emacs often go to other spaces. That's really weird.

Yes, the Emacs will be show up in space 3 by default, but it still can be moved to other space. Good news is that now Emacs get managed after adding your your setting into my .yabairc.
