### ISSUE TITLE
Allow installing yabai in macOS High Sierra

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#12]
After modifying the homebrew formulae with `brew edit yabai` and installing yabai on macOS High Sierra 10.13.6, it looks like everything is well and all features are working.
I would like if the homebrew formulae allows installing on macOS High Sierra by default.

**Comment by koekeishiya** [comment]
Some functionality doesn't work on High Sierra, such as *moving a space to a different monitor*, as well as *focusing windows*. The *focusing windows* part could be partially solved by using a lesser method to focus windows, such as chunkwm does. See my comment: https://github.com/koekeishiya/yabai/issues/3#issuecomment-493859031

Because of these reasons I don't want to claim that *Yabai* can run on High Sierra. This is not to say that this could not be supported, but it is not feasible for me to do so without having access to a High Sierra machine myself.

If someone could give me access to the Dock.app distributed with macOS High Sierra 10.13.6, I could probably do the reverse engineering needed to support these features, but someone else would have to verify that everything works properly.

**Comment by pcr910303** [comment]
@koekeishiya I am very very interested in helping you to allow yabai run on macOS High Sierra - I can help you both to give access to the Dock.app, and verifying that it works.
May I ask you how to help?

**Comment by koekeishiya** [comment]
Simply copy the Dock.app folder (and its contents) located at `/System/Library/CoreServices/Dock.app` to some other place on your drive and .zip it. Upload the .zip to this issue or just email it to me directly at *aasvi93@gmail.com*

**Comment by pcr910303** [comment]
[Dock.zip](https://github.com/koekeishiya/yabai/files/3232168/Dock.zip)
:+1:

**Comment by koekeishiya** [comment]
Try to build the latest master. Remember to reinstall the new scripting-addition, I think the following instructions should be correct:

```
brew services stop yabai
brew uninstall yabai
brew install yabai --HEAD
sudo yabai --uninstall-sa
sudo yabai --install-sa
pkill Dock
brew services start yabai
```

The following commands in particular need to be tested:
```
# focus the first eastward window
yabai -m window --focus east

# move the active space to the next display
yabai -m space --move next
```

Once these have been confirmed working, I'll update the readme and brew formula.

**Comment by pcr910303** [comment]
@koekeishiya Can confirm that `yabai -m window --focus east` works well.
I don’t have a second display so... I couldn’t test the second one :-(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment]
> Can confirm that yabai -m window --focus east works well.

That's great.

> I don’t have a second display so... I couldn’t test the second one :-(

No problem. I'll just assume it works until someone encounters an issue then. Thanks for your help.
