### ISSUE TITLE
Doesn't Work After Upgrade to 4.0.0

### ISSUE THREAD

**Issue by AurevoirXavier** [koekeishiya/yabai#1201]
Always pop up a window, tell me to give it permission.
I've tried to remove it from the accessibility list then add it back multiple times.

**Comment by AurevoirXavier** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/16152305/158942620-c7f7805f-3e95-439a-9bf7-5e91607af2e9.png">

**Comment by AurevoirXavier** [comment]
Download from release 4.0.0 then replace the homebrew file works.

**Comment by slifin** [comment]
Just had this same issue and replacing the binary (not the symlink) put there by homebrew appears to work for me too

**Comment by robrecord** [comment]
If it's there, and ticked, and another popup appears *immediately* after you dismiss one, then the popups are just historical - keep pressing enter until they all disappear. On my system there were something like 200 of them.

**Comment by koekeishiya** [comment]
I would recommend to run the binary itself once after install to update the entry in accessibility access if necessary, and only after that, run the homebrew service.

**Comment by qwinters** [comment]
I had the same issues as described. For me I tried the following: 
1. Run `brew services restart yabai`
2. Do a computer restart
3. Do both 1 and 2 each time after having removed yabai from system preferences pane
4. Do a full `brew services stop yabai ; brew uninstall yabai` and then `brew install yabai ; brew services start yabai`

Only option 4 worked for me. I don't think @robrecord's mention of historical windows is accurate to my experience because the windows reappeared after a system restart + a singular activation call. 

That said, it works fine for me now after having done a full reinstall of yabai.

**Comment by AurevoirXavier** [comment]
Duplicate with #867.
