### ISSUE TITLE
trouble enabling status bar

### ISSUE THREAD

**Issue by mattsawyer77** [koekeishiya/yabai#121]
Hello, I'm wondering what I'm doing wrong trying to enable the status bar. I'm using largely the example configuration. I only see a few pixels of something under the main system menu bar.

<img width="1693" alt="yabai_status_bar_screenshot" src="https://user-images.githubusercontent.com/236582/61161556-2220f100-a4b9-11e9-9f58-5b0296598fbb.png">

**Comment by koekeishiya** [comment]
The statusbar draws at coordinates 0,0 (or at the beginning of the main display), and is hidden by the apple menu bar. This is because it is not intended to be used with the Apple menu bar visible. You can turn on *autohiding* of the macOS menubar so that it only shows up when you move your cursor to access it - *System Preferences -> General -> Automatically hide and show the menu bar*

**Comment by mattsawyer77** [comment]
@koekeishiya thanks! I had no idea the menu bar could be hidden as such. The status bar is super cool, btw.
