### ISSUE TITLE
Border flicker on Catalina and yabai v4

### ISSUE THREAD

**Issue by samuellvicente** [koekeishiya/yabai#1241]
Upon updating to the latest v4.0.0 version I started noticing border flicker when I change focus between windows.

Here is a short video of what I'm experiencing:

https://user-images.githubusercontent.com/22838433/164023780-56a31b1d-8988-4f96-b091-c515794541a7.mov

In slow motion:

https://user-images.githubusercontent.com/22838433/164024830-025fb66a-b77c-4e13-bcb0-0a34d22048fb.mov

It seems that in between the drawing of the unfocused border and the focused border the border disapears and so it seems to flicker.

Anyone else experiencing this?

It also happens when I only have firefox open and I type, may be an unrelated issue but it's very distracting.

MacOS Catalina 10.15.7

Yabai v4.0.0 with sa

Btw, thank you so much for this software, without it, using MacOS would be insane.

**Comment by samuellvicente** [comment]
I see, so this is intended behaviour?

I reinstalled the 3.3.10 version just to make sure this did not happen before and it does not.

**Comment by koekeishiya** [comment]
The border system in v3.3.10 does not work in macOS Monterey so it was rewritten in v4.0.0; the new version has this side effect, at least for now.

**Comment by TheFoolishPupil** [comment]
I'm going to ask a slightly unrelated question here, @samuellvicente how have you manage to square your window corners?

**Comment by samuellvicente** [comment]
> The border system in v3.3.10 does not work in macOS Monterey so it was rewritten in v4.0.0; the new version has this side effect, at least for now. I spent some time trying to see if if was possible to have these systems live side-by-side and interchangeable through a config option, but that was not really possible in a way that I found acceptable.

I see, well, I'll just use v3 then since it has all the features I need.
Thanks for your time!

**Comment by samuellvicente** [comment]
> I'm going to ask a slightly unrelated question here, @samuellvicente how have you manage to square your window corners?

Hmm, I did nothing, I think it's the default behaviour for the border to be squared.

If your talking about the application windows then I also did nothing, I think there are some hacks you can do but I never tried them. 

My border has a width of 5 and it gives the illusion of squaring the corners. 

You can check my yabairc in my dotfiles and try my config for yourself.

**Comment by koekeishiya** [comment]
It appears that the new border system **could** get rid of this visual flicker if it is sped up. My proof of concept version (https://github.com/koekeishiya/yb) **does not** have this flickering happen.

I am not sure if this is achievable with the version that is integrated into yabai itself, because of synchronisation issues, as there is a lot more going on than simply "updating window borders".

I'll probably look into this in the future, as I myself find the visual flicker to be rather annoying at times.

**Comment by nickolaskraus-wf** [comment]
I love the borders, since it allows you to achieve a truly flat look. However, I am also struggle with the flicker.

![2022-06-04 11 10 12](https://user-images.githubusercontent.com/21178197/172015198-8184dfde-a3ed-4c82-bf47-9f4510af0068.gif)

I love this application, by the way.

**Comment by FelixKratz** [comment]
If borders are drawn below the window, instead of on top of the window, there will be no flickering: https://github.com/FelixKratz/yabai/commit/0cf7e92d9fb6031d9fa31af914e41745a58363ce

**Comment by koekeishiya** [comment]
When drawing below it will also have to enclose the window, instead of matching the window frame. This does not work well without padding/gap. A workaround is to include the size of the border frame inside of the node region, and subtract that width from the window itself, but this gets messy in situations where a window enforces min/max size constraints.

**Comment by koekeishiya** [comment]
I think I am going to try this with the workaround of subtraction the border inset from the node region of the window. If a window has min/max size constraints, the border should still be placed properly.

**Comment by s-h-o-t** [comment]
@koekeishiya it would be incredible if there the option to use borders in the old limelight style. With rounded corners and enclosing the window rather than being drawn on top. 🙏

I would try myself but I haven't got much experience with MacOS system programming. Either way thanks for the software. It's really great

**Comment by s-h-o-t** [comment]
It has also been problematic for me at times, to have window content obscured by the border being drawn over it.

**Comment by koekeishiya** [comment]
This will be fixed with the changes being made for #1430
