### ISSUE TITLE
SIP-related question 

### ISSUE THREAD

**Issue by diogox** [koekeishiya/yabai#1245]
I apologize in advance as I think this may have an obvious answer that I'm not aware of.

From what I could gather, SIP needs to be disabled so that we can get "root" access to the system folders for the script that Yabai requires for some features.

From what I understood from the docs, SIP will only blocks that access to third party apps.

Wouldn't putting Yabai in the App Store fix the issue?

Again, I'm coming from Linux to Mac, so I'm not familiar with the way things work on this side of the fence. I'm sure I'm missing something.

**Comment by diogox** [comment]
From [the docs](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection):

> System Integrity Protection (SIP) in macOS protects the entire system by preventing the execution of unauthorized code. The system automatically authorizes apps that the user downloads from the App Store. The system also authorizes apps that a developer notarizes and distributes directly to users. The system prevents the launching of all other apps by default.

**Comment by koekeishiya** [comment]
Apps that are on the App Store are sandboxed by default and cannot access parts of the system without specific entitlements being given, if I remember correctly. Having your software become notarised only lets Gatekeeper mark your software as "Approved by Apple" to prevent a warning on first run, which can be bypassed by holding the alt-modifier (or whatever it) during first launch.

In yabai I use quite a lot of private APIs that are not publicly documented by Apple, and so it will never pass their App Store and notarisation review. In addition, the techniques yabai uses to implement its functionality is essentially the same that a malware would be using. We inject code into a system process (the Dock) through its task port, to extend its capabilities and modify some of its internal state. There just is no way of doing this and also have SIP be enabled. There is also no way to implement this functionality **without** code injection. This is the reason frankly no other software except for yabai and TotalSpaces2 (which uses the same techniques) offers these features.

This comment I made some time ago may be of interest to you: https://github.com/koekeishiya/yabai/issues/798#issuecomment-767084471

Out of curiosity; a lot of macOS users that ask these questions seem to also be (former) users of Linux. Is it suddenly way more important to restrict the root user from modifying system files and processes in macOS than it was in Linux? Does Linux offer similar capabilities today?

**Comment by diogox** [comment]
Thank you for the detailed answer! I knew I must've been missing something 😅

> Out of curiosity; a lot of macOS users that ask these questions seem to also be (former) users of Linux. Is it suddenly way more important to restrict the root user from modifying system files and processes in macOS than it was in Linux?

It shouldn't be, no. The reason why I'm hesitant to turn off SIP is because I'm simply not familiar with the malware landscape on MacOS. I know Linux's. And I know that, as long as I am careful with what I run, I should be safe. Plus, it's a much less desirable target for hackers.
I guess it's the fact that Apple felt the need to implement that feature that makes it seem more dangerous to turn it off. Like there's some common attack vector that can't be prevented by your good judgement. Is it possible/common to get malware by simply navigating to a web page, for example?
In my case, I can also add that I'd be doing this on a work computer, so there's the added concern of the MDM software detecting it, or not allowing it, somehow (I've never had to worry about MDM before on Linux).

Would you say that the same good judgement on Linux keeps you just as safe on MacOS? 

> Does Linux offer similar capabilities today?

Not that I'm aware of. And I wouldn't want it anyway 😂

**Comment by koekeishiya** [comment]
> Like there's some common attack vector that can't be prevented by your good judgement. Is it possible/common to get malware by simply navigating to a web page, for example?

I think cases like this is exactly what they are trying to protect against with SIP. I know this scenario has happened in the past, where a bug in the browser allows for a sandbox escape, followed by exploiting other services running on the system to achieve privilege escalation. With SIP enabled this can still happen, but the amount of damage that can be done to the system when access is achieved is reduced. I would argue that you are in pretty bad shape either way at this point. 

Granted I have not been using Linux myself for quite some years now, I would assume that Linux is not immune to this type of an attack either. Though, of course you are correct that macOS is a more desirable target for hackers in the first place.

So in general, in my opinion, good judgement (as on any system) keeps you safe from *most* things, but there are obviously always things outside your control with all the complexity in computers (both software and hardware) today.

Obviously if this is a company computer I would not be surprised if you are denied access to even enter recovery mode to disable SIP in the first place. Either way I would encourage you to talk with IT at your company regarding this.
Also on Apple Silicon, disabling SIP will make it so that you cannot run iOS apps if that matters to you.

To be honest, I expect them to reject the request. In which case you can still run yabai, but with a reduced feature-set. You will still get window tiling, which is the majority of the functionality. There is a list of features that *require SIP to be disabled* here: https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

**Comment by diogox** [comment]
Thanks for the answer!

Yeah, I did briefly bring this up with IT but didn't really get an answer yet. I'll make sure to clear this with them before disabling SIP. I'm also expecting them to reject the request, as their job is to always risk ^^

> Also on Apple Silicon, disabling SIP will make it so that you cannot run iOS apps if that matters to you.

I actually didn't know about that. Interesting behavior :thinking: 

Either way, I've never used any iOS apps, so I think I would be fine with it.

> There is a list of features that require SIP to be disabled here

They do seem useful. But I can probably find some workarounds in my workflow to some of them :smile:

I think I have a better idea of the pros and cons of disabling SIP now. Thanks for the help!

And congrats on the project! Coming from Linux, it makes a huge difference to me :raised_hands:

**Comment by diogox** [comment]
Will close this now, just to avoid cluttering the issues on this project. Thanks again!

**Comment by diogox** [comment]
@koekeishiya Saw this today: https://mmazzarolo.com/blog/2022-04-16-drag-window-by-clicking-anywhere-on-macos/

So perhaps disabling SIP is not needed in order to have the "drag window by clicking anywhere" feature?

I have no way of testing this, but figured I'd drop it here :)

**Comment by diogox** [comment]
Nvm, I just noticed that you need to hold down cmd+ctrl for that, and I assume that's not the behavior with Yabai 😅

**Comment by garrett361** [comment]
> In yabai I use quite a lot of private APIs that are not publicly documented by Apple
@koekeishiya I am very curious: how can you even find what these private APIs are in the first place?

**Comment by albert-ying** [comment]
> Also on Apple Silicon, disabling SIP will make it so that you cannot run iOS apps if that matters to you.

@koekeishiya I just encountered this problem... Do you know any work around for that?
