### ISSUE TITLE
Unable to focus on the first window that was created when sharing screen using Zoom

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#1274]
Please watch the video see the demo of the issue.
Here you can see the right window is never getting focused unlike the rest of the windows. This is only happening when screen sharing on Zoom. I also saw the issue happening when screen sharing on Microsoft Teams.

Let me know if more info is needed

https://user-images.githubusercontent.com/3875065/168970297-428484fa-a0ea-4fb6-9105-79cae5b25697.mov

**Comment by koekeishiya** [comment]
So that is happening is that the "You are screen sharing" window is detected as a floating window, and raising the Terminal window would occlude this window completely, making it hidden. Yabai notices this and prevents the window from being raised/focused. 

This is intentional, but not what I had in mind when I implemented this.
The purpose was  to reduce friction with dialog and popup-windows that the user likely wants to interact with.

If you are able to move the "You are screen sharing" window out of the way, such that it does not overlap a window fully, focus should work again. You should be able to move it by holding down the `fn` modifier (unless you specified something else in your config) and dragging it. 

History:

https://github.com/koekeishiya/yabai/issues/407#issuecomment-759605800
https://github.com/koekeishiya/yabai/issues/1246
