### ISSUE TITLE
Switching Spaces Lags Only when Unity3d is open

### ISSUE THREAD

**Issue by BMonsalvatge** [koekeishiya/yabai#1277]
Hi, I am on a 16 inch MBP M1 Max, I have a blank unity project (latest LTS version for Apple Silicon) open and whenever I switch windows it has a roughly 3-4 second delay, occasionally locks up longer.  Switching via cmd+tab will switch between spaces without issue using Mac OS transitions.  If I close unity switching spaces goes back to normal.  Watching Activity Monitor I didn't notice any odd utilization there (just unity open).

Are there any diagnostics that would be helpful to determine the underlying issue?

**Comment by peppy** [comment]
I'm not sure how useful this will be, but I can reproduce this when pausing a debugger within SDL2/GL code in a project I develop. It's been a long term annoyance, but I haven't raised an issue because I'm not sure this is yabai's fault as opposed to macOS itself.

I believe it has something to do with a single application taking too long to process events on the OS event loop. I can provide a reproduction scenario if it helps.


https://user-images.githubusercontent.com/191335/169449948-c53262df-001d-4958-a120-a6eca73ee31e.mp4

@BMonsalvatge does this look similar to what you're seeing? In the video the delay is only a second or two, but as you say, can sometimes be 4-10 seconds long.

**Comment by koekeishiya** [comment]
Likely related #599, #600

**Comment by BMonsalvatge** [comment]
> I'm not sure how useful this will be, but I can reproduce this when pausing a debugger within SDL2/GL code in a project I develop. It's been a long term annoyance, but I haven't raised an issue because I'm not sure this is yabai's fault as opposed to macOS itself.
> 
> I believe it has something to do with a single application taking too long to process events on the OS event loop. I can provide a reproduction scenario if it helps.
> iTerm2.2022-05-20.at.04.20.34.mp4
> 
> @BMonsalvatge does this look similar to what you're seeing? In the video the delay is only a second or two, but as you say, can sometimes be 4-10 seconds long.

Yea seems similar.  Mine takes a bit longer and I mainly notice it on space switching between the space with Unity in it, and any other space.

> Likely related #599, #600

Thanks! Good to know there's already an issue for it.
