### ISSUE TITLE
Manage rule not applying to drop down list

### ISSUE THREAD

**Issue by joshuarubin** [koekeishiya/yabai#1306]
This seems related to #676. For fantastical, when I open the helper from the menubar, select an event and click a drop down (e.g. to choose an alert time), the drop down popup appears briefly and is immediately closed.

I've got this rule which I know works for the main helper window:
```sh
yabai -m rule --add app="^Fantastical Helper$" manage=off border=off
```

And I know it's an issue with yabai because the problem goes away when I stop the service.

**Comment by joshuarubin** [comment]
It seems to be related to `window_topmost on` as the issue goes away if that's off.

**Comment by irls-svg** [comment]
Heads up, if you want to be able to still keep floating windows on top of other applications being used, but not have to deal with the issues that come with using `topmost=on` you can create an array of applications that you don't want to have covering floating windows and then set their layer to below. For example, something like:
```bash
# DEFAULTS
yabai -m config layout bsp
yabai -m config window_topmost off

# APP SETTINGS

# applications with custom rules (main, day-to-day applications/fullscreen applications that i want to stay behind floating windows)
applications="(Calendar|Mail|Reminders|Notes|Microsoft Outlook|Discord|Messages|Slack|Firefox|Chrome|Code|Microsoft Word|Preview|Terminal|iTerm2|QuickTime|Player|Spotify|Music)"

# any apps that aren't main applications get set to float
# e.g. system preferences, colour meter
yabai -m rule --add app!="^${applications}$"    manage=off border=off

# main applications get set to bottom layer to prevent them from
# covering floating applications/popup windows
yabai -m rule --add app="^${applications}$"     layer=below
```
BTW, I've noticed that `layer` and `topmost` settings seem to persist after being commented out -- so if you're testing anything to do with these you need to actually reset them to `normal`/`off` before commenting out/removing them, otherwise they'll just keep behaving as though nothing's changed (been tossing up creating a separate issue for this, but I'm not sure if it's worth it or not?).

**Comment by kiryph** [comment]
Further example: Ignore settings window of LibreOffice (`manage=off`) and set `layer=above` with
```
yabai -m rule --add app="^LibreOffice$" title="^(Delete Contents|Customize|About LibreOffice|Check for Updates|Options - LibreOffice - .+)$" manage=off layer=above
```
The drop down menus in the setting windows are not accessible.

**Comment by koekeishiya** [comment]
Should be resolved in latest version.
