### ISSUE TITLE
Firefox not respecting window_placement second_child

### ISSUE THREAD

**Issue by RichardZhang104** [koekeishiya/yabai#1322]
I have window_placement set to second_child.

If I open two terminals they tile side by side. Then if I open firefox, this is what I get:

<img width="1439" alt="Screenshot 2022-07-09 at 11 26 57" src="https://user-images.githubusercontent.com/93663494/178101919-7410a79c-443f-4bea-9513-4179dc1f7ade.png">

When what I expect to get is this:

<img width="1433" alt="Screenshot 2022-07-09 at 11 26 36" src="https://user-images.githubusercontent.com/93663494/178101921-01c296a0-8006-4ddd-bd5f-5acd2f4bb253.png">

Why does this happen? This happens with some other applications but not all.

**Comment by LeeBuckle** [comment]
It looks like 2nd child is being respected, due to the Firefox window being at the bottom.

Are you focusing the terminal on the right side when you open Firefox? Yabai tiles new windows relative to the currently focused window.

If you open Firefox while being focused on the left terminal, then open it while being focused on the right, does it always appear in the same place?

**Comment by RichardZhang104** [comment]
Yes, firefox opens under the left terminal, regardless of if I focus the left or right terminal. This behavious happens 100% of the time when I'm opening firefox while it is running in the background (ie. when there's a dot under it on the menu bar).

If I quit firefox and then relaunch it, the behaviour seems random, it sometimes opens on the left and sometimes on the right, no matter which side I have selected. 

I tried commenting out everything in my yabairc except 'yabai -m config layout bsp', and I get the same behaviour.

**Comment by koekeishiya** [comment]
Sounds similar to https://github.com/koekeishiya/yabai/issues/1907

The problem seems to be that some applications steal focus before creating their window, thus overriding what yabai sees as the focused window, causing it to be placed incorrectly. Not sure how this can be solved, but tracking it in #1907.
