### ISSUE TITLE
Ignore fullscreen spaces in the "space indexing"

### ISSUE THREAD

**Issue by hotsno** [koekeishiya/yabai#1328]
I want to be able to consistently switch between spaces with the same keybinds, but right now, when I open an app in fullscreen, it increases the space number of any space "after" that fullscreen space, messing with my muscle memory. For example, I have `Spaces 1 and 2` on `Monitor 1` and `Spaces 3 and 4` on `Monitor 2`. If I open a `Fullscreen app 1` on `Monitor 1`, now `Monitor 2`'s spaces will have been pushed to `Space 4 and 5`.

My ideal solution would be a way to ignore fullscreen apps in the indexing of spaces, and then have a separate keybind to get to my fullscreen app.

Sorry if this is a question that could've been answered by reading documentation, but I couldn't find what I needed.

**Comment by AlgusDark** [comment]
Something you could do is to filter the spaces that have non-fullscreen-native and those that have fullscreen-native. After you have that filter array, you could use the current space to get the index of the space you are and then move left or right in the array.

Pseudocode:
yabai query windows | filter them by fullscreen-native | form an array of distinct spaces  | yabai space focus  [index(current-space)]

I'm currently on my phone, but let me know if you need code sample and I can happily do it for you once I"m on my PC.

**Comment by hotsno** [comment]
Thanks for the idea! I get how it works, but I'm not at all experienced writing shell scripts, so if/when you find the time, I'd really appreciate if you could write a code sample!

**Comment by AlgusDark** [comment]
[Here is an example of how to do it](https://jqplay.org/s/31t8RnZ22ec). I'm adding it here too just in case:

```
map(select(."is-native-fullscreen" == false) |
[.index, (if ."has-focus" then .index else empty end)]) |
[[.[][0]], .[][1] // .] as [$spaces, $focus] |
$spaces |
(index($focus)) as $idx | 
.[($idx + 1)%length]
```

This is done with jq. Line by line, what it does is to select only the non-native-fullscreen spaces. Then we save those in an tuple that has 2 elements; first is the spaces and second one is the focused one. After that, we just get the index of the focused space and at the end, we access it (+1 means going to the right, -1 is left).

I'm assuming you are using skhd, so this is query goes in a yabai query like:

`yabai -m space --focus $(yabai -m query --spaces | jq -e 'map(select(."is-native-fullscreen" == false) | [.index, (if ."has-focus" then .index else empty end)]) | [[.[][0]], .[][1] // .] as [$spaces, $focus] | $spaces | (index($focus)) as $idx | .[($idx + 1)%length]')`.

Now, this doesn't work when you are focused in a fullscreen-native space (because we won't have a focused index). But that's easy to fix. Let us know how you improve this, as this was done pretty quickly and can be improved. Share it with us :D

**Comment by hotsno** [comment]
Thanks a lot for writing and sharing that! 

Just got to take a look at it today, and I realized that the stuff I wanna do is complex enough that it would just be easier for me to write something in Python to handle it, so that's what I ended up doing (plus, I don't know jq at all, so I would've had to learn it).

[Here's what I ended up writing](https://gist.github.com/hotsno/96c0b8e65c398c76e29de231e173a0ed). `get_nonfullscreen_index()` takes in an index and returns the "corrected" index when taking only non-fullscreen spaces into account. `get_next_space()` gets the name space (looping around if you're at the last space), taking into account what type of space you're in -- if you're in a fullscreen space, it'll go to the next fullscreen space, same for non-fullscreen. And then `get_fullscreen_index()` and `get_previous_space()` are self explanatory taking in account the things I just described.

Now I can do:
- `yabai -m space --focus $(/path/to/python  /path/to/spaces.py get_nonfullscreen_index 1)` to get the 1st non-fullscreen index
- `yabai -m space --focus $(/path/to/python  /path/to/spaces.py get_fullscreen_index 1)` to get the 1st fullscreen index
- `yabai -m space --focus $(/path/to/python  /path/to/spaces.py get_next_space)` to get the next space (using my "rules")
- `yabai -m space --focus $(/path/to/python  /path/to/spaces.py get_previous_space)` to get the previous space (using my "rules")

Still not fully sure this is the logic I want to have, but I seem to like it so far and it's definitely better than what I had before!

**Comment by mlubej** [comment]
Thanks @hotsno for sharing this. I went with a little bit different implementation.

I use 3 displays, sometimes multiple desktops on the same display, and often also using native-fullscreen apps. I don't want native-fullscreen apps to affect my ordering, so I wrote some similar functions in order to:

- move non-native windows around the spaces across displays
- label spaces from specific displays accordingly (specific to the display, not space)
- move window to prev/next space

all of the above regardless of me using native-fulscreen apps or not

Here's the script: https://gist.github.com/mlubej/5a8a7c477d12193c584a458b239ec8fd

Example skhd + yabai commands:

```bash
yabai -m space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_first_space_from_display 1) --label main
yabai -m space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_first_space_from_display 2) --label mail
yabai -m space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_first_space_from_display 3) --label chat

# Move focus container to workspace
hyper - 1 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 1)
hyper - 2 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 2)
hyper - 3 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 3)
hyper - 4 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 4)
hyper - 5 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 5)
hyper - 6 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_nth_space 6)
hyper - 0x21 : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_previous_space)
hyper - 0x1E : yabai -m window --space $(/Users/mlubej/.pyenv/versions/3.8.7/bin/python /Users/mlubej/.config/yabai/spaces.py get_next_space)

# Focus after moving
hyper - f : yabai -m window --focus recent
```
