### ISSUE TITLE
scripting additional not installed

### ISSUE THREAD

**Issue by 0xApe** [koekeishiya/yabai#134]
➜ csrutil status
System Integrity Protection status: disabled.

https://d.pr/i/T0DMIh

os: Mojave 10.14.5
version: yabai-v1.1.2

**Comment by jbharat** [comment]
I am getting payload is outdated, even after running `sudo yabai --install-sa` and restarting yabai service.

<img width="372" alt="Screen Shot 2019-07-15 at 11 49 55 am" src="https://user-images.githubusercontent.com/6837979/61192348-f428f000-a6f6-11e9-848c-15f25128fa46.png">

os: Mojave 10.14.5
version: yabai-v1.1.2
System Integrity Protection status: disabled.

**Comment by koekeishiya** [comment]
@0xApe You need to install the scripting-addition. `sudo yabai --install-sa`

@jbharat After installing a new version of the scripting-addition, you need to relaunch the Dock (likely because your version predates the versioning scheme).

On master I've made it so that we automatically restart the Dock upon installing the scripting-addition.

**Comment by jbharat** [comment]
@koekeishiya Thanks. Restarting Dock worked.
