### ISSUE TITLE
No redraw of borders on focus

### ISSUE THREAD

**Issue by blu3beri** [koekeishiya/yabai#1346]
Hi,

I would like to add borders to my windows. However, as mentioned in #1241, it flickers and becomes a bit annoying. 

However I don't want to display the active window differently. This means that no redraw has to happen on a focus change. Is this already possible, might be a niche feature. If not, this issue can be completed.

**Comment by koekeishiya** [comment]
This is not related to the color being different. The redraw needs to happen because the ordering of the window is changed by macOS when a window is given focus.

**Comment by blu3beri** [comment]
> This is not related to the color being different. The redraw needs to happen because the ordering of the window is changed by macOS when a window is given focus.

Okay maybe I explained it wrong. But is Yabai doing the redrawing of the borders on a focus change event (there are other events of course, but I am mainly interested in that event)?

If we redraw based on that event, a config option of `window_border_no_redraw_on_focus_change` (naming is not my strong suit) might be a nice feature. With this config option enabled yabai does not redraw the border when the focus is changed. This means that no flicker happens on focus-change, only on respawn, size change, etc.

Again, if this is too niche or not worth any time, this issue can be closed.

**Comment by koekeishiya** [comment]
The redraw is performed by the macOS compositor. When macOS focuses (and raises) a window, the z-ordering of windows on the screen change. The focused window is ordered above the border window. We detect that this happens, and raise the border window again. This is what causes the flicker; there is no redrawing performed by yabai that can be disabled.

You can disable yabai borders and use https://github.com/koekeishiya/yb instead to avoid the flickering. The flicker happens because yabai is receiving a lot of events from macOS, and they are all reported in the same run-loop event queue -- meaning that we are not able to pre-empt the change in z-ordering quick enough.

A standalone border system that only receives events necessary to do borders only is fast enough to be able to react before any visual flicker becomes  noticeable, e.g the way that https://github.com/koekeishiya/yb works.

**Comment by blu3beri** [comment]
Thanks for the full response. I will give yb another go and see if that suits my needs. thank you very much :).
