### ISSUE TITLE
Restarting yabai is really slow

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/yabai#1352]
Hi,

Here is my .yabairc: https://gist.github.com/mickaelperrin/4b72fa46dec0aa8935b170685dac507d

I destroy/recreate all spaces upon yabai restart. This helps me to have a space configuration depending on how much external displays I use.

However, the destroy of space is painfully slow because all applications belonging to destroyed workspaces have to be moved/managed.

The space creation is really fast however.

I don't know what's causing this, I tried to make all spaces float before destroying them but without success.

Has anyone an idea on how to improve yabai restart ?

This is even more annoying related to #1309

**Comment by koekeishiya** [comment]
Modify the space removal code to delete in reverse order, instead of deleting the 1st space repeatedly. I assume that the 1st space has focus when this code runs, and removing the currently focused spaced is slower than removing an unfocused space.

Also, remove `yabai -m query --spaces | jq 'map(select(.type=="bsp") | .index) | sort | join(" ")' | tr -d '"' |  xargs -n1 -I{} yabai -m space --layout float {}`and simply run the space removal and recreation code before the following line: `yabai -m config layout                       bsp`.

**Comment by mickaelperrin** [comment]
@koekeishiya awesome.

I changed my delete_all_spaces function to

```
delete_all_spaces() {
  for monitor in ${MONITORS[@]}; do
    yabai -m space --focus $(yabai -m query --spaces --display $monitor | jq '.[0].index')
    while [ $(yabai -m query --spaces --display $monitor | jq '. | length') -ne 1 ]; do
      yabai -m space --destroy $(yabai -m query --spaces --display $monitor | jq '.[-1].index')
    done
  done
}
```

and things are working really well now !

Thanks !
