### ISSUE TITLE
M1 Monterey 12.5 - external_bar not working

### ISSUE THREAD

**Issue by ramondina** [koekeishiya/yabai#1357]
Not sure if this is a config error or genuine bug:

i have 2 displays (macbook display, external monitor).
The built-in display is set to the main display and the macos menu bar is set to automatically hide.

I use the following settings in my .yabairc:

```
yabai -m config layout          bsp

yabai -m config external_bar    "main:10:0"
yabai -m config top_padding     "40"
yabai -m config bottom_padding  "24"
yabai -m config left_padding	"24"
yabai -m config right_padding   "24"
yabai -m config window_gap      "4" 
```

no matter which parameter i use for `external_bar` the padding on my macbook display does not change.

Am i missunderstanding the documentation?

> external_bar [<main|all|off>:<top_padding>:<bottom_padding>]
Specify top and bottom padding for a potential custom bar that you may be running.
main: Apply the given padding only to spaces located on the main display.
all: Apply the given padding to all spaces regardless of their display.
off: Do not apply any special padding.

Thanks! 😄

**Comment by ramondina** [comment]
bottom padding works btw...
<img width="1728" alt="bottom_0_padding" src="https://user-images.githubusercontent.com/56022231/185601983-8eb9a4a6-7846-49e1-b04c-531b01efb412.png">
<img width="1728" alt="bottom_100_padding" src="https://user-images.githubusercontent.com/56022231/185602018-1680935b-7abb-42cb-8566-eea3bc652ee7.png">

**Comment by FelixKratz** [comment]
This is by design. As long as the external_bar top padding does not exceed the notch height it will be treated as if it was 0. Try setting the external bar top padding to:
```bash
yabai -m config external_bar "main:50:0"
```
you will notice that it is working.

It makes sense to treat the notched screens differently in this regard because yabai will only order windows below the notch regardless of an external or native bar. If the external bar top padding would take effect starting below the notch it would lead to an excess top padding on the internal display, while accounting for the external bar correctly on external displays.

**Comment by ramondina** [comment]
Thanks for clarifying!

The config i was looking for was:
```
yabai -m config layout 		    bsp

yabai -m config external_bar 	    "all:70:0"
#yabai -m config top_padding         "60"
yabai -m config bottom_padding      "24"
yabai -m config left_padding	    "24"
yabai -m config right_padding	    "24"
yabai -m config window_gap          "08"
```
Now both displays have the same top padding.
