### ISSUE TITLE
Status Bar On Multiple Display

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/yabai#136]
I use multiple displays. Is it possible to make the status bar available on multiple displays?

**Comment by koekeishiya** [comment]
You would have to create and initialize a status bar window for every connected display, and have it respond to display_removed, display_added events, as well as have all existing code that enables/disables or updates the status_bar operate on a collection of status_bars instead.

The code to draw the bar itself is already display agnostic. The main change with the exception of what I mentioned above would be to pass in an additional parameter to *bar_create* function that specifies which display the bar should draw to - instead of it fetching the main display.

I'm not interested in adding this upstream, but feel free to ask questions if you want to try and implement this in your own fork.

**Comment by shakedlokits** [comment]
@koekeishiya I'd like to help here, could you tell me where I should start?

**Comment by koekeishiya** [comment]
See my previous comment. The relevant files are `src/bar.c`, `src/event.c` and `src/message.c`. To retrieve a list of current displays, see functions defined in `src/display_manager.c`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benwr** [comment]
is this closed because it's addressed or because it won't be addressed?

**Comment by dominiklohmann** [comment]
@benwr 
> is this closed because it's addressed or because it won't be addressed?

See the 2nd comment in this issue (emphasis mine).

> I'm *not interested in adding this upstream*, but feel free to ask questions if you want to try and implement this in your own fork.

**Comment by benwr** [comment]
Ah, sorry I didn't read sufficiently carefully.

**Comment by TomFaulkner** [comment]
> I've also got [this uebersicht widget](https://github.com/benwr/barlioz/blob/master/widgets/workspaces.jsx), which is very similar. Sometimes it seems to crash for unknown reasons though :/

That widget is great, thank you!

**Comment by x-ji** [comment]
@noperator The configuration works well. Thanks for sharing.

**Comment by x-ji** [comment]
Note that the widget might cause high CPU usage from yabai, as mentioned here: https://github.com/koekeishiya/yabai/issues/434#issuecomment-595075618. It could be helpful to limit the refresh rate of Übersicht.

**Comment by noperator** [comment]
Hi @x-ji, thanks for the heads up. That widget is currently [configured to refresh every 100 ms](https://github.com/noperator/dotfiles/blob/master/widgets/spaces.coffee#L3) just to ensure that it promptly updates whenever I switch between spaces. I saw your comment on the ticket you referenced:
> Seems that constantly running the command `/usr/local/bin/yabai -m query --spaces` is having some performance impact.

Perhaps I'll find another way to update the spaces display that's less CPU intensive. Also, I found @koekeishiya's [comment](https://github.com/koekeishiya/yabai/issues/434#issuecomment-594491799) interesting since I've been having [issues](https://github.com/koekeishiya/yabai/issues/376#issuecomment-580410015) with mouse clicks not being recognized while using yabai:
> Under certain circumstances (heavy load??)…a mouse-click event is not forwarded to the target application if yabai is intercepting it.

Perhaps this high Übersicht refresh rate puts a heavy load on yabai, which prevents it from properly forwarding mouse-click events to the target application. Anyway, just trying to make sense of multiple issues which may be related.

**Comment by nuynait** [comment]
I tried the widget for some time, then I ends up using [WhichSpace](https://github.com/gechr/WhichSpace) to display the desktop number directly on mac menu bar. 

Because that widget doesn't support secondary monitor, I fork it and create another menu bar item to display secondary monitor desk space number with an alpha. Looks like this:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/2152195/75995791-eebd2780-5eca-11ea-9b45-38e25d7d9cfb.png">


https://github.com/nuynait/WhichSpace

**Comment by koekeishiya** [comment]
> Perhaps this high Übersicht refresh rate puts a heavy load on yabai, which prevents it from properly forwarding mouse-click events to the target application. Anyway, just trying to make sense of multiple issues which may be related.

It shouldn't really be an issue. The events are processed fine, it's just consuming a higher cpu percentage, as it is doing work more frequent, instead of sleeping.

> Perhaps I'll find another way to update the spaces display that's less CPU intensive.

You can use the yabai signal system to have yabai invoke a shell script or applescript (or w/e you want) after processing e.g a space_changed event, instead of having to poll every x ms. I don't exactly know how Übersicht widgets can be targetted, but there is a (not tested by me) sample for it in the yabai wiki in the tips and tricks section.

**Comment by x-ji** [comment]
@nuynait Thanks for the tool 👍 . Though it seems that it currently doesn't work if there are more than 2 monitors? (my third monitor isn't shown on the status bar).

**Comment by nuynait** [comment]
> @nuynait Thanks for the tool 👍 . Though it seems that it currently doesn't work if there are more than 2 monitors? (my third monitor isn't shown on the status bar). I wasn't able to open an issue in your repo.

Now you can open the issue in the repo. I only use a seconday monitor. I can make the change for you if I have time this weekend.

**Comment by TomFaulkner** [comment]
Can confirm increasing that refresh time to 3 seconds makes a significant difference in yabai cpu usage. Dropped from around 4% to alternating between 0.1 and 1.8% during the refresh.

**Comment by x-ji** [comment]
@nuynait Sure. Opened an issue in your repo.

**Comment by noperator** [comment]
For those interested—I [updated my Übersicht spaces widget](https://github.com/noperator/dotfiles/commit/4a154c05a764c96df6bf5828b238832eab3df222) to indicate whether a given space has any windows assigned to it or not. In the following example:
- Spaces 2 and 8 are currently visible on the first and second displays, respectively
- Spaces 1, 5, 7, and 8 have windows assigned to them
- Spaces 2, 3, 4, and 6 are empty

<img src="https://i.imgur.com/YilN0MH.png" width="400px" />
