### ISSUE TITLE
New window sometimes exceeds layout node boundaries

### ISSUE THREAD

**Issue by overhacked** [koekeishiya/yabai#1388]
When creating a new window, the size of the window sometimes exceeds the layout node's boundaries, especially when there are many windows on screen and the new window is deep in the node tree. See attached video for example. See linked PR for debugging information and a proposed fix.

**Comment by overhacked** [comment]
#### Video

https://user-images.githubusercontent.com/121654/188353520-6653adea-6319-4d1d-a80c-5c33d60df3e2.mov

**Comment by koekeishiya** [comment]
This should be resolved in https://github.com/koekeishiya/yabai/commit/a64df0c8978c2ee27f4a9fdfbba13ea3bc6ead19
Accidentally introduced in https://github.com/koekeishiya/yabai/commit/1e00a59205409587fd8194d50f004e87118da9a3

It could also be because of the applications min/max size constraints, the we are not able to bypass.
