### ISSUE TITLE
Hide window creation 

### ISSUE THREAD

**Issue by nikita-orca** [koekeishiya/yabai#1437]
First of all - thanks for the great open-source product!
Is there a way to remove flicker on window creation? 

https://user-images.githubusercontent.com/98094840/191736077-74e15f30-5d99-4d69-b47a-29010f5ba91f.mov

**Comment by koekeishiya** [comment]
It will be removed for users that enable window animations, when that is released.ed.

**Comment by nikita-orca** [comment]
Hey!
I've updated yabai to the latest release (5.0)
Animation is working, but I'm still seeing the same issue with window creation
Are there any additional steps?
Thanks

**Comment by nikita-orca** [comment]
Not sure if you receive notification on closed issues @koekeishiya

**Comment by koekeishiya** [comment]
It's not really possible to make it much better than this. Yabai doesn't know about the window before it is rendered on the screen.

**Comment by nikita-orca** [comment]
I've seen somewhere suggestion to hide the window and show it only after it's placed.
Is it hacky or not possible?

**Comment by koekeishiya** [comment]
How quickly the window is hidden depends on how quickly the OS can report to yabai that a new window has been created. I find it hard to believe that we will be quick enough to hide the window before the user is able to see it. The amount of time it takes for us to get notified and a window that we can manage varies heavily between applications.

**Comment by koekeishiya** [comment]
I am testing this in practice and for most windows that are created it seems to work well. Every once in a while I am able to spot the window before yabai is able to hide it; probably visible for like ~30ms, but I do notice it.

**Comment by koekeishiya** [comment]
So here I have implemented a sample where I basically try to pre-empt the compositor by making the window invisible *as fast as possible* in macOS. Yabai then moves and resizes the window to the target frame, if it is going to be managed.
If `config window_animation_duration` is `> 0.0` yabai animates the opening with a single fade transition, otherwise the window appears instantly at the desired position.

![create](https://user-images.githubusercontent.com/6175959/192107117-6f3d2db3-c852-4b2a-a8a2-c45761661112.gif)

This looks pretty nice and works well for the most part, however that last `Safari` window I open in that gif appeared on the screen for probably ~40ms. It was very noticeable for me as a user that it spawned and then got hidden by yabai before it was moved into place and animated into view; the recorded video (and converted gif) did not manage to capture that frame.

**Comment by nikita-orca** [comment]
Cool, could you share a branch to test?

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/tree/animate_spawn

Window borders are not adapted for this experiment and should be turned off in your config.

**Comment by jheroy** [comment]
@koekeishiya  Could you wait until the `window_created` signal execution is completed and then finally display the window.  I use `window_created` signal to stack the new window in some space to keep only two split part. Thanks.
