### ISSUE TITLE
Zoomed windows are occluded if not preemptively raised

### ISSUE THREAD

**Issue by jonatan-branting** [koekeishiya/yabai#1441]
Zooming a window which hasn't been raised will cause it to be occluded by other windows.
(or more specifically all windows which have been raised since the window in question itself was raised)

This will frequently happen if you use `focus_follows_mouse = autofocus`. 
A common use case (at least for me) is to hover a window I want to fullscreen and then pressing the corresponding binding. 
As it currently is I have to press the window before or after zooming it.

A solution would be to force-raise any window which are zoomed.

**Comment by jonatan-branting** [comment]
This also seems to occur using `focus_follows_mouse = autoraise`, although not consistently. Not sure when or why, however.

**Comment by koekeishiya** [comment]
This was an ordering bug with the animation system; I have changed the system not to mess with ordering since then. I personally think I'd sometimes prefer the behaviour you are talking about, where I can zoom a window and not make it frontmost.

The behaviour you described can be easily achieved by using the following command: ` yabai -m window --toggle zoom-fullscreen --focus` so I don't think it needs to be made a default?

**Comment by jonatan-branting** [comment]
> This was an ordering bug with the animation system; I have changed the system not to mess with ordering since then. I personally think I'd sometimes prefer the behaviour you are talking about, where I can zoom a window and not make it frontmost.
> 
> The behaviour you described can be easily achieved by using the following command: ` yabai -m window --toggle zoom-fullscreen --focus` so I don't think it needs to be made a default?

That's reasonable, completely missed that `--focus` was an option. Thanks!
