### ISSUE TITLE
brew service start doesn't work after update

### ISSUE THREAD

**Issue by boof-fo** [koekeishiya/yabai#1448]
If i run yabai in a terminal it works, starting it with "brew services start yabai" does nothing.

**Comment by 0xWaleed** [comment]
I would suggest to check the Accessibility permission in Security & Privacy.

**Comment by koekeishiya** [comment]
Check the logs: https://github.com/koekeishiya/yabai/wiki/Configuration#debug-output-and-error-reporting

> directory containing log files (HOMEBREW_PREFIX defaults to /usr/local unless you manually specified otherwise)
HOMEBREW_PREFIX/var/log/yabai/

> view the last lines of the error log 
tail -f /usr/local/var/log/yabai/yabai.err.log

> view the last lines of the debug log
tail -f /usr/local/var/log/yabai/yabai.out.log


Likely caused by 

> yabai must be given Screen Recording permission **if and only if you want to enable window animations**, and will request access when necessary. The application must be restarted after access has been granted.

https://github.com/koekeishiya/yabai/wiki#installation-requirements

**Comment by boof-fo** [comment]
It works, thanks
