### ISSUE TITLE
windows are not resized after insert (from fullscreen mode)

### ISSUE THREAD

**Issue by nikita-orca** [koekeishiya/yabai#1481]
Open any window in fullscreen mode
 `yabai -m window --toggle zoom-fullscreen`
Create another window and exit fullscreen mode

The new window is placed on top, old window hasn't been resized

**Comment by occludedpixel** [comment]
When you say
> Create another window and exit fullscreen mode
Do you switch focus back to the old window before toggling fullscreen mode?

Also, does the new window end up in fullscreen at this point?
> The new window is placed on top, old window hasn't been resized

**Comment by occludedpixel** [comment]
Sorry, I'm a bit confused about what you're saying. Could I clarify whether the following steps match what you are doing? In the steps, I make reference to an attached screen recording of me going through the same steps.

1.  open an app (in the video I open the terminal)
2. toggle full screen of the app
3. open another app (in the video the Reminders app)
4. switch focus back to the first app and toggle full screen for that app

https://user-images.githubusercontent.com/97084099/195508184-1cd177eb-1f66-464b-a195-706f4ef9d7f2.mp4

If I am doing the same steps as you, could you explain how the behaviour on your system differs from the recording?

**Comment by nikita-orca** [comment]
https://user-images.githubusercontent.com/98094840/195994174-b67579fc-3c56-4e2f-b97c-434d9cff3b5e.mp4

1. Have 2 open windows
2. Fullscreen window on the right
3. open another window (I'm using a keyboard shortcut)
4. new window is placed on top, grabbing focus, and a fullscreen window is automatically toggled back

**Comment by dimitarvdimitrov** [comment]
I am also seeing the same behaviour that @nikita-orca recorded after upgrading from 4.x.x (don't remember which one exactly, sorry) to 5.0.0

**Comment by occludedpixel** [comment]
@nikita-orca Could I check what's the behaviour you're expecting instead in your recording? Is it one of the following?

1. Are you expecting the fullscreen terminal window to be resized to the top right corner (taking up quarter of total space) when you open the second terminal window? If that's the case, I'm afraid that's no longer the expected behaviour (please the reply to @dimitarvdimitrov below).
2. Otherwise, are you expecting the fullscreen terminal window to remain fullscreen and the second window to be placed on top? This is what happens when I do what you did in the video with 3 windows instead of 2 so I think there's a bug here which can be fixed by adjusting the following line
https://github.com/koekeishiya/yabai/blob/c888d80540a580c61e68ee3f6682fb0099962f0e/src/view.c#L254
to ` : node->zoom == node->parent && node->zoom != view->root`. 

@dimitarvdimitrov In 4.0.4 opening a new window when there's a window currently in fullscreen would cause the fullscreen window to revert back to normal. In 5.0.0, the behaviour has changed to keeping the fullscreen window in fullscreen and placing the new window on top. #864 looks like the specific change in 5.0.0 responsible.

**Comment by dimitarvdimitrov** [comment]
so it looks like it's working as intended. What do you think about making this un-fullscreen behaviour a config option - e.g. `unzoom_on_new_window`?

**Comment by nikita-orca** [comment]
@koekeishiya could you do this fix, please?
https://github.com/koekeishiya/yabai/issues/1481#issuecomment-1281938635

**Comment by occludedpixel** [comment]
I looked into this

> So it would be nice to fix the bug at least

a bit more and realised that the change I suggested here

>    to ` : node->zoom == node->parent && node->zoom != view->root`.

would also cause unexpected behaviour: if you had two windows open and `--toggle zoom-parent` one of them then open a third window, the `zoom-parent` window would be zoomed fullscreen instead parent (so basically the opposite of the current issue happens).

It looks like the underlying cause is that whenever it comes to a situation where there are two windows in a space, `zoom-parent` and `zoom-fullscreen` fold into one and subsequently we are unable to determine whether the zoomed window is supposed to be fullscreen or parent (currently it is taken to be parent). 

Maybe there needs to be a separate boolean field in `window_node` to distinguish between the two?

**Comment by occludedpixel** [comment]
@nikita-orca As for this

>  I would like yabai to turn off fullscreen when a new window is added But I see #864, so that's not possible currently

The following signal should be able to do it if an `unzoom_on_new_window` option suggested by @dimitarvdimitrov doesn't get added.

```
yabai -m signal --add event=window_focused action='if [[ $(yabai -m query --windows --window | jq ".\"is-floating\"") == "false" ]]; then
win_id=$(yabai -m query --windows --space | jq "map(select(.\"has-fullscreen-zoom\" and (.\"has-focus\" | not)))[0].id")
if [[ $win_id != "null" ]]; then yabai -m window $win_id --toggle zoom-fullscreen; fi
fi'
```

I've been using this signal to automatically unzoom windows even when switching window focus (in yabai v4.x.x the unzooming would happen when adding windows but not switching). However, this 

> @koekeishiya could you do this fix, please? [#1481 (comment)](https://github.com/koekeishiya/yabai/issues/1481#issuecomment-1281938635)

still needs to be addressed before the signal is able to achieve the behaviour you desire in your screen recording

> screen.mp4

**Comment by nikita-orca** [comment]
up

**Comment by dimitarvdimitrov** [comment]
thanks @nikita-orca, this signal works well as a workaround for me

**Comment by nikita-orca** [comment]
It's not working for me :(

**Comment by mil-ad** [comment]
The signal kind of works but it's janky. It takes a moment for it to realise something's changed and then everything kind of rejiggles into the right place.

**Comment by koekeishiya** [comment]
Made zoom persistence configurable; `yabai -m config window_zoom_persist on|off`

**Comment by rublev** [comment]
> screen.mp4
> 
>     1. Have 2 open windows
> 
>     2. Fullscreen window on the right
> 
>     3. open another window (I'm using a keyboard shortcut)
> 
>     4. new window is placed on top, grabbing focus, and a fullscreen window is automatically toggled back

Sorry to bump a 4 year old thread but how do you get your macos menubars height to be so large? @nikita-orca

**Comment by fnschmidt** [comment]
@rublev his menu bar is that tall because he is using a MacBook screen with a notch
