### ISSUE TITLE
Yabai plays poorly with Chrome

### ISSUE THREAD

**Issue by haberdashPI** [koekeishiya/yabai#1494]
I have noticed yabai's performance and chromes performance degrade *substantially* over time. If I quit yabai, or I quit Chrome things work as expected, but the two together become unusuable.

Chrome verison: 106.0.5249.119 (arm64)
macOS version: 12.6 (21G115) (arm64)

**Comment by haberdashPI** [comment]
New data point: the performance issues seem to be a linear function of the number of chrome tabs I have open. With just 2 tabs open, things are just fine. When I have 15+ tabs open chrome and yabai both become impossibly sluggish.

**Comment by teelahti** [comment]
I can confirm this observation and give a bit more data: I personally use another Chromium browser (Brave), and recently - might be after the Yabai 5.0.1 update but also might not - Brave starts to hang after window operations. This is _very_ noticeable: complete hang might last between 10-30 s. Observing with Brave tasks view, it is the browser frame that hangs, none of the tab contents. 

I run multiple browser profiles with 5-20 tabs each. I've not been able to pinpoint the root cause. I've even read Chromium commit logs trying to find a reason. All components are on latest versions: MacOS, Yabai, Brave. I didn't report this earlier as this might as well be a bug on the Chromium side (but for some reason, it surfaces only with Yabai active).

**Comment by zakroma** [comment]
[https://chromeisbad.com/](https://chromeisbad.com/)

**Comment by teelahti** [comment]
> https://chromeisbad.com/

I use Brave, and as the article states, this issue doesn't apply to Brave.

**Comment by kodokoto** [comment]
I'm also getting the same issue, yabai has been working fine with chrome for the past few years but recently all my devices have been having issues where chrome and yabai at the same time.

**Comment by prgres** [comment]
same issue for me

**Comment by Liquidmantis** [comment]
Just for a probably unneeded data point.  I have been experiencing the issue, too.  At one point I was able to fix, or at least reduce, the issue by disabling some extensions.  In my case it appeared I had too many old entries in OneTab and purging them fixed it.  But now it's back even without extensions loaded.  

I took the advice above and used it as the final incentive to move off of Chrome.

**Comment by danielgek** [comment]
Another datapoint: i'm using 5.0.1, and specifically the last version of chrome lags at each window operation

**Comment by koekeishiya** [comment]
These are issues Chrome needs to resolve.

**Comment by haberdashPI** [comment]
FYI: I have not noticed this issue lately with a chromium based browser (Vivaldi), so it's possible it has been resolved.
