### ISSUE TITLE
Slowness window resize 

### ISSUE THREAD

**Issue by lucafulgenzi** [koekeishiya/yabai#1521]
Why when I increase or decrease the size of a window, yabai seems like think about it, he do the animation and then redraw the window. 
Whereas by disabling the animations everything is much more reactive, but still repeating the command several times seems like slowing down and then suddenly resuming everything

**Comment by Ushio-Clover** [comment]
Thank you for letting me know I'm not the only one with this problem. I encountered this problem after an update to my system. I didn't set the animation, but when I did something like resize the window, there was a long linear animation of a fixed zoom over a resized window. This seems to be macOS behavior. I don't know how to deal with it.😂
Have you solved the problem?😶

**Comment by lucafulgenzi** [comment]
For the moment I just disabled the animations and all kinds of blurs, there is still some graphic artifacts and some slowness but definitely more acceptable.

**Comment by Ushio-Clover** [comment]
I seem to have fixed this issue after I reinstalled yabai (from HEAD). You can try reinstalling yabai by following the steps in the **wiki**.

**Comment by Ushio-Clover** [comment]
I guess that it may was caused by the **scripting addition** starting in the wrong way.

**Comment by lucafulgenzi** [comment]
I installed the HEAD version, but still it seems to me that the problem is not solved.
At this point I think it is a structural problem, that is, how the window resize event is handled.
I hope we will see improvements in fluidity and performance with future releases.

**Comment by koekeishiya** [comment]
Unfortunately there is nothing that can be done to speed up window resizes. The slowness is caused by Apple and application developers, as actions have to go through the accessibility API, which is a system-wide blocking API that requests an application to perform some action. 

The speed at which windows are moved is solely controlled by the performance of this API and the authors of various macOS applications. This is just how macOS is built, and there is no way to circumvent that.

To see this in practice, try to run `yabai -m space --rotate 90` repeatedly on a space with 8 Kitty terminal windows (of various dimensions), and then do the same in a space with 8 Chrome windows (of various dimensions).

**Comment by lucafulgenzi** [comment]
I figured it was a Apple problem, like every other problem that is present on yabai.
However, thank you for your exhaustive response and thanks for your work.

**Comment by koekeishiya** [comment]
This started to annoy me and I got a little bit creative, and found a way to improve the situation.

https://github.com/koekeishiya/yabai/issues/2060
