### ISSUE TITLE
Cannot load Scripting Addition on Macbook Air M1 2020

### ISSUE THREAD

**Issue by DragonDev07** [koekeishiya/yabai#1559]
Hi! Im having an issue when trying to run the `sudo yabai --load-sa` command, where I get the following error:
```
could not spawn remote thread: (os/kern) invalid argument
yabai: scripting-addition failed to inject payload into Dock.app!
```
I've looked into fixing this through this issue: #1234, but none of the solutions that were provided worked (Changing boot args, fully disabling SIP, Uninstalling and Reinstalling SA, etc.)

Does anyone have another way to try and fix this issue?

**Comment by aiguofer** [comment]
Are you running off HEAD (`brew install koekeishiya/formulae/yabai --HEAD`)? The M1 stuff hasn't been officially released but it's working well for me.

**Comment by DragonDev07** [comment]
> Are you running off HEAD (`brew install koekeishiya/formulae/yabai --HEAD`)? Ventura 13.0 support isn't officially released yet but it's working well for me form `master`

I just tried it, and it doesn't seem to work still. I also get spammed by yabai wanting to be allowed with accessibility to control the computer, even though it is already allowed to. When I try to load SA it is the same error as before.

**Comment by karlicoss** [comment]
@DragonDev07 had the same issue, I think it's because you need to use the actual yabai binary (instead of just output of `which yabai`, which is a symlink). So whatever is the output of `brew --prefix yabai)/bin/yabai` basically.

Seems necessary both during self-sign step (as mentioned [here](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head)), and when you add it to the accessibility settings.

**Comment by DragonDev07** [comment]
@karlicoss I tried this, and it still doesn't work, giving the same error.

**Comment by koekeishiya** [comment]
Follow the wiki instructions exactly as they are written, and it should work (does on both my machines anyway).
If you are still having issues, read this comment for instructions to debug your setup https://github.com/koekeishiya/yabai/issues/1515#issuecomment-1344070256
