### ISSUE TITLE
Cannot focus space due to an error with the scripting-addition. Ventura 13.2 with HEAD

### ISSUE THREAD

**Issue by ekmekjian** [koekeishiya/yabai#1567]
So I am running the beta of Ventura and seem to have trouble focusing a space 
```bash
yabai -m space --focus 3
cannot focus space due to an error with the scripting-addition.
```
I've installed the HEAD version as explained here to do https://github.com/koekeishiya/yabai/issues/1532
Certifying to the new location rather that what `which` was pointing too and updating `sudoers` file as well but get a syntax error of 
```
/etc/sudoers:62:13: syntax error
sudo visudo -f /private/etc/sudoers.d/yabai
```
with the `-f` underlined
```bash
 /opt/homebrew/Cellar/yabai/HEAD-03b2483/bin/yabai -m space --focus 3
cannot focus space due to an error with the scripting-addition.
```
If there is anything else I can provide let me know.

**Comment by ekmekjian** [comment]
I'm not sure what happened but it works now

**Comment by ekmekjian** [comment]
It worked for a moment but then the issue returned

**Comment by ekmekjian** [comment]
I don't know what happened but it started again. Didn't mean to close the first time.

**Comment by tydomitrovich** [comment]
For the record, I encountered the same issue. It turns out I didn't read the docs carefully enough and blindly copied the line `sudo visudo -f /private/etc/sudoers.d/yabai` into `/etc/sudoers`. This was fixed once I removed removed that line from `/etc/sudoers` and added privileges to `/private/etc/sudoers.d/yabai`.
