### ISSUE TITLE
yabai will cause the system running at a slow speed.

### ISSUE THREAD

**Issue by zer0yu** [koekeishiya/yabai#1590]
yabai will cause the system to run at a slow speed. It's a problem with yabai itself or my configuration file. I need help.

OS info:
```
macOS 12.6.2 21G320 x86_64
```

config like:
[yabairc](https://github.com/zer0yu/dotfiles/blob/main/yabai/yabairc)

**Comment by jrock2004** [comment]
Did you find out what was causing it?

**Comment by zer0yu** [comment]
I still haven't found the corresponding reason.

**Comment by jrock2004** [comment]
I know what helped me was having a bad config for skhd. Once I found an issue, performance has improved on my intel mac. My m1 mac had no slow downs at all

**Comment by zer0yu** [comment]
So it turns out that the incorrect configuration of skhd can also affect its performance. Can you tell me what your incorrect configuration was?

**Comment by peppy** [comment]
If you are seeing delays before skhd hotkeys activate, the cause is usually the system with event loop being delayed by some process with a global hook. TL;DR, something on your system listening for keyboard input its window isn't in the foreground (basically a keylogger) to consume it in some way.

You can generally trial-and-error closing other applications down until you find the culprit in a scenario like this.

I've found multiple cases so far:
https://github.com/pqrs-org/Karabiner-Elements/issues/3254#issuecomment-1287859361
https://github.com/keycastr/keycastr (when turning on mouse event display)
or potentially just having your mouse running at too high a polling rate (https://github.com/koekeishiya/yabai/issues/1061)

**Comment by zer0yu** [comment]
I will check my skhd configuration file to see if there are any similar issues.
