### ISSUE TITLE
yabai rule for an application and its window's title

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1627]
I am trying to move an specific application with specific title to the space 1. If I use only application name it works fine but doesn't work when i combine it with window title. Is it a known limitation or i am missing something?

works: `yabai -m rule --add app="^qutebrowser$" space=1`
doesn't work:`yabai -m rule --add app="^qutebrowser$" title="^Teams$" space=1`

yabai version: 5.0.2
macos: ventura 13.2

**Comment by koekeishiya** [comment]
Some windows spawn without a title and it sets the title after a short delay. Since yabai applies rules on creation; it sometimes looks at a window before the title has been set. This is a bit tricky to solve because we want rules to be applied before doing anything to the window, but we still want it to feel as responsive as possible.

We also do not want to reapply rules every time a window title changes. We could allow a rule to be applied upon the first title change after creation, but this would again be prone to the delay / latency issue mentioned above.
