### ISSUE TITLE
yabai isn't working anymore

### ISSUE THREAD

**Issue by rajeshmajumdar** [koekeishiya/yabai#1642]
Tried everything, idk what happened. yabai suddenly stopped working. Everytime I try `brew services stop yabai && brew services start yabai` it does tile the apps for a second then back to not working, although it is still showing that blue outlining the app. I think I only tried installing karabiner, after that yabai isn't working not sure though.

Tried reinstalling with removing from accessibility list, disabling SIP. IDK what's wrong.

**Comment by leggomuhgreggo** [comment]
Same. Started after most recent mac update, to Ventura 13.2.1

Apple is always trying to rain on our sweet window tiling parade.

**Comment by azinsharaf** [comment]
were i lucky that 13.2.1 didn't break my yabai? :)

**Comment by leggomuhgreggo** [comment]
Maybe it's an architecture / chipset thing?

I'm running on `2.3 GHz 8-Core Intel Core i9`

**Comment by azinsharaf** [comment]
ok, i am M1 Max chipset.

**Comment by leggomuhgreggo** [comment]
Doh! I thought I'd upgraded but turns out it failed because I had a pending xcode update, so I was still on `5.0.1`. Sorted that out and upgraded to `5.0.2`

Regrets for the confusion + thanks for the excellent tool.


#### Steps I took to resolve:
- `brew upgrade yabai` => encountered out of date xcode error.
- updated xcode (this takes a while)
- restarted for good measure
- accepted license with `sudo xcodebuild -license accept`
- `brew upgrade yabai` => successfully installed `5.0.2` 🎉 
- re-enabled permissions for new yabai version
- windows started rockin out again 🤘

**Comment by rajeshmajumdar** [comment]
Does yabai logs things, I am already on the latest update and I don't have xcode so idk what the issue is.
Although homebrew is throwing a warning stating `Calling plist_options is deprecated! Use service.require_root instead`

**Comment by rajeshmajumdar** [comment]
I tried removing all the whitelisted apps from yabairc and it's now working. But now I can't whitelist any apps.

**Comment by rajeshmajumdar** [comment]
```
# yabai -m rule --add label="Finder" app="^Finder$" manage=off
# yabai -m rule --add label="System Preferences$" title=".*" manage=off
# yabai -m rule --add label="Software Update" title="Software Update" manage=off
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="Spotify" app="^Spotify$" manage=off
```
Something wrong with the way I am whitelisting these apps.
