### ISSUE TITLE
mac monterey 12.0.1 Unable to perform load-sa

### ISSUE THREAD

**Issue by zxhTom** [koekeishiya/yabai#1671]
yabai: scripting-addition failed to inject payload into Dock.app!
yabai --version : v5.0.2

issues The solution idea was tried, but it was not solved

**Comment by darklyspaced** [comment]
Hi, I am experiencing the exact same issue. It was working just a few days ago and now it, for some reason that is unbeknownst to me, just stopped working and the payload will not inject. I have the same yabai --version as you but I am running Ventura 13.0.1 and didn't update between it working fine and it breaking.

**Comment by darklyspaced** [comment]
Ahh okay. I spent some time debugging it on my end and it turns out that I had cleared the boot-args for my computer which resulting in some settings messing up. All I needed to do was add back:
`sudo nvram boot-args=-arm64e_preview_abi`
Now it attaches properly for anyone who might have the same problem in the future!

**Comment by zxhTom** [comment]
Yes, you still have to feel the contribution of the boss

**Comment by WATERMELOUN3** [comment]
@darklyspaced that solved it for me too, thanks a lot!

**Comment by zxhTom** [comment]
邮件已收到！谢谢配合。
