### ISSUE TITLE
Long delay when created workspace

### ISSUE THREAD

**Issue by danteissaias** [koekeishiya/yabai#168]
A large delay occurs when creating a workspace with:

```
yabai -m space --create; id=$(yabai -m query --displays --display | grep "spaces"); yabai -m space --focus $(echo ${id:10:${#id}-10})
```
There is a large delay before the workspace is created, this issue persists in the latest version but was not present in previous versions. I have tested, this issue remains present on the master branch.

**Comment by marcelja** [comment]
This query shouldn't work in the current master since `yabai -m query --displays --display` returns a json structure, e.g. like here:
```
{
        "id":724057050,
        "index":2,
        "spaces":[2, 3],
        "frame":{
                "x":1680.0000,
                "y":-251.0000,
                "w":1920.0000,
                "h":1200.0000
        }
}
```

Could you try this:
`yabai -m space --create; index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && yabai -m space --focus "${index}"`

skhd example:
https://github.com/koekeishiya/yabai/blob/7641afd7fdf95101de6675a8e1b9bfafdc3b4c63/examples/skhdrc#L41-L43

**Comment by danteissaias** [comment]
Ah, okay cool that works.
