### ISSUE TITLE
After updating OSX (Ventura 13.3) and Yabai (5.03), changing spaces with skhd stopped working.

### ISSUE THREAD

**Issue by TuralAsgar** [koekeishiya/yabai#1686]

**Comment by seanptmaher** [comment]
Same issue here. It seems to work once I navigate to each window in turn, works for a few minutes, then stops working. This is the relevant function on my skhdrc:

```
alt - 1 : set index 1; eval "$(yabai -m query --spaces | jq --argjson index "$index" -r '(.[] | select(.index == $index).windows[0]) as $wid | if $wid then "yabai -m window --focus \"" + ($wid | tostring) + "\"" else "skhd --key \"alt - " + (map(select(."is-native-fullscreen" == 0)) | index(map(select(.index == $index))) + 1 % 10 | tostring) + "\"" end')"
```
Once I navigate to and focus the window itself in the workspace, navigation works. However, until I navigate to the workspace, I get this error: 
```
could not locate window with the specified id '54'.
could not locate window with the specified id '252'.
could not locate window with the specified id '60'.
could not locate window with the specified id '57'.
could not locate window with the specified id '54'.
could not locate window with the specified id '49'.
could not locate window with the specified id '594'.
could not locate window with the specified id '49'.
could not locate window with the specified id '44'.
```

How should I debug this?

I can't disable SIP because of corporate policy, which is why I'm not using 
`yabai -m space --focus n`

**Comment by cynicade** [comment]
Had the same problem here, in my case it had something to do with the scripting additions not being able to work properly because yabai didn't have the accessibility perms it normally needs.

Try this (when not on space 2 😅)

```
❯ yabai -m space --focus 2
```

If you get `cannot focus space due to an error with the scripting-addition` there's a high chance you need to make sure your permissions for yabai are correct in the system settings and load/reload the scripting additions.

You can also check the error log at `/opt/homebrew/var/log/yabai/yabai.err.log` for clues - in my case the answer was there(also useful to post those when making a bug report).

**Comment by ascandella** [comment]
I just ran into this myself, and managed to fix it with `brew reinstall yabai`, followed by `brew services restart yabai`. Note that the reinstall (even though it was still version 5.0.3, generated a different checksum, so I had to update my `/private/etc/sudoers.d/yabai` appropriately.

After I did this, I got a prompt to allow yabai to access Accessibility, and things started working again.

**Comment by TuralAsgar** [comment]
@ascandella, solution worked for me. You saved my day. My hands are so used to these, it would be impossible for me to work without. Thank you all very much!
