### ISSUE TITLE
Unable to remove borders

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#17]
Running yabai installed from HEAD using homebrew. Setting the border to 0 and turning the border off in the config does not remove the border.

**Comment by dominiklohmann** [comment]
This works for me on `HEAD` in my `~/.yabairc` file:

```
yabai -m config window_border off
```

Did you restart `yabai`?

**Comment by koekeishiya** [comment]
`0` and `1` are not valid values for configuration here. Use `on` or `off`. This is simply because I find reading strings bring semantic value and increases the understanding of the file, instead of looking at a bunch of numbers and having to infer that the setting is a toggle. `0` is also not a valid value for the `border_width`, as I felt like the proper solution was to explicitly disable borders, rather than just using a zero-width - both for clarity and performance reasons, as creating empty-borders would still be doing work and using RAM.

If you run yabai with the `--verbose`` argument you will get debug prints stating some error. It is also possible to check the exit code of a given command inside the config file and do something in response (although there is only a single code for OK and one for ERROR). Maybe these should be warnings rather than debug statements, aka they would also be printed to stdout (or stderr, I forget).

**Comment by capaldo** [comment]
my .yabairc is:
```bash
#!/bin/bash

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffd75d74
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        0.99
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
```

I also wanted to mention that opacity is not working at all for me either.

**Comment by koekeishiya** [comment]
The `--verbose` has to be specified to the running *yabai* instance, not the message client, but that is actually not necessary in this case - you can forget that I mentioned it.

If running `yabai -m config window_border off` does not print an error message in the console it was ran, everything should be fine. You can confirm that by checking that it has an exit code of 0: `echo $?` in bash. Just a reminder that toggling that border setting will only affect *new* windows, not existing ones. For it to affect existing windows you'd have to relaunch *yabai*. You can use `yabai -m window --toggle border` to toggle an existing border - but only for the focused window.

**Comment by capaldo** [comment]
Running `yabai -m config window_border off` did the trick. Nothing was shown in the console and exit code was 0. Thanks for your help. Not really sure why yabai wouldn't adhere to the config settings.

**Comment by dominiklohmann** [comment]
> Not really sure why yabai wouldn't adhere to the config settings.

Did you make your configuration file executable? `chmod +x ~/.yabairc` does that.

**Comment by capaldo** [comment]
Yes this fixed both the border and opacity issue. Thank you so much.

**Comment by limeless** [comment]
I have same issue with this, `chmod +x ~/.yabairc` and restart yabai service doesn't solve it,
so I use the ugly way just set colors to `0xf` to "turn off" the border with skhd.
`:: def : yabai -m config active_window_border_color 0xf`

**Comment by koekeishiya** [comment]
This works just fine for me and is likely a user error. Read my comments above for information on how to debug this. As a general note, it may be easier to just run yabai manually from a terminal instead of running it through brew services when you are trying to solve an issue. I've taken great care to output a lot of information regarding what is going on if you run with the *--verbose* option.

```
brew services stop yabai
yabai --verbose

# look at the output and see if things are processed as expected or if there are any error messages.
```
