### ISSUE TITLE
Service fails to install if ~/Library/LaunchAgents doesn't exist

### ISSUE THREAD

**Issue by aouerf** [koekeishiya/yabai#1728]
This issue seems to be because the plist path is opened without checking if the directory exists:
https://github.com/koekeishiya/yabai/blob/f4ad453b764e4ccd5a046ac7d0ea372a0ef6d418/src/misc/service.h#L96-L97
I believe the user experience here could be a bit better. I can make a PR for this when I get the chance, but I'm filing this issue in case someone can get to it before I do.

The same issue predictably exists for [skhd](https://github.com/koekeishiya/skhd/blob/1fddb7aaa221cb3e1063c2fd32fd7e19700acb95/src/service.h#L102-L103).

**Comment by koekeishiya** [comment]
Fairly certain this folder will always exist unless a user has specifically decided to delete it, in which I think failing is better than recreating it.

**Comment by aouerf** [comment]
It didn't exist after a fresh install of macOS, which is why I filed this issue since I had to dig in to figure out why it wasn't working since the error message wasn't very intuitive. I can definitely see where you're coming from though, so feel free to close this if you want to leave things as is.

**Comment by plotchy** [comment]
Thanks for reporting this, I ran into this issue just now on a fresh install.

**Comment by vhagedorn** [comment]
Sorry for necro, but adding on to the solution:

If the directory did not exist, and the user had created it manually (as in my case), the permissions would not allow the process to write to the directory. This can be fixed with a simple `chmod 775`.

I encoutered this issue with skhd, but these appear to have the same impl, so I'm leaving my comment here.

Cheers
-vadim
