### ISSUE TITLE
Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by TheBaum123** [koekeishiya/yabai#1750]
as the title says, when i try to run `brew services start yabai` or `brew services restart yabai` i get `Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file`. this has been happening for about a week now, and i do not know what causes it. i reinstalled yabai and that didnt fix it.

**Comment by qtaped** [comment]
https://github.com/koekeishiya/yabai/issues/1738

**Comment by rolfed** [comment]
I'm experiencing the same issue.

**Comment by pauldiloreto** [comment]
As @qtaped mentioned, this is a duplicate issue. Please search closed issues before posting a new one.

As you can see in the link, the command to start no longer uses `brew`, you should run `skhd --start-service` and `yabai --start-service` instead.
Also mentioning this here, since I ran into this issue. If you are still getting a similar error even with this new command, you may need to make a new directory here:
`mkdir /Users/{YOUR_USERNAME}/Library/LaunchAgents`

**Comment by TheBaum123** [comment]
Im sorry, it appears, that i accedentally didnt take off the open issues filter before looking at the issues yesterday. Thank you for helping me anyways and have a great day.
