### ISSUE TITLE
Deserialization Support / Defined Layouts

### ISSUE THREAD

**Issue by Kryan90** [koekeishiya/yabai#180]
In chunkwm, I had serialized a few layouts and would de-serialize them with skhd.

Is a similar function supported in yabai?

If not, is there a standard way of achieving a desired layout?

This is an example of one of saved layouts:
Browser full length on the left, editor and terminal stacked on the right
![Screen Shot 2019-07-31 at 3 42 53 PM](https://user-images.githubusercontent.com/18740821/62250601-8a713d00-b3aa-11e9-9d88-4f6834eec589.png)

**Comment by koekeishiya** [comment]
There is no layout serialization or deserialization system and I don't plan on implementing one. You could maybe do something using the *signal* system to automate your layout.

**Comment by Kryan90** [comment]
Ah, okay. I will read the signal docs and see if I can come up with a solution.

Thanks!

**Comment by dominiklohmann** [comment]
What's needed for both this and #184 is this:

- `parent-window` / `child-windows` attributes in window queries so the tree can be traversed in the correct order
- `split-ratio` attribute in window queries
- a command for setting the `split-ratio` directly, e.g. `yabai -m window [<sel>] split_ratio <value>`

**Comment by koekeishiya** [comment]
I'm currently not interested in making the aforementioned changes.

**Comment by choco** [comment]
Hello, in the process of migrating from chunkwm I noticed that this feature is missing, any particular reason? I find it extremely useful in some situations.

Would this be something you'd like to get contributed?

**Comment by koekeishiya** [comment]
> any particular reason?

I've opted not to implement it because the version in chunkwm feels like an incomplete solution as it is unable to track windows. I did experiment with that in chunkwm, but was not all that happy with that attempt, and I just haven't had the time to iterate on the problem yet.

I'm open to a contribution to such a system in general, but not if it is simply a copy of the existing version chunkwm had. I still think this can be solved in a much better way, given enough time spent.
