### ISSUE TITLE
Sticky without Float?

### ISSUE THREAD

**Issue by AlJohri** [koekeishiya/yabai#1843]
As a separate follow up to #1835, even with SIP disabled, is it possible to make a window "sticky" without floating it?

Based on #574, it seems this is impossible?

>If a tiled window is made sticky, it will implicitly float the window (because sticky windows cannot be tiled) using the same rules as a regular float.

>If a floating window is unfloated, it will implicitly clear the sticky bit (because sticky windows cannot be tiled), be set to normal window layer, and re-tile.

Essentially I want to have my notes application open on all spaces without it being "topmost". I want it "titled" next to the rest of my windows, ideally on the left like a sidebar.

Is there anyway to achieve this?

**Comment by koekeishiya** [comment]
Sticky windows will not be tiled, because it is impossible to make it tile into the same slot in every space, causing the window to jump around when switching spaces. 


It is in theory possible to create something like a sidebar-mode that sticky windows are pushed into, but I think you are better of setting a *padding_<dir_>* and using the window move/resize commands to place the sticky window where you want it to be.
