### ISSUE TITLE
Regular expression matching for rules causes lag

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#19]
I tracked this down to this function:

https://github.com/koekeishiya/yabai/blob/4e1f43b924cbded5cb6a508ceb7cd9248beed47a/src/misc/helpers.h#L125-L138

`regcomp` does not need to be called for every iteration, since the regular expression never changes. Preparing the regex takes a lot of work, which should only be done once—when the rule is created.

**Comment by koekeishiya** [comment]
I don't really get why preparing a regex should be a hard problem that causes this kind of an issue, but heck what do I know. Will implement your proposed solution later today.

**Comment by dominiklohmann** [comment]
In general compiling a regex object takes way longer than the actual comparison, that's always been the case. Not sure if the regex implementation in libc optimises for text-only comparisons. I started noticing visible lag with just 10 rules, e.g.:

```
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on opacity=1.0
```

(This example actually showcases another issue, which is that app names can be localised, so having some way to use the unique bundle identifier com.apple.DigitalColorMeter instead would be lovely.)

**Comment by koekeishiya** [comment]
Do you think it is necessary to support application name if we can accept the bundle identifier instead? Trying to minimize bloat.

Sent from my iPhone

On 3 Jun 2019, at 08:58, Dominik Lohmann <notifications@github.com<mailto:notifications@github.com>> wrote:


In general compiling a regex object takes way longer than the actual comparison, that's always been the case. Not sure if the regex implementation in libc optimises for text-only comparisons. I started noticing visible lag with just 10 rules, e.g.:

yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on opacity=1.0


(This example actually showcases another issue, which is that app names can be localised, so having some way to use the unique bundle identifier com.apple.DigitalColorMeter instead would be lovely.)

**Comment by dominiklohmann** [comment]
I think app name is the more important filter compared to bundle identifier, as it's a lot easier to use. Telling people to look up the bundle identifier for applications in the application bundles Content/Info.plist file is just asking for a lot of issues. Maybe it's just fine with the regex support as is, especially considering how few people deal with more than one locale at a time. 

It may be technically more correct to use bundle identifiers, but they will not help achieve anything new.

**Comment by koekeishiya** [comment]
It is easy enough to output the bundle identifier in the result of a window query command, so I suppose the only difference would be that they would either as you say lookup the *bid* manually, or run a query command, where as with the app name they can simply look at the menubar / process manager.

My initial reasoning for going with the app name rather than the *bid* was to allow a single rule to hit multiple applications based on the provided pattern. I feel like that is easier to hit when using the application name than it would be with bundle identifiers. However, I don't particularly use that part of it myself and if that holds true for other users as well - I see no big reason not to make the switch.

**Comment by dominiklohmann** [comment]
Honestly I don't want to deviate from the original issue too much, because that's still a thing, but I'm coming to the conclusion that application names are better than bundle identifiers. Think about the most troublesome of applications, Emacs, for example: I don't think it has a bundle identifier at all and even if it does, is it the same between different Emacs distributions?

**Comment by koekeishiya** [comment]
I'll stick to app name only for now then. If this turns out to become really annoying, let me know and we can add both I suppose. As I mentioned earlier I'm trying to find a better balance between useful options and what I consider to be bloat. Having too much complexity / many options also make things harder to understand / keep up with.

**Comment by dominiklohmann** [comment]
> Having too much complexity / many options also make things harder to understand / keep up with.

Indeed. Discussing features more and saying no to most of them is completely fine with me, especially if it makes the issue board less helpdesk-esque (if that is a word). I still have some things on the back of my mind, but will mostly stick to issues about regressions and bugs and writing docs.

Additionally there'll be the yearly macOS beta thread in just a few hours to have one thread for people to stick to and to upload new versions of Dock.app. I'll create the thread shortly after I got 10.15 running on a device and will update it regularly as usual. 
As a side note: I won't do this for chunkwm this year, I think. Not sure if it's worth the time or if you even want to update chunkwm for 10.15.

**Comment by koekeishiya** [comment]
> As a side note: I won't do this for chunkwm this year, I think. Not sure if it's worth the time or if you even want to update chunkwm for 10.15.

I agree with this. You've probably noticed but I've archived the *chwm-sa* repository and moved the source files directly into the yabai repository and integrated it with the build system.

The scripting addition for yabai also uses a unix file instead of listening on port 5050. The port 5050 thing was mainly just something I did while experimenting with scripting additions, and it sort of became a permanent thing. Figured it was time to sort that out.
