### ISSUE TITLE
Yabai scripting-addition payload (0x0) doesn't support macOS 14.1 (23B74)

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#1936]
Whoops, here we go again! 😁

![yabai scripting-addition payload (0x0) doesn't support this macOS version!](https://github.com/koekeishiya/yabai/assets/103744/885eab81-5f61-408c-9623-e7674a0487af)

I'm sure we'll get an update soon!

**Comment by roelvangils** [comment]
I am also praying for an update, but let's not put pressure on @koekeishiya 😁

**Comment by jacobg-jellyfish** [comment]
no pressure, none at all ;P  .. not to mention the top of the bar seems to take into account the mac os menu bar height regardless of whether it hides or not ;p

**Comment by adkillick** [comment]
Hi folks, I've been a heavy user of the Scripting Addition and I'm looking forward to using it again! Like you, since upgrading to Sonoma I haven't been able to use it but I'm not getting that pop-up. I believe I have the SA properly loaded etc but I get no error messages or feedback in both log locations (`/tmp/yabai_$USER.out.log` and `/tmp/yabai_$USER.err.log`) when I try commands that require the SA. Should I be seeing something (popups?, errorlogs?).

**Comment by Explosion-Scratch** [comment]
This just started happening to me as well, happy to debug if needed. An update would be much appreciated, happy to help in any way I can!

**Comment by Mmasson-01** [comment]
+1 for this @koekeishiya. I tried to figure out what you did here: https://github.com/koekeishiya/yabai/commit/ea834ac67193c4d6e07c7b070ba8a3cce23b90fe for 14.0.0. Maybe a hint on your process to help fix it?

**Comment by ipstone** [comment]
> +1 for this @koekeishiya. I tried to figure out what you did here: [ea834ac](https://github.com/koekeishiya/yabai/commit/ea834ac67193c4d6e07c7b070ba8a3cce23b90fe) for 14.0.0. Maybe a hint on your process to help fix it?
> 
> meanwhile, here's a temp workaround to switch spaces proposed by Koekeishiya
> 
> ```
> alt - 1 : skhd -k "ctrl + alt + cmd - 1"
> alt - 2 : skhd -k "ctrl + alt + cmd - 2"
> alt - 3 : skhd -k "ctrl + alt + cmd - 3"
> alt - 4 : skhd -k "ctrl + alt + cmd - 4"
> alt - 5 : skhd -k "ctrl + alt + cmd - 5"
> alt - 6 : skhd -k "ctrl + alt + cmd - 6"
> alt - 7 : skhd -k "ctrl + alt + cmd - 7"
> alt - 8 : skhd -k "ctrl + alt + cmd - 8"
> ```
> 
> Map the shortcut in mission control to make it work.

hello, I am new to yabai/skhd, but experiencing this same issue. I don't quite understand the point of using alt-1,2,3 ... would you elaborate what this is doing here with mapping it to : 
```
alt - 1 : skhd -k "ctrl + alt + cmd - 1"
```

How is it different from using ctrl +1, 2, 3 ... as usually mapped for space switching using mission control?

Thanks

**Comment by Mmasson-01** [comment]
> How is it different from using ctrl +1, 2, 3 ... as usually mapped for space switching using mission control?

@ipstone  not different but then you can use ctrl for something else. The idea was at first to use this mapping as a fallback if Yabai throws an error, but it's not.

Here's the initial fallback solution:

```
alt - 1 : yabai -m space --focus 1 || skhd -k "ctrl + alt + cmd - 1"
```

**Comment by bigduu** [comment]
> +1 for this @koekeishiya. I tried to figure out what you did here: [ea834ac](https://github.com/koekeishiya/yabai/commit/ea834ac67193c4d6e07c7b070ba8a3cce23b90fe) for 14.0.0. Maybe a hint on your process to help fix it?
> 
> meanwhile, here's a temp workaround to switch spaces proposed by Koekeishiya
> 
> ```
> alt - 1 : skhd -k "ctrl + alt + cmd - 1"
> alt - 2 : skhd -k "ctrl + alt + cmd - 2"
> alt - 3 : skhd -k "ctrl + alt + cmd - 3"
> alt - 4 : skhd -k "ctrl + alt + cmd - 4"
> alt - 5 : skhd -k "ctrl + alt + cmd - 5"
> alt - 6 : skhd -k "ctrl + alt + cmd - 6"
> alt - 7 : skhd -k "ctrl + alt + cmd - 7"
> alt - 8 : skhd -k "ctrl + alt + cmd - 8"
> ```
> 
> Map the shortcut in mission control to make it work.

Yes, this is the root cause, the minor update from Apple, include update the Dock as well, so sa can't find the correct function address in the Dock.app, make the space functional not work, but I'm don't have the hack experiences, can't not help that

**Comment by koekeishiya** [comment]
I'm not interested in spending my time teaching people who reverse engineering works, sorry. There are lots of material available on this topic already if you go looking.

**Comment by bigduu** [comment]
> I'm not interested in spending my time teaching people how reverse engineering works, sorry. There is a lot of material available on this topic already if you go looking.

Yes, thanks for you reply, we can only find the other solution to instead of yabai way if this is really take much time, I mean the way e.g: through Console.app or Monitor.app to find the address not step by step. 
Can I ask why yabai-sa need hook the Dock to implement space function? I find switch the spaces focus seems not need hook Dock, the `CGSManagedDisplaySetCurrentSpace`, `CGSShowSpaces` and `CGSHideSpaces` can do that, not sure the create and destroy need this, but seems the most user want to switch the space focus is enough. 
Do you think it's possible? and if like that do you have some suggestion for that make we can skip the limitation?

**Comment by juliends** [comment]
Some issues (maybe all) are solved by the last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61)
Focusing the next space is operational again 🎉 

You will need to run Yabai from [HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) in order to try it for yourself

Thanks @koekeishiya 🙏

**Comment by bigduu** [comment]
Really good news! Thanks a lot @koekeishiya !!!!

**Comment by ccimponeriu1996** [comment]
Thanks so much you are a hero @koekeishiya

**Comment by erlingur** [comment]
Thanks a lot @koekeishiya!! Really appreciate it!

**Comment by roelvangils** [comment]
Thank you for all your hard work, @koekeishiya. All works perfectly fine again for me on 14.1.1. It feel like I have all my super powers back! 🪄

**Comment by kkreso** [comment]
> Thank you for all your hard work, @koekeishiya. All works perfectly fine again for me on 14.1.1. It feel like I have all my super powers back! 🪄

Same here (14.1.1) - many thanks @koekeishiya .

**Comment by koekeishiya** [comment]
Works fine on 14.1.2.
14.2 will be added when it is out of beta.

**Comment by roelvangils** [comment]
I can confirm! It's safe to upgrade to 14.1.2.

![20231201_124817_System Information@2x](https://github.com/koekeishiya/yabai/assets/103744/0b46ba2c-ee0e-4080-9181-369b1c54b20a)
