### ISSUE TITLE
help with filtering signals

### ISSUE THREAD

**Issue by Who23** [koekeishiya/yabai#195]
Hello,
I've been having trouble with filtering signals and only applying the actions to specific windows. I've read the docs, but I don't know why it isn't working.

 I have a window called 'statuswin' that when moved, is re-moved back to it's original spot. Here's what I have in my `yabairc`

```
yabai -m signal --add event=window_moved title=statuswin \
    action="yabai -m window $YABAI_WINDOW_ID --grid 20:20:15:0:5:4"
```

However, it seems to apply this action to *every* window I move. Could someone help me with this? Am I missing something obvious?

Forgot to add I don't have the scripting addition, or SIP disabled. I don't think it should affect it though, since I'm just moving a window?

**Comment by dominiklohmann** [comment]
So there's three issues with this:

- The `app=` and `title=` filters are only implemented on current master and are not in the release version.
- Think carefully: Where is `$YABAI_WINDOW_ID` evaluated? Currently, it is located within double quotes in an executable file, so it is evaluated in your yabairc instead of when executing the action. Use single quotes instead or escape the variable using `\$YABAI_WINDOW_ID`.
- The filters take a regex. If you want to match, say, the window named exactly statuswin of the application iTerm2, you would be better of filtering by `app="^iTerm2$"`  and `title="^statuswin$"`.

Please also note that yabai cannot read window titles on macOS Catalina (yet).

**Comment by Who23** [comment]
Oh! I see the problems with this. I'll close this issue as the filters aren't even implemented yet. Thanks for the help!

**Comment by dominiklohmann** [comment]
Well they're implemented, just not in the current release version. You can check the [unreleased section of the changelog](https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#unreleased) for more info on what's coming with the next release.

**Comment by Who23** [comment]
yes sorry i used the wrong word I meant not in the lastest release
