### ISSUE TITLE
Issues with yabai after computer wakes from sleep

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#1979]
I am having issues where sometimes after computer wakes up after sleep yabai stops working. I suppose that has something to do with new instances being created, since recently tis happened I had to give permissions to a new yabai, and the old yabai had an icon removed. It often happens that if I wake up the computer, I actually have to restart it because yabai does not work properly. Furthermore, when I run it, I always get the PID file lock abort error.

**Comment by fkajzer** [comment]
if this happens, you can restart yabai with `yabai --service-restart` instead of restarting your machine. 

I also have some issues with yabai after waking from sleep since upgrading to sonoma, where my skhd shortcuts are run with ~5 seconds delay after waking from sleep. But i did not really find out when exactly this happens, seems random.
I think this issue is actually related to yabai instead of both yabai and skhd, since only restarting yabai fixes this for me.
