### ISSUE TITLE
migrating from chunkWM

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#2]
Is it safe to assume this is replacing chunkWM moving forward? As of right now is it stable enough to replace chunkWM?

As usual, thanks a million for all your work.

**Comment by koekeishiya** [comment]
I'm undecided about the future of chunkwm moving forward. I will probably do a final release of chunkwm with the changes that has made it into master - and archive the repository, when this is ready for a v1.0.0 release. It is looking pretty good so far, from my experience.

This is stable enough to replace chunkwm now, yes, and also has full support for multiple display (at east from my testing) - something which is lacking in chunkwm. All the features I want to implement have pretty much been finished ported from chunkwm, with tweaks to some of the functionality. The main features that chunkwm offer that has not made it into this version is the *monocle space layout*, and the *desktop serialization system*. There are minor configuration settings that I've ignored on purpose, and there may be other things that I have forgotten, but then they were probably not very important anyway.

Features that are lacking, but will be implemented, include some sort of window rules system, as well as the ability to query more information. Some query stuff has been implemented for retrieving information about open windows, and spaces, as well as the ability to read the current value of a config setting. The query to retrieve spaces and display information will be changed, but I added some temporary stuff to get my bar working until the final system is implemented.

Documentation will be updated when I have the time and motivation to do so, otherwise most commands correspond to whatever their name used to be in chunkwm. Looking at the example skhdrc and yabairc config in this repository should help plenty. Otherwise, all defined commands and arguments are defined at the top of: https://github.com/koekeishiya/yabai/blob/master/src/message.c

**Comment by acmcelwee** [comment]
👋 - `chunkwm` lover here, and someone also interested in this project. Your tools continue to make my day-to-day workflows on MacOS much more productive, so thanks for that.

Yesterday I setup `yabai` via homebrew (`yabai version 0.1.0`) and started a new yabai-focused `.skhdrc`, and an easy way to switch back and forth between my current `chunkwm` + `skhd` config and `yabai` + the updated config. So far, the directional window focusing is the only thing that I believe is "implemented" but isn't working (`yabai -m window --focus north|east|south|west`). 

My question is: Is it helpful for people to try this out and creating issues to help identify gaps? Or is it the project at the point where it's just annoying for people to submit issues, because you aren't ready to comb through the issues that others encounter? Either way, let me know and I'm happy to comply with what you think makes the most sense.

**Comment by bysimeon** [comment]
adding on here. recently made the transition as well. wanted to note that when a space is on float, manually adjusted window size will work, but after you adjust the window size it may be readjusted by yabai [i've attached a gif]

![yabai](https://user-images.githubusercontent.com/18429469/57987756-b5a2ec00-7a4b-11e9-82eb-c29e5bc66234.gif)

**Comment by koekeishiya** [comment]
> adding on here. recently made the transition as well. wanted to note that when a space is on float, manually adjusted window size will work, but after you adjust the window size it may be readjusted by yabai

Good catch. We detect when a window is resized using the native macOS resize-handle and adjust our layout correspondingly. This code incorrectly triggered for non-managed windows (aka floating windows).

> So far, the directional window focusing is the only thing that I believe is "implemented" but isn't working (yabai -m window --focus north|east|south|west).

Directional focusing work in tiled spaces, but they may be a bit buggy when floating windows are involved. This is because I originally wanted to allow them to focus the first window in a given direction regardless of which state the window was in. This turned out to be a bit harder than I expected with the calculation that I currently have implemented.

> Is it helpful for people to try this out and creating issues to help identify gaps? Or is it the project at the point where it's just annoying for people to submit issues, because you aren't ready to comb through the issues that others encounter? Either way, let me know and I'm happy to comply with what you think makes the most sense.

If you are running the master branch and find something that is not working as the documentation suggest, feel free to open an issue. I'd rather not have feature requests and so on in the current state.

**Comment by simonsmith** [comment]
> The main features that chunkwm offer that has not made it into this version is the monocle space layout

Does this mean we wouldn't see a monocle mode at all?

**Comment by koekeishiya** [comment]
> Does this mean we wouldn't see a monocle mode at all?

Undecided at this point. Will see as more progress is made.

**Comment by BlueDrink9** [comment]
Just wanted to chime in on the whole "replacing chunkwm" thing: The readme suggests the script addon is *required for all* yabai features - is that in fact the case? Because if so, I can imagine a huge number of people not wanting to disable SIP, and therefore preferring to stay with chunkwm

**Comment by pcr910303** [comment]
@BlueDrink9 Please see #13.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BlueDrink9** [comment]
Ah, thank you for that. Hopefully this comes up in searches now. Fully support, shame about the focus issue - for this single-monitor user, it's been a favorite and flawless feature

**Comment by koekeishiya** [comment]
@BlueDrink9 

IF you don't  care about the other functionality, try to clone the repo and toggle the ifdef in the function `window_manager_focus_window_with_raise` (in *window_manager.c*). This will enable same window focus mechanism that *chunkwm* uses.
