### ISSUE TITLE
Xcode editor breaks when yabai is running

### ISSUE THREAD

**Issue by domfz** [koekeishiya/yabai#2010]
Maybe someone knows a way to fix this. In Xcode there is this bug that happens rarely when yabai is off, and ALWAYS when yabai is on.

Here's what's happening:

- Build a project and click back into editing code
- Type something -> nothing happens
- Click somewhere inside the editor -> previously typed stuff gets pasted

Also every click into the editor seems delayed and selects the text between two clicks, sometimes moves the text and is generally buggy. After like 4 or 5 clicks everything turns back to normal. 

This makes yabai unusable when working on a project and building UIs where I have to build the project pretty often. Is anyone experiencing this?

**Comment by P4RK-J4EWOONG** [comment]
I also have this happen. 😢 

Also, whenever Xcode tries to show a preview of the UI, it creates an empty space. So I just blocked yabai from managing Xcode.

**Comment by wojciech-kulik** [comment]
Yes, Yabai is completely broken, but nobody wants to fix that. I created an issue about the same problem:
https://github.com/koekeishiya/yabai/issues/1877

I have also found a root cause. You can fix it on your own by changing the code (one line) and compiling Yabai.

However, after some time I decided this tool is too buggy, glitches are too annoying and it's easier no to use it. If possible I recommend focusing more on terminal for daily work, it gives a much bigger flexibility especially if you use tmux and Neovim.

**Comment by koekeishiya** [comment]
Unable to reproduce on the lastest master. 

If you have this issue on the lastest master please create a minimal bogus POC Xcode project in which this issue happens. A screenrecording would be helpful too.
