### ISSUE TITLE
Apps opened as shortcuts do not receive focus.

### ISSUE THREAD

**Issue by eomdohyeon** [koekeishiya/yabai#2030]
My ".skhdrc" file has the following settings. 
Pressing cmd + return opens the iterm2 window.
```
# open terminal
cmd - return : /Applications/iterm.app/Contents/MacOS/iterm2 --single-instance -d ~ &> /dev/null
```
Previously, when you opened an app with that shortcut, the focus would be set automatically.
But now when I open the app it is out of focus and pointing to "Finder".

It's inconvenient to have to move the mouse to refocus to point to a newly opened app.

This issue occurred after the Sonoma 14.2 update.
I tried the settings below, but the symptoms are the same.
![image](https://github.com/koekeishiya/yabai/assets/83337136/ff460035-37f7-4d49-a674-a2f9c675c3d3)

Version information: `Sonoma 14.2.1` / `yabai-v6.0.2` / `skhd-v0.3.9`

**Comment by ognistik** [comment]
It seems to be a new Sonoma issue and not so much a problem with Yabai. It happens to me with every application. Specifically when the app is in a different space. It will move to the space where the window is, but focus on Finder. And it doesn't only happens with key bindings for opening apps in skhd, it also happens with my app switcher Contexts, or RCMD.

I have added this line to my yabairc configuration which fixes it for me (with some obvious focus shifting, since I have opacity enabled). 
```
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
```
This will focus on the last window that Yabai remembers after a space switch. It seems like the actual shortcut or action to switch to the app or window does get recognized by Yabai. If anyone knows a better fix would love to know.

**Comment by rcorre** [comment]
I encountered this after updating to OSX 14. @ognistik's solution does not seem to help. I have the following `yabairc`:

```
yabai -m config \
	layout bsp \
	window_opacity on \
	auto_balance on

yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
```

In `skhdrc`, I have:

```
cmd - return : wezterm start --always-new-process
```

When I press cmd-return, the new terminal is not focused. Focus remains on the previously focused window.

**Comment by frixaco** [comment]
Same issue. I'm using latest `Sonoma@14.2.1`, `Yabai@6.0.9` and `skhd@0.3.9` with **WezTerm** terminal. Workarounds mentioned above didn't help unfortunately.

```
ctrl + cmd - t : /Applications/WezTerm.app/Contents/MacOS/wezterm start
```

**Comment by koekeishiya** [comment]
This is a macOS issue. See this comment for an Alacritty workaround. Replace "alacritty" in the app filter to adjust for other applications: https://github.com/koekeishiya/yabai/issues/1858#issuecomment-1904815407
