### ISSUE TITLE
Request: make it a bit easier to update

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#2096]
I noticed that @koekeishiya is on a roll with releasing small updates. That's great! 🦾 As someone who always seeks the latest features, I have been updating to each new version. However, I am wondering if there is a way to automate the update process for the `/private/etc/sudoers.d/yabai` file, which contains the authentication information for loading the scripting addition.

Currently, updating this file is a manual process, which can be challenging for new users (you have to run `echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"` and use that output to overwrite the sudoers file). Perhaps it would be helpful to semi-automate the process by introducing a command like `yabai setup`. This command could guide users through the update process and prompt them to enter their admin password when the file is about to be overwritten?

**Comment by koekeishiya** [comment]
If you know what you are doing, the following one-liner can be used to update the sudoers file correctly:

```
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
```

I have also created an installer script that can be used instead of homebrew because of the issue with having to re-grant acccessibility permissions for every upgrade because of reasons:
>I guess this is happening because macOS stores the absolutepath when saving permissions, because yabai is a single binary application and not an app bundle. When homebrew upgrades yabai it places it in a folder specific to the version, so every brew upgrade causes the binary to be stored at a different path, effectively resetting the permissions.

A codesigned binary release can be installed using the yabai [installer script](https://github.com/koekeishiya/yabai/blob/master/scripts/install.sh); it will always point at the latest release version.

```
# install yabai binary into /usr/local/bin and man page yabai.1 into /usr/local/man/man1
curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin

# install yabai binary into ~/Software/bin and man page yabai.1 into ~/Software/man
curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin ~/Software/bin ~/Software/man
```

This has all been added to the wiki in the "Install latest release version" section.

Ref: https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1939670967 and https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1941363232

Having a yabai command `yabai --configure-sudo` or something that updates the sudoers.d/yabai file could maybe be a thing, but I very much want users to understand exactly what modifications they are doing to their system.

**Comment by roelvangils** [comment]
Thanks! Perfect answer 😉

**Comment by s1dc0des** [comment]
mouse and keyboard are stuck after updating, `brew upgrade`. it asks for acccessibility permission. which i cant grant because i cant use mouse and keybaord. super annoying.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/2040#issuecomment-1894500655

The instructions explicitly states that you should stop yabai before upgrading.
