### ISSUE TITLE
scripting addition does not support macOS Sonoma 14.4

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#2150]

**Comment by PrayagS** [comment]
Tried multiple times by installing from HEAD but every time I get the error that payload isn't supported on this macOS version.

**Comment by koekeishiya** [comment]
Fixed on master.

Note that there are tons of breaking changes on master compared to the last released version, and there will likely be more breaking changes before a new release is made.

Consult the changelog before you consider building the master branch from source.

**Comment by PrayagS** [comment]
Thanks for the quick fix! That did the trick.

Not seeing any issues as of now. Will do the job until the next release comes out 🤞🏼

**Comment by PrayagS** [comment]
> I built from master just now, but I still see the error that payload isn't supported on this macOS version. Did I do something wrong? Running on Apple Silicon. Updated using the wiki guide ([Wiki: Installing yabai (from HEAD) (updating to latest head) ()](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head))

@rxbn Try the following steps,
```sh
yabai --uninstall-service
sudo yabai --uninstall-sa
# uninstall and reinstall yabai or build it
sudo yabai --load-sa
yabai --install-service
yabai --start-service
# might have to restart again after giving it permissions
```

Uninstalling and re-loading the payload would be required I guess because of the change in the OS version.

**Comment by funkey** [comment]
Can confirm that the fix is working (M1 Pro), following the steps by @PrayagS above. In addition, I found it necessary to remove all previous yabai versions from the "Accessibility" and "Screen & System Audio Recording" lists under "Privacy & Security". Seems macOS got confused by the previous entries and entered an infinite loop asking for permissions for the new executable. The "breaking changes" since the last release didn't break anything on my end (running a not-too-fancy configuration here, YMMV).

I just also want to use this opportunity to thank you @koekeishiya for the great work on yabai and the prompt fix. As a multi-decade Linux user, it is yabai that made my Mac usable for me. Thanks a ton for that. Just signed up for you [patreon](https://patreon.com/aasvi) :)

**Comment by jwhit445** [comment]
Can confirm it works on Sonoma 14.4 (23E214)! No scripting errors and space changes are working again.

**Comment by IanQS** [comment]
I'm still running into the "Loader quit unexpectedly" issue, even when I followed the instructions from @PrayagS. This happens on brew and installing from the `curl`.

Here's what I ran

```
yabai --uninstall-service
sudo yabai --uninstall-sa
brew uninstall yabai
brew install koekeishiya/formulae/yabai
```

Then, just in case my current configs (located in `~/.config/yabai/yabairc` and `~/.config/skhd/skhdrc` have issues, I copy the configs that are output during the brew install process to my home directory

```
cp /opt/homebrew/opt/yabai/share/yabai/examples/yabairc ~/.yabairc
cp /opt/homebrew/opt/yabai/share/yabai/examples/skhdrc ~/.skhdrc
# verify that the contents of the sudoers file is still correct, and it is.
sudo yabai --load-sa
```

and it outputs that the loader quite unexpectedly via a GUI popup :/ What's interesting is that when I ignore the error, I can do certain things like

```
yabai -m window --focus {NSEW}
yabai -m window --space 1
```

but I can't do `yabai -m space --focus 1`, as that outputs `cannot focus space due to an error with the scripting-addition.`

---

When I installed via the `curl`, when I get to the `sudo yabai --load-sa`, I also tried running `yabai` and it ran into `yabai: scripting-addition failed to inject payload into Dock.app!`

Might anyone know what is going on? I don't think it's my `yabairc`, as the issue appears even on the recommended yabai, and it seems consistent across the various install modes

**Comment by PrayagS** [comment]
> I'm still running into the "Loader quit unexpectedly" issue, even when I followed the instructions from @PrayagS. This happens on brew and installing from the `curl`.
> 
> Here's what I ran
> 
> ```
> yabai --uninstall-service
> sudo yabai --uninstall-sa
> brew uninstall yabai
> brew install koekeishiya/formulae/yabai
> ```
> 

@IanQS These changes are not yet released. You'll have to build against HEAD,
```sh
brew install koekeishiya/formulae/yabai --HEAD
```

**Comment by danni-storm** [comment]
Apologies for adding another post to this thread but I am curious if we install against HEAD, will Brew install the stable release once it's out or will we have to reinstall to get the stable release?

**Comment by gegoune** [comment]
@danni-storm The latter.
