### ISSUE TITLE
Rounded borders don't conform to window corners at small widths

### ISSUE THREAD

**Issue by epetousis** [koekeishiya/yabai#216]
It looks like yabai's window borders seem to not quite conform to the corners of each window when using a 1px or 2px border width. I'm not sure if being on the 10.15 developer beta is causing the issue or whether this is just a result of the border radius calculations that happen in border.c.

Take a look at these pics, there's a noticeable gap between the corner of the border and the corner of the window:

![window border 1px](https://user-images.githubusercontent.com/853461/63212599-694e7180-c14a-11e9-940d-fc5acbcf2c17.png)
![window border 2px](https://user-images.githubusercontent.com/853461/63212606-7bc8ab00-c14a-11e9-81fe-a29c8dcbb386.png)

**Comment by koekeishiya** [comment]
Various applications have different border widths. Not sure if there is a one-size-fits-all approach here.

**Comment by tsujp** [comment]
I've noticed that since I did my windows-have-square-borders hack that _all_ Yabai borders fit nice and snug, this is because at a `border_width` of `3` the Yabai border perfectly masks the square corner, going even larger than that works fine too. It actually works from a `border_width` of 2 or above.

Here's a GIF demo below, I had to compress it to keep the size reasonable. Here's a direct MP4 link on imgur if you want that instead: https://i.imgur.com/NFInlpY.mp4 (31 seconds)

![thegoodstuff](https://i.imgur.com/YpdqYd1.gif)

Notice that Finder has a square border here, and that with a`border_width` of 2 or more it looks really good, I expand it to 10 to exaggerate the effect and move Finder around to show that under the border things are in-fact still square. It's not a perfect solution because it requires patching some SystemAppearance.bundle files _but_ if you plan on using borders _and_ not having them fit irks you I'd say I recommend it.

**Comment by koekeishiya** [comment]
That looks pretty good, yeah. I haven't looked into actually modifying the system files, so I have no clue whether that can lead to potential problems with updates, or if it simply requires a re-patch after an update has been installed. Are they fairly trivial to maintain?

Alternative solutions would be to have a config option to specify if the border should be *outside* (current behaviour), *inside* or *in-between* the window. If the border is *in-between* it will occlude a small part of the window (depending on the width), but should also make it fit/look better imo.

**Comment by tsujp** [comment]
@koekeishiya it was not trivial to find what to edit in so far as there is lots to slog through but for getting system windows to have square edges there are only 2 types of files to patch and for square edges it's even more trivial since the texture is just a square.

1. A file which defines some effects to apply to the window, this is the `base` and in my setup I set it to completely transparent. Normally this is applied to the top of the window giving it a very subtle while line that curves at the edges; so the edit here is just make 4 texture sizes all empty png files.
2. A file which defines the window mask, it's a luminance map so black = show it and white = hide it, all I did was set all 4 textures to pure black and there we go square borders.

There are technically 16 files; a set for each of `small` and `regular` (unsure _exactly_ what these are) displays(?), then 1x and 2x resolution variants, and then `active` and `inactive` variants which I assume apply to active and inactive windows. Since everything is the same – a pure black box of a texture – you only need to edit this down to 8 files to apply the effect, and even then that _might_ be 8 times too many as when I first tried it I just slammed the same 30x30px png for all and it worked fine.

Here's a repo I made for the square edges that I made today:

Original files: https://github.com/tsujp/square-macos-windows/tree/master/DarkAquaAppearance/WindowFrame_WindowShapeEdges/Original

Edited files: https://github.com/tsujp/square-macos-windows/tree/master/DarkAquaAppearance/WindowFrame_WindowShapeEdges/Edited

Maintenance as far as I'm aware would just be to patch these if updating macOS changes them in any way; unsure as I have just done this today and so I have no idea what kind of updates affect this. They persist through reboots etc as I rebooted many-a-time to get this working as I tried things; later on I realised I just had to kill Finder to get it to re-register and close and reopen other apps to get them to re-register the new assets.

**Comment by koekeishiya** [comment]
I've added support for selecting how the borders are placed relative to the window.
On master there are now three options: 

1. exterior (identical to how it has been lately)
2. interior (draws exactly on top of the window frame)
3. inset (50%-ish of the border is exterior, and the other half is interior)

**Comment by choco** [comment]
Would it be possible to make the last thing (active border topmost) an option? I don't use the scripting addition so I can't disable shadows, so when using the external border and clicking on the window it get brought above the border itself, messing the color of the border (since the shadow is drawn above)

**Comment by koekeishiya** [comment]
Seems like a reasonable request. I don't remember at this time why the active border isn't always topmost. Probably something to do with other topmost windows and/or autofocus or something.

Hmm I wish there was some other way to solve the issue where a window that is clicked on gets raised above the border window (I tried to hook up to occluded events for the border windows, but that did not seem to trigger..), same with the shadow issue, although I have all shadows disabled for now.

**Comment by tsujp** [comment]
I've noticed window borders are blurry if you use `inset` for the `window_border_placement`, if I change it to `exterior` they are sharp again. I'm running off of master via `brew install --HEAD yabai`.

**Comment by koekeishiya** [comment]
They are just as sharp in all 3 placements for me. Likely something to do with window shadows as mentioned by cHoco earlier, or something specific to your system.

**Comment by JakeHL** [comment]
This issue has returned with the re-introduction of rounded corners. You can change the border thickness to hide the gap, but it would be great to maybe have an option to inset the border a little so that we don't need super thick borders visible just to hide the gap. @koekeishiya
