### ISSUE TITLE
All the floating windows are above the non-floating windows

### ISSUE THREAD

**Issue by seonjunn** [koekeishiya/yabai#2170]
After updating yabai to the head after my mac update, all the floating windows are placed above the non-floating (tiled) windows even when I switch the focus to the tiled windows.

```
$ yabai --version
yabai-v7.0.2
$ sw_vers
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
```

I would provide any other info (configs) if required.

**Comment by shrugalic** [comment]
Isn't the point of floating windows that they float in front of everything else?

**Comment by jpsummer** [comment]
I'm having the exact same issue after updating MacOS to Sonoma, every floating window is sticky on top of any tiling window.

**Comment by shrugalic** [comment]
There was a breaking change in v 0.7.x, as documented in https://github.com/koekeishiya/yabai/issues/2128

Solution: use `sub-layer` instead of `layer`.

This solves my issue:
```
yabai -m rule --add app=".*" sub-layer=normal
```

**Comment by benkoppe** [comment]
`yabai -m rule --add app=".*" sub-layer=normal` changes nothing for me. I'm still having the same issue as described.

**Comment by shrugalic** [comment]
For debugging it might be helpful to check out what properties the windows in question have, in particular that they're not `sticky` by accident or suchlike:
```sh
yabai -m query --windows
```

**Comment by Pandoks** [comment]
Add this:
`yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"`

**Comment by koekeishiya** [comment]
Output of `yabai -m query --windows` ?

Also note changes to window rules in v7.0.0: 
> Add a new rule. Rules apply to windows that spawn after said rule has been added.

For `yabai -m rule --add app=".*" sub-layer=normal` to apply to windows that are already opened **before** yabai is launched or this rule is added, you need to also run `yabai -m rule --apply`

**Comment by shrugalic** [comment]
> Which config should I modify to make this as default?

_If_ I understand the documentation correctly (which [koekeishiya](https://github.com/koekeishiya) graciously left above), having the rule `yabai -m rule --add app=".*" sub-layer=normal` in your config should help prevent the issue for all windows you'll spawn in the future.

And running `yabai -m rule --apply` applied this rule to the windows you already had open. This should be a one time thing, if you have the previously mentioned rule in your config.

**Comment by koekeishiya** [comment]
The reasoning is that floating windows specifically should always be in front of tiled windows. This is very common with Linux window managers, and I also personally prefer that functionality. The motivation is that when floating windows are mixed alongside tiled windows in a managed space, the floating window usually has one of the following purposes:

a) temporary window that the user needs to interact with before it can be closed/moved away/minimized
b) window that should remain visible while work happens in some other window
c) dialog/pop-up window that requires attention

Very rarely in my opinion does it make sense to allow this window to get hidden behind the grid of managed windows.
If you want the window to go away, either move it to the side so it does not block the windows that you are working in, change its opacity, minimize it, move it to some other workspace.

Now I agree that this is opinionated, which is why it can be disabled fairly trivially in the user config.

**Comment by Maxachaka** [comment]
> Add this: `yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"`

For anyone that comes back to this wanting to figure out why their shit is broken, this is what you add at the top of your config file for yabai

yabai -m rule --add app=".*" sub-layer=normal
yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"

Then restart the service. If it doesn't work, just replace all layer with sub-layer.

**Comment by GladioFeng** [comment]
> > Add this: `yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"`
> 
> For anyone that comes back to this wanting to figure out why their shit is broken, this is what you add at the top of your config file for yabai
> 
> yabai -m rule --add app=".*" sub-layer=normal yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"
> 
> Then restart the service. If it doesn't work, just replace all layer with sub-layer=normal. Ex: yabai -m rule --add title="^Preview" manage=off sub-layer=normal

it works for me
