### ISSUE TITLE
Install version w/ Catalina Support?

### ISSUE THREAD

**Issue by booherbg** [koekeishiya/yabai#2173]
Hi, I've been suing yabai for years now and love it. I'm on an older macbook with Catalina and something happened to my yabai install where it wouldn't start. I did a re-install with brew, but now it refuses to install because I'm on Catalina (not Big Sur). Now I'm stuck without tiling windows and it's bugging me lol.

Is there a handy way to install a version with Catalina support, or should I just go back and try to build from source?

**Comment by koekeishiya** [comment]
The last version with Catalina support was v4.0.4 and can be downloaded here: https://github.com/koekeishiya/yabai/releases/tag/v4.0.4

The archive contains a prebuilt binary that you just download and put somewhere in your system.
(Ideally, somewhere in your $path). I have no idea which bugs are present and what problems that may entail, that have since gotten fixed.

I also don't know which parts of the current master/latest version that are broken in Catalina.
You can try to build from source and fix errors as they arise, but it is not something I want to spend my time on.

**Comment by booherbg** [comment]
Thank you! This is very helpful. This is probably the same version I had before so it should work just fine for me.
