### ISSUE TITLE
Weird gray thingy when the animation is on

### ISSUE THREAD

**Issue by aln-chg** [koekeishiya/yabai#2197]
When i add new window or rotate, or anything that triggers yabai's animation it turns gray when transitioning.

https://github.com/koekeishiya/yabai/assets/154101132/fb0d2039-5c2e-4bf1-b69d-be46983007f8

**Comment by aln-chg** [comment]
is there anyway to disable this?

**Comment by koekeishiya** [comment]
That is what your terminal actually looks like when the vibrancy effect is stripped. You can verify this by using the macOS Screenshot utility (open Spotlight -> Screenshot) and select "Capture selected window", then click on your terminal window. Look at the screenshot. 

You can either change how your terminal is customized or disable yabai window animations. This is why I stick to regular transparency instead of adding vibrancy effects to my terminal:

![anim](https://github.com/koekeishiya/yabai/assets/6175959/330f8f58-91dc-4ad4-a763-4225087386c6)

**Comment by aln-chg** [comment]
thanks a lot, also for anyone that uses alacritty and didnt get what he meant, just disable blur in alacritty.toml, ill try to find a way to add blur back and ill post it here if i can

**Comment by koekeishiya** [comment]
Apple's own window capture sample has the same limitation. So from what I can tell there is nothing to be done here to improve the situation, unfortunately.

<img width="1787" alt="capture" src="https://github.com/koekeishiya/yabai/assets/6175959/a7495c6d-2e4a-41c0-ac39-31e2217be0d2">

(This is actually a live video feed capture of the window, and not just a screenshot, but it still has the same limitation).
