### ISSUE TITLE
Hide window titlebar/trafficlights

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#241]
I see user configurations over at https://reddit.com/r/unixporn for yabai that have hidden window titlebars in things like vscode, terminal, finder and the like. Is this something yabai does? I cannot find mention of it in the documentation.

I think if we're using a tiled manager with the titles displayed at the top centre with it's own bar then things like traffic lights for window controls, and individual window titles are wasted vertical space.

**Comment by dominiklohmann** [comment]
That's straight up impossible and needs to be done on a per-application level.

**Comment by chaoxu** [comment]
It is known that winbuddy can do this. https://github.com/w0lfschild/winBuddy

However there is nothing that can take a window id and remove the title bar. Such script would be super nice.

**Comment by koekeishiya** [comment]
It is not possible to globally remove titlebars, because each and every application is responsible for drawing its own titlebar, and it does so through the Cocoa framework provided by Apple. This is also why every application on macOS is guaranteed to "look the same" in a unified way that you often do not get on Linux distros.

winbuddy can do this because it literally injects code into every single running application and modifies the appearance property through the Cocoa API.
