### ISSUE TITLE
zoom- vs windowed-fullscreen

### ISSUE THREAD

**Issue by vvatikiotis** [koekeishiya/yabai#2420]
Can someone describe the difference?

I have implemented a single window is centered and of reduced size (via	padding) script. 

Now I need to be able to toggle fullscreen for that single, centered window and I've sortof made it (in a clunky way probably), with gaps and zoom-fullscreen.

It works, sort of. for more than 1 window, it works,  however when having a single, centered and smaller size window it doesn't.

And reading the docs about it I feel that this information (zoom vs windowed fullscreen) is kinda lacking.

Thanks

**Comment by Bellavene** [comment]
`zoom-fullscreen` maximizes the window whatever
'windowed-fullscreen' maximizes the window, but within paddings and `external_bar` options.

**Comment by vvatikiotis** [comment]
The following "I have added a command that ignores all configured padding (both padding and external_bar padding).", from https://github.com/koekeishiya/yabai/issues/2221#issuecomment-2267548152 suggests the exact opposite., `windowed-fullscreen` ignores padding and external_bar....

Which one is it?

**Comment by Bellavene** [comment]
Ah yeah, sorry for misleading.

**Comment by aspauldingcode** [comment]
I was the one to make this feature request. 


Yabai Zoom 
follows your padding rules, as well as external bar padding. If you have gaps, zoom maximizes the window (covering other windows in the space) like normal. It's always been there. 


Windowed fullscreen is another option meant to replace the native-fullscreen. 

Instead of an annoying zoom and workspace switching animation that macos imposes, we just instead ignore padding limits to the window, and maximize the application window to the screen size. 

This way, it's basically an instant fullscreen toggle.

**Comment by vvatikiotis** [comment]
That clears things up, thanks!

**Comment by aspauldingcode** [comment]
> That clears things up, thanks!

Awesome!
Please don't forget to close this github issue if you've resolved it 😁
