### ISSUE TITLE
does yabai supports launching app at startup

### ISSUE THREAD

**Issue by kulubaev** [koekeishiya/yabai#2447]
i am trying to find extra info on this however after long search i decided to write it here

currently i have setup segregating apps per space once i launch them manually. it work correctly.

however i wonder if i can make yabai to launch them machine start. is this supported out of box, folks mentioned about tools such alfred, raycast,  do i need external tool for this scenario.

i am running monterey OS at the moment. Intel machine..

thanks

**Comment by kinglouie** [comment]
launching apps is outside the scope of yabai, but since yabairc is a simple shell script you can use it to do the following:

check if desired app is not already running if not then:
1. create [one shot window rule](https://github.com/koekeishiya/yabai/blob/c456566e94f2269ae27327039fe7cf4783d8c5a7/doc/yabai.asciidoc#rule) with yabai to put the app on the desired space
2. launch the app with standard terminal command `open -a APP_YOU_WANT`

**Comment by kulubaev** [comment]
> launching apps is outside the scope of yabai, but since yabairc is a simple shell script you can use it to do the following:
> 
> check if desired app is not already running if not then:
> 
> 1. create [one shot window rule](https://github.com/koekeishiya/yabai/blob/c456566e94f2269ae27327039fe7cf4783d8c5a7/doc/yabai.asciidoc#rule) with yabai to put the app on the desired space
> 2. launch the app with standard terminal command `open -a APP_YOU_WANT`

thanks
