### ISSUE TITLE
Directional focus in bsp space not working

### ISSUE THREAD

**Issue by acmcelwee** [koekeishiya/yabai#3]
yabai installed from git master branch, via homebrew
```
❯❯❯ yabai --version
yabai-v0.1.0
```

This is a laptop-screen only with multiple spaces. I've installed and loaded the scripting addon. 

In a bsp space with no floated windows, any attempts at a directional focus (`yabai -m window --focus north|east|south|west`) has no effect. At first, I suspected it was a problem with my skhd config, but executing the commands from a terminal in a bsp space doesn't change focus, either.

**Comment by alin23** [comment]
I'm experiencing the same on 10.4.5

**Comment by koekeishiya** [comment]
If you are not on macOS Mojave 10.14.4, you need to toggle this ifdef for any sort of focusing to work: https://github.com/koekeishiya/yabai/blob/master/src/window_manager.c#L508

Yabai uses the scripting-addition to focus a given window, because this lets us bypass the focus bug that chunkwm had where the wrong window gets focus when multiple displays are connected. I don't remember the issue number for chunkwm, but there are multiple issues about it.

**Comment by alin23** [comment]
Oh great! Thanks for pointing this out!

**Comment by koekeishiya** [comment]
Master branch is now updated with support for 10.14.5.

**Comment by acmcelwee** [comment]
✅- directional focus works great when working from the master branch

**Comment by barakyo** [comment]
I'm having this issue with 10.14.5. I've tried uninstalling and reinstalling several times. When trying to send the messages manually, the command returns 0, but focusing still isn't working. No errors in the log either. Other commands like zoom, rotate tree, etc work, but focusing windows does not.
