### ISSUE TITLE
Handling window moves from mission control

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#30]
I'm not sure if it's possible, but is it possible for yabai to detect window moves from one space to another that happens from mission control and resize windows itself?̊̈
I already managed to accommodate myself to switch from and back again one space to another after moving windows around in mission control (which makes yabai 'know' about the changed windows), but it'll be great if yabai can detect changes itself.

**Comment by koekeishiya** [comment]
Try the latest master and see if that's better.

**Comment by pcr910303** [comment]
@koekeishiya Wow, that's some fast feedback :-o
That's well, much much much better! 👍 
Can the window resizing be a little bit more responsive?̊̈
It feels a litttttle laggy...(Maybe that's just because yabai resizes windows after the animation finishes...?̊̈ I'm not sure...)
I mean, this is super great too; if you don't feel like it, the current state is still great for me :-)

**Comment by koekeishiya** [comment]
If you are talking about the delay between mission-control exiting and the window resize starting - this is because we have to poll to check if mission-control is still active or not. There is no event reported to us when mission-control exits. The polling is rate limited to reduce cpu usage.

The window resize itself is done through the *accessibility API* and is not something that we can speed up, unfortunately.

**Comment by koekeishiya** [comment]
> If you are talking about the delay between mission-control exiting and the window resize starting - this is because we have to poll to check if mission-control is still active or not. There is no event reported to us when mission-control exits. The polling is rate limited to reduce cpu usage.

I noticed that I had introduced some unnecessary delay. This has now been removed.
