### ISSUE TITLE
Coming back from full screen changes layout

### ISSUE THREAD

**Issue by marcjoha** [koekeishiya/yabai#324]
I'm usually dividing my screen in two sections. Lately I've been working on a presentation in google slides. I've noticed that if I click present, or just tell yabai to go full-screen, when I come back again the two sections change places.

This happens only if I full-screen or present the left section. If I full-screen/present the right, then the layout stays when I come back.

**Comment by dominiklohmann** [comment]
That's the desired behavior. When you enter fullscreen mode for a window, you move it to another (its own) space. When you then exit fullscreen mode for that window, it gets added back to its previous space, where yabai tiles it as if it was a window that was newly added to that space.

**Comment by marcjoha** [comment]
I find the experience surprising and quite inconvenient, but if this is by design, I suppose what I'm asking for is a feature request to remember the state of the layout before entering full screen.

**Comment by koekeishiya** [comment]
I don't want to implement this as a feature, because it does not make sense imo. Let's say you have two windows visible each taking half of the available screen space. Now you take the left-window and fullscreen it. Before exiting fullscreen you go back to the original space and open some other window that you need to use. This will cause the layout to change. You then swap back to the fullscreened application, do some more work and decide to exit fullscreen. The previously cached layout no longer applies because the amount of windws avaible has changed.

There are of course ways to define what should happen in the scenario I've described above, but it is not intuitive behaviour to me. I find it reasonable and easy to thinkg about when the behaviour is simply that a window that leaves the space is untiled, and a window  that enters the space will become tiled - unless they have previously been explicitly made floating of course.

Now I do actually have the use case you are talking about all the time in my daily usage. I have two or more windows tiled on the same space and I want to momentarily focus on one of the windows in fullscreen, which is why the command `yabai -m window --toggle zoom-fullscreen` is there. Have you not yet tried this command, or is there simply a reason why you need to use macOS native-fullscreen mode?

**Comment by marcjoha** [comment]
Thank you both for the extra details. I had indeed not tried the window-based fullscreen, only the native version. Not sure why actually, but this mostly solves for my use case. The remaining piece is getting your windows messed up after presenting something using Slides, but that's a small price to pay.

**Comment by braham-snyder** [comment]
A third type of full screen -- eg the edX and youtube video full screen buttons -- also causes a retile when it's undone. But that type of full screen can't always be emulated by just using yabai's zoom, because on many sites the video will stay its original size even if the browser window is expanded.

In that type of full screen, there is no additional space created, either. That makes me think it might make sense to restore the layout when it's undone. Granted, I wouldn't be surprised if that's a pain to implement.

**Comment by jdarren** [comment]
my common use case is enter/exit zen-mode in vscode (which puts the window in native full screen). it's a PITA to re-layout my desktop every-time i exit zen-mode. i really wish this feature request would get more consideration.

**Comment by Bellavene** [comment]
Agreed. This is fundamental, re-layout after full screen video makes no sense. Although I see that it will cost a lot of time to implement right.
