### ISSUE TITLE
Fullscreen layout

### ISSUE THREAD

**Issue by pikajude** [koekeishiya/yabai#337]
Hi, I think this feature existed in chunkwm but I can't find it in yabai. Basically, I have a massive external monitor that I use at work, which bsp works great for. When I work from home, I like to have most of the apps I use be (non-native) fullscreen, i.e. `yabai -m window --toggle zoom-fullscreen`, but for every app. This ensures I get max screen real estate and can alt tab through windows without having to switch spaces as I would if they were native fullscreen.

Is there a way to write a layout where every window is fullscreen zoomed? or is there a way to write a command that can do it for me?

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/83 for some kind of scriptable solution. This also kind of ties in with #203. I suppose enough people are interested in this that I'll consider looking into it for the next release. No ETA though.

**Comment by SebastienElet** [comment]
Thanks a lot @koekeishiya it's really useful for 11-13 inches screens

**Comment by koekeishiya** [comment]
Implemented on master using #203 as the backing mechanism.

```
yabai -m config layout stack
yabai -m config --space 3 layout stack
yabai -m space --layout stack
yabai -m window --focus stack.first
yabai -m window --focus stack.prev
yabai -m window --focus stack.next
yabai -m window --focus stack.last
```

**Comment by koekeishiya** [comment]
Updated docs and changelog to reflect the changes made for this issue. I have yet to be able to fully test this feature; did anyone encounter any bugs as a result of these changes, or does it seem fine?

**Comment by jmpohl** [comment]
@koekeishiya Has been working fine for me so far!

**Comment by danielhra** [comment]
Hey guys been loving yabai so far, moving from amethyst who would fail every here and then. I've been mainly using this layout but theres a few things i cant work around just yet, so i figured i would ask, btw if there is a better place to do so pls let me know!

So how would i be able to move a window within a stack to another space?

**Comment by jmpohl** [comment]
@danielhra You should be able to use the same command that you would in any other mode than stacking to do the same thing (in my`.skhdrc` file):

```
shift + ralt - 2 : yabai -m window --space 2 
```

to move the focused window to space 2 for example. Of course to do this you will need the scripting additions installed and the workspace will need to exist (personally I always have 10 workspaces created so I don't have to worry about bindings for creating and deleting workspaces)

P.S. *This may not be the best place for you to ask about this, or for me to answer, but it worked out since I had alerts on for this issue lol*
