### ISSUE TITLE
Disable live window resizing when using mouse-drag in a bsp-layout

### ISSUE THREAD

**Issue by brightpuddle** [koekeishiya/yabai#341]
I'm on a 2018 Macbook Pro, and live window resizing still stutters--even with eGPU. I greatly preferred the red guidance lines used for resizing in chunkwm as opposed to trying to constantly re-render content.

Opening an issue to suggest introducing this as an option.

Great application btw. I'm still on chunk due to this and and #337, but your work is by far the best tiling WM for MacOS.

**Comment by koekeishiya** [comment]
I've made it so that the layout adjustment happens when the mouse-button is released, so that it works the same way as it would if you simply resized the window using macOS' native handle.

The only benefit to using the mouse-drag commands provided by yabai is that it will allow you to move/resize the window by clicking anywhere in the window. Otherwise it should work exactly the same as if simply dragging/resizing a window. This applies to both tiled and floating windows.
