### ISSUE TITLE
example skhdrc config has many shortcut keys crashing with default mac shortcuts

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/yabai#362]
it's not a very good first user experience. i think we should provide a better default config. or maybe comment out the conflicted ones?

example: 

cmd shift 3 for screenshot
option shift left - right for selecting text

**Comment by koekeishiya** [comment]
I personally think hotkeys are to subjective to bother with this. It is very hard to create something that will fit for multiple macOS users because it heavily depends on what they do, what applications they use, and which actions are the most productive to have easy access to, while also having them be somewhat intuitive.

The skhdrc file is so trivial to edit (and is updated live on file save) that I do not consider this a problem. I think that anyone who wants to be productive using this tool will have to invest some time to make their own shortcuts, and use the sample config as a reference to learn the limited syntax that skhd uses.

**Comment by mstr3336** [comment]
> I think that anyone who wants to be productive using this tool will have to invest some time to make their own shortcuts

If people supply well recieved alternative bindings, would you be open to including them as alternatives in the examples dir?

Personally I quite like the default config of linux's [regolith wm](https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config).  

There are some differences in implementation for regolith, such as context sensitive behaviour for the same keys (There's a toggle-able resize mode, and the same command that moves a window within one display will also move across displays). 

I quite like the feel of both of these behaviours, I do find it a lot easier to remember than yabai's default bindings.

**Comment by tuananh** [comment]
how about we provide several keybinding to common tiling app?

- yabai i3 key binding version
- yabai regolith wm key binding version

like how vscode has different keybinding provided and maintained by community

**Comment by koekeishiya** [comment]
I think that would probably be better suited for the wiki, than the repository itself. #5 @dominiklohmann

**Comment by dominiklohmann** [comment]
There are always be trade-offs to be made here between keyboard layout, system-wide shortcuts, application-wide shortcuts, and non-modal shortcut ergonomy.

I have a recommendation of minimally-invasive defaults (i.e., not overriding any system default keyboard shortcuts) written down somewhere, and I can share that this weekend. I've written down a note to get back to this.

**Comment by mstr3336** [comment]
Hi @dominiklohmann , did you wind up getting around to sharing your shortcut config?

Also - By "non-modal", are you referring to the distinction between having a particular shortcut permanently available, with a dedicated binding, vs having the same set of keys perform different functions, based on some context (Eg "resize mode" vs "move mode" toggle)?

**Comment by mstr3336** [comment]
> The skhdrc file is so trivial to edit (and is updated live on file save) that I do not consider this a problem. I think that anyone who wants to be productive using this tool will have to invest some time to make their own shortcuts

Though I agree with this to an extent, I think it's worth acknowleding that users tend to prefer tools that "just work", and like having an "easy" option to configure their profiles broadly, and then the option of fine-tuning that if they really need to. 

For me personally, I realised that the default hotkey combinations collided with many of my favourite build shortcuts in my IDE, and rather than take the time to understand what shortcuts do what, I just disabled the skhd service. 

After examining the skhd bindings, I just decided to leave it off until I had the time to work it out myself. 

> I think that would probably be better suited for the wiki, than the repository itself. #5 @dominiklohmann

I think this instinct is a good one, as I also wouldn't want to be fending off (Or merging) PR's for every other person's "best" keybinding to go into the examples dir, but I do think it's nice to give people a place to share/collaborate on systems they find convenient. 

Personally, if noone else has, I'll be working on a skhdrc that mimics [regolith wm for linux](https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config), simply because I don't intend to memorize different bindings for every system I use, and I find their bindings non-invasive and easy to remember.  

I'll be putting it somewhere on the wiki

**Comment by dominiklohmann** [comment]
> did you wind up getting around to sharing your shortcut config?

You'll have to wait until my backlog has shrunk a bit. I want to do this properly, and writing thoughts on every category of shortcuts takes time like an hour or two, which I just haven't had this past weekend.

> Also - By "non-modal", are you referring to the distinction [...]

skhd has support for modal hotkeys, which is what this is referring to. Basically. any hotkey that requires aa series of key-presses, much. like what people know from software like Vim or tmux.

**Comment by koekeishiya** [comment]
> For me personally, I realised that the default hotkey combinations collided with many of my favourite build shortcuts in my IDE, and rather than take the time to understand what shortcuts do what, I just disabled the skhd service

I think our main differences come from the fact that this is not intended to be a set of default shortcuts. It's a sample file for informational purposes, and that's it. I suppose that could be clarified, but there is a reason I use the word "sample", and not "default".

> Though I agree with this to an extent, I think it's worth acknowleding that users tend to prefer tools that "just work", and like having an "easy" option to configure their profiles broadly, and then the option of fine-tuning that if they really need to.

I don't disagree with this, but there is only so much effort I am willing to put into this project.
I'm fine with people creating and submitting information to the wiki as long as it fits well into the current style, and is regularly maintained (if necessary). While the wiki is open for everyone to edit, I've let @dominiklohmann sort of administrate the wiki so far.

**Comment by geeohgeegeeoh** [comment]
I think the key observation here has been lost: *first user experience* is not good. The collision is understood, it is unavoidable, but the choices that have been made functionally collide with one app binding (screenshot) which breaks the _principle of least astonishment_ rule.

First user experience colours subsequent experience. If the fact it collides was more overt, People would be forewarned.

I tend to thinking the ScreenShot app is a bad choice to collide with in many ways. I've coded around it in my .skhdrc

**Comment by koekeishiya** [comment]
> First user experience colours subsequent experience. If the fact it collides was more overt, People would be forewarned.

> I tend to thinking the ScreenShot app is a bad choice to collide with in many ways. I've coded around it in my .skhdrc

I mean, this is my whole point though. There is no set of default shortcuts provided with yabai. The fact that people copy and use a *sample* file for their daily driver is really none of my concern.

As per my previous comment; I'm fine with other people in the community providing various config-files that can act as a set of default shortcuts for beginners.

**Comment by geeohgeegeeoh** [comment]
Who wrote the sample file? I'd say whoever wrote the sample file has at
least some concern.

G

**Comment by tuananh** [comment]
I think we can conclude that @koekeishiya is open to PR to add more sane sample config. or more variety configs. at the very least, keep the sample file small to demonstrate what yabai can do and more full config to mimic other tiling windows managers in wiki maybe?

**Comment by koekeishiya** [comment]
> I think we can conclude that @koekeishiya is open to PR to provide a sane sample config. or more variety configs. at the very least, keep the sample file small to demonstrate what yabai can do and more full config to mimic other tiling windows managers in wiki maybe?

I'd prefer to have it in the wiki instead of having to deal with PRs. The wiki is already open for everyone to edit. I think @dominiklohmann already has some ideas for how he wants this to be done, so I'd suggest waiting until he has time to do so. If you want to contribute a gist or just a comment in this issue containing the binds you want to provide, that is probably fine, and it can be moved into the wiki once a section has been set up.

Also, for clarification purposes because I feel like a lot of people miss the point..
The skhd config in the examples directory is referred to as a sample config for the very reasons that are mentioned here. It has a lof of conflicts, and there has not been put any thought into making it. It is simply a file to show the very basic syntax that skhd uses, and how it can be utilized to interface with yabai; listing the most commonly used operations. 

I could write half a page in the readme explaining this, but then (from experience) people won't read it anyway, so I've opted to use more concise language and wording, e.g: sample file.

If people can't seem to understand that, then I am more inclined to simply not do samples when new features are added, and simply link to the documentation instead.

**Comment by geeohgeegeeoh** [comment]
I think my confusion is the idiomatic native English speakers meaning of
'not my concern' -its a statement which can mean at least three things:

1) I have other more pressing concerns than this (but it is concerning)
2) I I do not regard this as a concern
3) I know it's broken and I don't care. I could not care less.

You obviously do care it's confusing people but you feel a different
solution is better. I tend to think an example .skhdrc is useful if only to
show syntax, if you don't intend having a 'standard or default one.

Your example is reasonably complete. That is why people use it!

Cheers

G
