### ISSUE TITLE
Date and time format in status bar

### ISSUE THREAD

**Issue by johnnypea** [koekeishiya/yabai#39]
Would you consider adding status bar date and time format option in the configuration file?

Something like `l jS \of F Y h:i:s A` prints: "Monday 8th of August 2005 03:12:46 PM"

Thank you very much.

**Comment by dominiklohmann** [comment]
If you wanna get this done quick and dirty, replace this line

https://github.com/koekeishiya/yabai/blob/7b9f51e6bb6af6140c54fdb82a8bea7b42f31f82/src/bar.c#L194

with this code:

```c
strftime(time, sizeof(time), "<format specifier>", timeinfo);
```

More info on the special `strftime` format specifiers: https://en.cppreference.com/w/c/chrono/strftime

If I recall correctly, `strftime` should be used here regardless of the actual format because it's guaranteed to properly handle time zones. Although I don't know how much that really matters if all that's printed is hour and minute.

**Comment by koekeishiya** [comment]
I don't think I will be making the bar more configurable through settings. It was just meant to be something very simple to provide an alternative to the Übersicht bar I personally used previously. A lot of people sent me emails asking about it, so I figured I'd provide something similar a long with the window manager.

That said, the entire code for creating, configuring and drawing the bar is isolated in `bar.c`, so it should be very trivial to maintain your own fork where you can do whatever you want to with regards to the status bar, without risking any merge conflicts when you want to pull from upstream.

If you have questions regarding the statusbar code, feel free to create an issue regarding that, and I'll try to help out.
