### ISSUE TITLE
Move/resize named window

### ISSUE THREAD

**Issue by henrik242** [koekeishiya/yabai#392]
The `window` command only works with the focused window as far as I can see. Is it possible to resize and move a window by `title`? 

Something like `yabai -m window title="^MyTitle.*$" --resize=abs:1000:1000`

**Comment by dominiklohmann** [comment]
```sh
yabai -m query --windows |
  jq '.[] | select(.title | test("^MyTitle.*$")).id' |
  xargs -I{} yabai -m window {} --resize abs:1000:1000

**Comment by henrik242** [comment]
OK, I figured it out:
```
WINDOW_SEL=$(yabai -m query --windows |jq '.[] | select (.title | contains("travel-app2")) | .id')
yabai -m window $WINDOW_SEL --resize abs:1000:1000
```

**Comment by dominiklohmann** [comment]
Note that your version fails if multiple windows match the query.

**Comment by henrik242** [comment]
@dominiklohmann By the way, am I right to assume that I can't use `--resize` and `--move` in the same `window` message?  Right now I have issue two separate commands.

**Comment by koekeishiya** [comment]
> By the way, am I right to assume that I can't use --resize and --move in the same window message? Right now I have issue two separate commands.

Yeah, that is correct. There is no technical reason for this, it's just how I happened to write the message parsing logic. Might revisit this idea in the future, but I don't think it's a big deal.
The overhead of having to issue two separate commands is not that important considering the fact that the macOS AX API will always be the bottleneck here.

**Comment by dominiklohmann** [comment]
Note that you don't need to issue the query twice:

```sh
yabai -m query --windows |
  jq '.[] | select(.title | test("zsh")).id' |
  xargs -L1 sh -c '
    yabai -m window $0 --toggle float &&
    yabai -m window $0 --resize abs:500:500
  '
```

**Comment by henrik242** [comment]
@dominiklohmann I guess whether that is only one command is a matter of opinion ;)

**Comment by tophee** [comment]
I've spent quite some time trying to figure this one out. I somehow thought it could be done with a rule, but then I couldn't figure out how to trigger the rule... Anyway, I agree that it would be nice to have a simpler command for selecting named windows, i.e. something similar to how rules work.

For example, instead of 
~~~
yabai -m query --windows |
  jq '.[] | select(.title | test("^MyTitle.*$")).id' |
  xargs -I{} yabai -m window {} --resize abs:1000:1000
~~~

something like 
~~~
yabai -m window title="^MyTitle.*$" --resize abs:1000:1000
~~~

**Comment by koekeishiya** [comment]
> something like
> `yabai -m window title="^MyTitle.*$" --resize abs:1000:1000`

The "problem" with this syntax is that there are a lot of properties (and combinations of properties) that may be interesting to filter by, and mixing it straight into the command structure like this makes it both complicated to read, and potentially to parse. 

If filters are allowed in-place instead of a `WINDOW_SEL`, then it would have to be allowed every place that currently allows a `WINDOW_SEL`, to maintain consistency (and simplicity) in the CLI.

In theory that means that the parser would have to allow for, and understand, something like the following (even though it might not make sense from a practical pov):
`yabai -m window title="^MyTitle.*$" app="^MyApp.*$" space=1 --swap title="^OtherTitle.*$" app="^OtherApp.*$" space=2`

I think the above command would be ambiguous from a parser pov, unless extra context is given. Not saying that it would be impossible, but I think it makes things a lot more complex both from a user pov and certainly from an implentation-pov.

The thing that is great about the current design is that you know how to issue commands that affect certain entities (windows, spaces, displays) using very simple syntax, and when more complex needs arises, there is a standard way to retrieve the information that you need to script that behaviour.

**Comment by tophee** [comment]
Thanks a lot for explaining. It makes more sense now. I am looking at this from the perspective of someone who is not a software engineer and who has just started using yabai. I can't tell, at this point, whether I would prioritize consistency over ease of use, but if that's what you want to do, that's obviously fine. 

From my perspective, another way of making yabai easier to use would be to simply highlight this design decision in the documentation. Of course, you can say that all the information is already there, but it still took me quite a while to figure out the importance of the query command. As someone who is getting started with yabai, it felt like that would be for more sophisticated setups so it didn't occur to me for a while that I really need to jump through that hoop to select a window by its title. So I think it might help users to have that clarified more explictly early on in the docs, even if it may seem redundant to more experienced users.

As I think more about it, I think I might be able to turn around your consistency argument to argue for a simplification of selecting named windows: what about allowing labels for windows? Why should `WINDOW_SEL` not accept `LABEL`? If that were added, it would at least allow us to query windows once, label them, and then refer to them via their label...

**Comment by koekeishiya** [comment]
> Thanks a lot for explaining. It makes more sense now. I am looking at this from the perspective of someone who is not a software engineer and who has just started using yabai. I can't tell, at this point, whether I would prioritize consistency over ease of use, but if that's what you want to do, that's obviously fine.

I think it is important to have an interface that is easy-to-understand in terms how to do things. I agree that adding a single option that would let you select a window by its title as proposed is easier for the specific thing you are trying to do here, but from an overall design pov it makes things more unclear; as in there are now multiple ways of doing the same thing, but only when some properties are applied -- it makes the interface convoluted over time.

> From my perspective, another way of making yabai easier to use would be to simply highlight this design decision in the documentation. Of course, you can say that all the information is already there, but it still took me quite a while to figure out the importance of the query command. As someone who is getting started with yabai, it felt like that would be for more sophisticated setups so it didn't occur to me for a while that I really need to jump through that hoop to select a window by its title. So I think it might help users to have that clarified more explictly early on in the docs, even if it may seem redundant to more experienced users.

I agree that it could certainly be outlined with more info/samples in the wiki, but it is not really high on my priority list. I don't spend too much time on this project these days, and would rather do programming when I do make time for it. The wiki used to be open for the community to edit, but people made changes that made things incorrect, and I would have to spend a lot of time to continually review said changes and revert them, which is why I locked it down.

> As I think more about it, I think I might be able to turn around your consistency argument to argue for a simplification of selecting named windows: what about allowing labels for windows? Why should WINDOW_SEL not accept LABEL? If that were added, it would at least allow us to query windows once, label them, and then refer to them via their label...

No reason really, I just haven't implemented it yet. For consistency reasons, as you mention, it should be possible to allow labelling both windows and displays as well (all "entities"). The labelling spaces thing was added as a quick experimental thing, and the label-system is not completely fleshed out yet. I believe there are some open issues regarding it and allowing for default labels when none are specified and so on. No ETA for when that will be a priority though.
