### ISSUE TITLE
Window flickering

### ISSUE THREAD

**Issue by choco** [koekeishiya/yabai#394]
Sometimes when I'm not doing anything I notice that the window flicker, like it was resized and then brought back to the same size.
This happens multiple times a day, I have no idea what could be causing this, I also have no idea how to explain this better. I was just wondering if anyone else was experiencing something similar.

**Comment by koekeishiya** [comment]
See my comment in #403 , not sure if related. When mission-control is exited we try and look for changes and reapply regions if necessary - #30 

Not sure if this is a bug or a sideeffect of something that was implemented on purpose to solve some other situation.

**Comment by choco** [comment]
In my case it is not a crash.
Also for me it seems more of a resize/move on the side rather than a resize from the top. Finally it doesn't seem to be related to activating/exiting mission control since it also happens when I w as in the same space by quite some time.

**Comment by choco** [comment]
In the weekend I'll try to debug this and maybe provide some video proof ahah

**Comment by koekeishiya** [comment]
Is this still a thing in the latest version?

**Comment by choco** [comment]
I updated to the last version yesterday (it was hard saying goodbye to the borders ahah). I'll let you know at the end of the week if it's still an issue (at least on my end)

**Comment by choco** [comment]
Unfortunately it still happens :(

**Comment by koekeishiya** [comment]
So yabai does not actually respond to move / resize events and try to force the window back to an assigned region etc. like chunkwm did, and so I don't see how this could be caused by yabai as you already confirmed that it is not related to mission-control, which would be the only time we do something that is not a direct response to an event that was generated by macOS.

Could your issue be related to this comment: https://github.com/koekeishiya/yabai/issues/403#issuecomment-635997583 ?

**Comment by emilecombes** [comment]
I have the same issue. It seems to happen whenever the mouse hovers over a button which activates a pop-up window.

**Comment by jjant** [comment]
This happens here as well. I've noticed it happening also when typing in text boxes (even if those text boxes have fixed sizes), but I can't reproduce it deterministically.

**Comment by tav1nald3rs0n** [comment]
For me my window flickers like hell when I hover a link, only on Microsoft Edge

**Comment by jjant** [comment]
Full screen videos in firefox flicker a lot. It makes fullscreen literally unusable.

**Comment by greyshi** [comment]
I found that this was caused by a rule I put in place to prevent dialogs/popups from appearing behind windows making them un-viewable. After removing this line, the flickering goes away. It's without a doubt caused by Yabai.

    yabai -m rule --add app="^(Google Chrome|Code|IntelliJ IDEA)$"    manage=on layer=below

**Comment by koekeishiya** [comment]
The `manage=on` property is specifically there to allow applications that are not detected by yabai by default (due to bad accessibility [role](https://developer.apple.com/documentation/applicationservices/carbon_accessibility/roles?language=objc) and [subrole](https://developer.apple.com/documentation/applicationservices/carbon_accessibility/subroles?language=objc) assignments from the creator, usually happens to cross platform software that is focused on Linux as the main platform), and is **not** the inverse of `manage=off` which makes yabai treat a window as floating.  The way you are using it in the above  rules **WILL** cause bad things to happen.

**Comment by greyshi** [comment]
It was the only workaround I could find to prevent dialogs like the floating Calendar app event info pop up from appearing behind managed windows. Found the solution on the issue [here](https://github.com/koekeishiya/yabai/issues/1156) based on [this](https://github.com/koekeishiya/yabai/issues/1156#issuecomment-1262191338) comment. For now, that pop up problem has gone away for me even when commenting this line out. Not sure if it's intermittent caused by some other state I'm not currently in.

**Comment by koekeishiya** [comment]
At the very least change it to the following: `yabai -m rule --add app="^(Google Chrome|Code|IntelliJ IDEA)$" role="AXWindow" subrole="AXStandardWindow" manage=on layer=below`

The correct way to do this would be to have a rule that says `mange=off` for all windows, and then hook a script up to the `window_created` signal, calling `--toggle float` if the window matches your filter.

**Comment by george43g** [comment]
> At the very least change it to the following: `yabai -m rule --add app="^(Google Chrome|Code|IntelliJ IDEA)$" role="AXWindow" subrole="AXStandardWindow" manage=on layer=below`
> 
> The correct way to do this would be to have a rule that says `mange=off` for all windows, and then hook a script up to the `window_created` signal, calling `--toggle float` if the window matches your filter.

Can you please elaborate on this? I'm getting the same issue and there doesn't seem to be an easy fix or workaround.
