### ISSUE TITLE
Remove space transition animation when moving spaces outside of yabai

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#398]
If I have an app in space 2, but space 1 is focused, and i select the app in space2 via dock, the screen transition is slow.

Is there a way to make the screen transition to the space with the app open fast like if I switch spaces with my hotkeys? Thanks.

**Comment by dominiklohmann** [comment]
I took the freedom to title your issue and move the actual issue from the title into the body.

The answer to your question is no.

**Comment by srsholmes** [comment]
This might not be what you are looking for, but there is a system setting where you can reduce the animation between changing spaces as described here https://apple.stackexchange.com/a/255220 . 

The animation still takes place, but it is a fade rather than a jarring sliding animation. 

Hope that helps 👍

**Comment by chriseomi** [comment]
> The answer to your question is no.

[Totalspaces2](https://totalspaces.binaryage.com/) allows instant spaces switching. It uses injection so needs SIP disabled. Personally find it to be a complete godsend.

**Comment by koekeishiya** [comment]
Yabai does allow instant space switching, as long as the space switch is triggered using `yabai -m space --focus whatever` and not through cmd+tab or some other OS controlled mechanic.

Does Totalspaces remove the animation when entering/exiting native fullscreen spaces, and when using cmd+tab to activate a window on an inactive space?

I know it used to be able to do this on High Sierra, but ever since Mojave launched that behaviour did not come back, afaik.

**Comment by strafe** [comment]
@koekeishiya I have just tested TotalSpaces2 on 11.2.2 and it is able to completely remove the animation (instant, just like yabai) when clicking on icons in the Dock that force a workspace change. It would be great if yabai did this too since it's quite jarring to have no animations when using hotkeys and sliding animations with the dock.

TotalSpaces2 was not able to remove the <kbd>Ctrl+Left/Right</kbd> sliding animation, either by design or maybe it just isn't possible but I assume those can be rebound with skhd anyway.

**Comment by koekeishiya** [comment]
I am testing some changes to the scripting-addition on the latest master that removes:

1. The space switch animation when clicking icons in the Dock that force a space change.
2. The space switch animation when selecting an application with cmd+tab that force a space change.
3. The space switch animation when focusing a space using the default macOS mission-control keyboard shortcuts (numeric ones, not left/right).

This is still a work in progress, meaning that not all OS versions are supported yet.

I have currently tested and verified that this is working on macOS Big Sur 11.6.1 (Intel), but believe it should also work on Monterey 12.3.1 (Intel). 

I have also verified and tested that it works on macOS Monterey 12.3.1 (Apple Silicon).

See #1235 for future updates.

**Comment by strafe** [comment]
That is awesome, @koekeishiya did you conclude removing the left/right shortcut animation is not currently possible?

**Comment by achendev** [comment]
On one of my MBA where SIP cannot be disabled, i use tricky approach to achieve habitual experience of instant switching

This keymaps contains list of apps in order i would like them to use, as if they would be placed at different spaces, so i can switch between them instantly while all of them on a SINGLE workspace

In my case: option + 1 switches to left side, option + 2 - to right side
It takes about 60ms to compute which the current app and what the id of prev/next one while switching, i couldn't optimize it faster, but if feels fine, at least in 15 times faster than native annoying animation

If it sounds good for you, you need to replace array of apps with yours and remap to keys you'd like
```
cat ~/.skhdrc 
alt - 1 : \
    WINDOW_ID=$(yabai -m query --windows | jq -r --argjson apps '["Sublime Text","Tabby","Google Chrome","Telegram"]' '. as $all_windows | ([.[] | select(."has-focus")] | .[0].app // "null") as $focused_app | $apps as $app_list | ($app_list | index($focused_app)) as $idx | if $idx != null and $idx > 0 then $app_list[$idx - 1] as $target_app | ([$all_windows[] | select(.app == $target_app)] | .[0].id // empty) else empty end'); yabai -m window --focus "$WINDOW_ID"

alt - 2 : \
    WINDOW_ID=$(yabai -m query --windows | jq -r --argjson apps '["Sublime Text","Tabby","Google Chrome","Telegram"]' '. as $all_windows | ([.[] | select(."has-focus")] | .[0].app // "null") as $focused_app | $apps as $app_list | ($app_list | length) as $len | ($app_list | index($focused_app)) as $idx | if $idx != null and $idx < ($len - 1) then $app_list[$idx + 1] as $target_app | ([$all_windows[] | select(.app == $target_app)] | .[0].id // empty) else empty end'); yabai -m window --focus "$WINDOW_ID"
```

It not quite about disable animation, but it works for me

**Comment by flawnn** [comment]
https://github.com/flawnn/instantspaces

I isolated yabai's Dock patch here so you can use it without yabai. Feel free to contribute!
