### ISSUE TITLE
Status bar height

### ISSUE THREAD

**Issue by dsanson** [koekeishiya/yabai#420]
Because I am on a tiny 12" Macbook, I prefer to have a narrower status bar and use a smaller font than default. But the height of the status bar is hard-coded. So for awhile now, I have had a local branch with a tweaked hard-coded status bar height. That's fine, though sometimes I have to rework the tweak when I merge in your upstream changes.

I respect your desire to keep the status bar simple and keep customization to a minimum. I can keep doing what I have been doing. But, given that font size is configurable, I think it would make sense for status bar height to be configurable as well. (If i was more confident in my ability to write idiomatic C, I'd make the change myself and submit it as a pull request.)

**Comment by koekeishiya** [comment]
> I respect your desire to keep the status bar simple and keep customization to a minimum.

It's not really that I don't want to allow customization of the status bar, but it's more the fact that I just don't really want to be in charge of that type of project. The current status bar implementation is really just something I added because I wanted something simple for my own usage, and people kept emailing me asking what bar I used.

For a more detailed explanation of what I would like to have happen in the future, see my comment https://github.com/koekeishiya/yabai/pull/316#issuecomment-579279827
