### ISSUE TITLE
Turning on window border can break focus following

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#427]
It looks like the extra time it takes to render the border can interfere with focus updates. More noticeable with larger `border_width`.

Reproduction:

- Turn on `window_border`
- Using the mouse, move from one window to another, then quickly switch back.
- Note that occasionally focus will remain on the second window, rather than returning.
- (Moving the mouse another time will correctly update focus.)

![2020-02-28 13 50 17](https://user-images.githubusercontent.com/191335/75511551-e5970b00-5a31-11ea-9650-f7954c2b6b7b.gif)

nb: Aside from the above issue, I'd really like to use the window border feature to better know which app I have focused during keyboard navigation, but the draw overhead it adds makes switching windows feel a bit sluggish. Not sure if this can be improved at all, but it would be a huge usability boost!

**Comment by koekeishiya** [comment]
So I don't think this has anything to do particularly with window borders being enabled. There is a check in place to only respond to a mouse moved event if it has been at least 25ms since the last movement. This is to reduce the amount of cpu usage during heavy mouse activity. I don't at this time have a better solution than rate limiting.

**Comment by koekeishiya** [comment]
window borders are no longer a thing, so I'm closing this.
