### ISSUE TITLE
why some app windows minimize itself after switching to other desktops

### ISSUE THREAD

**Issue by chenjunweii** [koekeishiya/yabai#438]
Hi Guys, why some app windows minimize itself after switching to other desktops

for example, I have two desktops opened

desktop 1 => two terminals

desktop 2 => chrome

sometimes those 2 terminals had already minimized before I switch from desktop 2 to desktop 1,
so there was nothing on the desktop 1, I have to click the terminals icon on the dock again 

any ideas?

**Comment by dominiklohmann** [comment]
This really lacks information. Windows don't usually minimize themselves. Please post steps that reliably reproduce the issue, and if possible add a screen recording of the issue.

**Comment by koekeishiya** [comment]
There is no functionality in yabai that can minimize a window - it is not implemented. 
This is happening because of something else on your system. Note that macOS have built-in actions that e.g hide inactive windows etc upon performing certain keyboard shortcuts or modifier+mouse buttons on the active window, that work across spaces.

**Comment by chenjunweii** [comment]
@koekeishiya  I think i found the problem, thanks for the advice!
