### ISSUE TITLE
I have some troubles in switching space

### ISSUE THREAD

**Issue by XDID** [koekeishiya/yabai#465]
yabai -m space --focus 1
this command doesn't work for me after I update my system to macOS Catalina 10.15.4

**Comment by dominiklohmann** [comment]
Duplicate of #462 and a whole bunch of other comments.

When you start yabai, it likely tells you via a system notification that the installed version of the scripting addition is outdated. You need to manually reinstall it after updating to a recent version of yabai itself.

This all happens because the scripting addition changes Dock.app, and system updates sometimes change Dock.app, too, requiring the scripting addition to be changed.
