### ISSUE TITLE
mouse_action1 seems to have no effect

### ISSUE THREAD

**Issue by devshane** [koekeishiya/yabai#468]
Using `yabai-v2.4.1` with the mouse config:

```
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
```

Holding `fn` and left-click-dragging a window doesn't move or swap the window but `fn` and right-clicking does resize it. There's nothing in the yabai logs that I can see and I can arrange windows fine with keybinds.

I'm a recent convert to yabai; this config works with chunkwm:

```
chunkc set mouse_move_window \"fn 1\"
chunkc set mouse_resize_window \"fn 2\"
```

Thanks for any help.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

> The following features of yabai require System Integrity Protection to be (partially) disabled:
>> move window by clicking anywhere in its frame

**Comment by devshane** [comment]
Bah, sorry. Thanks.

**Comment by koekeishiya** [comment]
If you don't want to disable SIP and install the scripting-addition, you can get this specific functionality to work by changing this line: https://github.com/koekeishiya/yabai/blob/master/src/event.c#L1187 to `window_manager_move_window(g_mouse_state.window, fx, fy);`

It won't be as smooth/performant, but it will work.

**Comment by koekeishiya** [comment]
Also note that you can just drag a window by its titlebar and drop it in a specific region of another window, to perform a warp/swap respectively, see #142 for more information. The same will apply for manually resizing a window - the layout will be adjusted automatically. The mouse-commands are simply to allow the action to trigger from anywhere in a window instead of only its titlebar.
