### ISSUE TITLE
Improve focus_follows_mouse with mouse_follows_focus off

### ISSUE THREAD

**Issue by JonathanHuot** [koekeishiya/yabai#483]
**Expected behavior:**
When opening floating windows, or changing focus with keyboard, the "focus_follows_mouse" should be suspended, unless we move the mouse to another window than the current one. (could it help https://github.com/koekeishiya/yabai/issues/407 ?) .
I feel this behavior more natural, for background info I come with i3 experience.

Note that it applies to both `autofocus` or `autoraise` when `mouse_follows_focus` is off.

**Example of configuration to reproduce:** 
```
yabai -m config layout bsp
yabai -m config window_topmost on
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus off
```
If you want to test with modal:
```
yabai -m rule --add app="^System Preferences$" manage=off
```
If you want to test with keyboard .skhdrc:
```
alt - left: yabai -m window --focus west
alt - down: yabai -m window --focus south
alt - up: yabai -m window --focus north
alt - right: yabai -m window --focus east
```

**Typical use-case:**
1) two windows are split vertically
2) mouse is over the left window
3) change focus to the right window with the keyboard (alt-tab or alt-right)

Current behavior:
4a) mouse moves toward the right window, yabai focuses the left window
5a) mouse reaches the right window, yabai focuses the right window
6a) mouse moves to the left window, yabai focuses the left window

Expected behavior:
4a) mouse moves toward the right window
5a) mouse reaches the right window
6a) mouve moves to the left window, yabai focuses the left window

**Comment by koekeishiya** [comment]
At first I thought this sounded like a great solution, but after thinking about it for a while I see a few notable issues with the approach so far. These could potentially be solved, or at least it could be documented behaviour to clarify certain cases.

So let's say we extrapolate your suggestion for more complex layouts, e.g three windows are all split vertically. Mouse is over the left-most window. Change the focus to the right-most window using whatever keyboard-centric method available to you. Now move the mouse toward the right-most window:

Current behaviour:
Yabai focuses the left-most window as that's the window below the cursor.
It reaches the center window and changes focus again.
It reaches the right-most window and focuses the right window.

Suggested behaviour:
Yabai does not focus the left-most window
It reaches the center.. what is the expected behaviour?
It reaches the right-most window.. behaviour depends on the previous step.

This also applies to the following type layout:
```
 A |
---| C
 B |
```

**Comment by JonathanHuot** [comment]
I think the key part of the solution is: ` the "focus_follows_mouse" should be suspended, unless we move the mouse to another window than the current one`

I'm not sure how Yabai is implemented and what are the possibilities of the OS API. However, I'd suggest to everytime a focus change is detected from window A to window B, Yabai captures the old focused window A id.
Then, everytime Yabai detect mouse change, if it goes over any other window different than A, it changes the focus.

So, in practice, it will be:

Three windows split vertically
Current behaviour:
Yabai focuses the left-most window as that's the window below the cursor.
It reaches the center window and changes focus again.
It reaches the right-most window and focuses the right window.

Suggested behaviour:
Yabai does not focus the left-most window
It reaches the center, Yabai focus the center
It reaches the right-most window, Yabai focus the right-most window.

Does it sound good?

**Comment by dominiklohmann** [comment]
I'm still not convinced this is a solution to an actual problem and would like to go back from solution space to problem space. Can you describe _why_ the current behavior is problematic?

**Comment by JonathanHuot** [comment]
The proposal started after one specific problematic.

Let's say you reuse the yabai configuration mentionned in the initial ticket, plus this one:
` yabai -m config focus_follows_mouse autoraise` 
You also need a keyboard shortcut to launch MacOS System Preferences.

- Start with two windows split vertically.
- Put your mouse on the left window.
- Launch System Preferences with keyboard shortcut, normally it opens in the center of the screen, right between the two windows managed by Yabai.
-> MacOS will give automatically focus to System Preferences
- You move the mouse toward the System Preferences in order to clic on buttons
-> Yabai detect mouse move and assign focus & raise to the left window. The System Preferences window is now hidden between your left window.
- You move the mouse toward the right side of the System Preferences (the one visible)
-> unfortunately, your mouse trajectory was hover the right window for a single pixel (like coming from the middle of the screen), so Yabai detect mouse hover right window and raise it.

Then you're screwed because you have open a System Preferences, but it has been automatically hidden behind your windows by Yabai. The probability seems maybe a bit unrealistic, but it occurs to me frequently.

**Comment by dominiklohmann** [comment]
You can always just either use mouse follows focus or hold down <kbd>fn</kbd> to temporarily disable focus follows mouse.

I think the proposed change introduces more problems than it fixes.

**Comment by JonathanHuot** [comment]
I think on UX point of view, using `fn` is really a key which should never been used. To me, this `fn` is for handling edge-cases, not to manage daily scenarios.

In term of problems in the implementation, I'm not sure to follow which problems it raises.

Also, that's only a suggestion of implementation, but if we look on how i3 works, it seems to change focus only when cursor cross windows borders. Does it sound more realistic for you ? 

It will have the same beneficial impact on UX: moving the cursor within an unfocused window will not change the focus.

**Comment by koekeishiya** [comment]
You can always change the modifier key to be something else than *fn*, that's just the default key so that it is mostly out of the users way, by default.

I do like this suggestion more than the original one, but I think it may be problematic to achieve in practice, in terms of performance. There is no way for us to know when the cursor crosses a window border, which means that every time the mouse is moved, we need to check what the window is, and whether the previous mouse movement was outside or inside this windows boundary to determine the action to be taken.

**Comment by koekeishiya** [comment]
I experimented with some private API that notifies us when the mouse enters inside a tracking region of a window, and it works well for some applications and not so well for others, because some applications only apply tracking regions to certain parts of the window.

I don't think it is feasible to perform the boundary check manually as mentioned in my comment above.
