### ISSUE TITLE
Feature suggestion - menu bar position

### ISSUE THREAD

**Issue by JonathanHuot** [koekeishiya/yabai#484]
Hi here and many thanks for this wonderful window manager. 

I think it will be great to have the choice of selecting the position of the status bar. I will not expect left and right, but I think `bottom` can be helpful.

e.g. `yabai -m config status_bar_position bottom`

**Comment by koekeishiya** [comment]
The status bar will be removed some time in the future. Doing a proper customizable bar is more work than I want to take upon me (due to other projects), and so I feel like adding the bar in yabai was a mistake I made early on. You can see #463 and #476 for other people whom are interested in doing a proper bar project for macOS.

**Comment by JonathanHuot** [comment]
Thanks for the quick reply, it makes sense; I will propose the feature to the *bar projects. Thanks for your work.
