### ISSUE TITLE
Firefox picture-in-picture

### ISSUE THREAD

**Issue by willus10245** [koekeishiya/yabai#496]
I've been using yabai for a while now, and I really love it. But I've run into an issue today, where after restarting my computer, yabai will not pick up and resize the picture-in-picture window when watching a video in Firefox. It's been working for me for at least a couple months, and now I can't get it to work.

Any help is appreciated. Thanks!

**Comment by b4k3s** [comment]
I noticed this too. Are you using Nightly? It seems that Mozilla has changed the way that the OS should observe the PIP window because for me, the regular Firefox still tiles the PIP video as it did before. After messing around with it for a few minutes, I have found that simply telling yabai to tile the application manually corrected the problem on my system, so I offer my solution to you. Just add the following to your yabairc:

`yabai -m rule --add app="^Firefox Nightly$" manage=on`

There are a few strange behaviors with this though. First, yabai sometimes tries to tile the PIP video's browser window even if it is minimized, leaving a gap where yabai thinks the window ought to be. I'm assuming this is because it is an extension of the window rather than its own separate window. Second, the PIP window tends to move to the focused space, even if you attempt to add `sticky=off` to the rule. This isn't a problem for me personally, but I thought I'd mention it.

Hope this helps.

**Comment by willus10245** [comment]
That worked. Thanks so much! I'm actually using Firefox Developer Edition. Idk how the release cadence differs from regular Firefox, but I'd imagine it's probably closer to Nightly

**Comment by b4k3s** [comment]
Happy to help! Correct. The Dev Edition and Nightly are very similar. Both receive features months ahead of the regular Firefox. Nightly just gets daily updates.

**Comment by nicola** [comment]
having trouble to make the picture in picture window to not follow the yabai tiling. Any suggestion?

**Comment by johnallen3d** [comment]
Hello @nicola, if I understand your question correctly, I think you're looking for the following rule:

```sh
yabai -m rule --add label="Firfox PIP" app="^Firefox$" title="^(Picture-in-Picture)$" manage=off
```

**Comment by johnallen3d** [comment]
I came here with a slightly different question/problem. I have the Firefox PIP window "un-managed" and that works great. However, (I'm guessing) because it's always-on-top, whenever I jump to a space that has the PIP window present it becomes the focused window. Further, since it's not managed, I can't simply use my binding to navigate (east/west etc). There's probably no way around this but I thought I'd throw it out there in case someone else has a clever solution that I'm overlooking.
