### ISSUE TITLE
Updated to 10.15.5 Beta (19F72f) overnight and Yabai gives the following error "Payload doesn't supported this MacOS version!"

### ISSUE THREAD

**Issue by SxC97** [koekeishiya/yabai#501]
Most of Yabai seems to still work just fine, but fast focus desktop seems to be broken.

**Comment by dominiklohmann** [comment]
Can you upload the following files:

- `/System/Library/CoreServices/Dock.app`
- `/System/Library/PrivateFrameworks/SkyLight.framework`

If you start yabai with `--verbose`, you should see a line like this in its output:

```
yabai: osax version = 1.0.8, osax attrib = 0x0
```

It'd be really helpful to know the value of `osax attrib`, because that lists what part of the scripting addition need to be updated.

**Comment by SxC97** [comment]
[Archive.zip](https://github.com/koekeishiya/yabai/files/4567306/Archive.zip)
Heres the zip files. When I try to start yabai with `yabai --verbose` I get the following response `yabai: could not acquire lock-file! abort..`

**Comment by dominiklohmann** [comment]
> When I try to start yabai with `yabai --verbose` I get the following response `yabai: could not acquire lock-file! abort..`

You need to stop the service first, yabai cannot be run more than once at the same time. I.e., `brew services stop yabai`.

**Comment by SxC97** [comment]
My bad, here's the output: `yabai: osax version = 1.0.9, osax attrib = 0x0`

**Comment by koekeishiya** [comment]
Should be fixed on master.

**Comment by LachlanGrant** [comment]
Looks live osax v1.0.10 fixed the issue for me. Thank you!
