### ISSUE TITLE
Feature request: select window by number

### ISSUE THREAD

**Issue by smackesey** [koekeishiya/yabai#504]
Yabai currently supports the ability to swap or warp by supplying an identifier for a target window in [several different formats](https://github.com/koekeishiya/yabai/wiki/Commands#move-window): direction (north/south/east/west), recency of use (recent), and some positions in window tree (first/last/next/previous). It would seem to be useful to be able to select any window in the tree by index.

I'm not sure how exactly windows are numbered, but is it determined by the position on the screen? Then users could learn to easily determine the index of the target window. I'm hoping that one would be able to do something like `yabai -m window --swap 2` to swap with the second window in the tree.

**Comment by dominiklohmann** [comment]
There is no guarantee about the order of window queries for now, but note that a window id is a valid window selector.

This means you can just take the output of a window query, sort by the windows position and then take the 2nd windows id and re-use it in a query:

```sh
yabai -m query --windows --space |
  jq 'sort_by(.frame.y, .frame.x) | .[1].id' |
  xargs yabai -m window --focus
```

**Comment by smackesey** [comment]
@dominiklohmann I see-- thanks a lot for the suggestion, it does what I was hoping for. I'll leave it up to developers to decide whether to close the issue, as I'm not sure whether anyone eventually plans to implement the functionality directly.

**Comment by dominiklohmann** [comment]
Closing this as resolved. I don't think guarantee of query output order is a good thing to add, as it may hinder other yet to be developed features.

**Comment by eraserhd** [comment]
I have a script that comes up with a stable window number (based on position):

https://github.com/eraserhd/dotfiles/blob/develop/bin/yabai-window-number

It's used [here, for example](https://github.com/eraserhd/dotfiles/blob/develop/skhd/default.nix#L22-L31).

I came up with a program `gewgaw` that displays a transparent overlay with a number and waits for one key, but it's kind of terrible (when typing at full speed, I have to wait for a flash, and I kind of want the numbers always available instead of needing to look after hitting ctrl - w)... so I think I have to revisit the approach.  Maybe it won't wait for a key, skhd can spawn it, and kill it when the next key is typed?  Anyway, advice welcome on this bit.

https://github.com/eraserhd/gewgaw/blob/develop/gewgaw.c
