### ISSUE TITLE
Inconsistent API: single-window commands

### ISSUE THREAD

**Issue by smackesey** [koekeishiya/yabai#513]
To focus a window:

```
yabai -m window --focus <WINDOW_SEL>
```

To minimize/deminimize/close a window:

```
yabai -m window <WINDOW_SEL> --{minimize,deminimize,close}
```

I'm not sure if there's a reason for this, but it seems like an oversight with user-unfriendly effects. I spent a few minutes scratching my head why my focus commands (`yabai -m window <WINDOW_SEL> --focus` weren't working.

**Comment by dominiklohmann** [comment]
It makes a bit more sense if you think about the window selectors as source and destination, source being the window to act on and destination being the window to interact with.

You act on a source window for minimize, deminimize, and close, but for switching windows you interact with a destination window.

**Comment by smackesey** [comment]
@dominiklohmann That does make more sense, though I would argue since it's still confusing since this framing is not the unambiguous and obvious choice. When I minimize a window, am I "acting on" or "interacting with" that window? Seems like both... and that window is neither a "source" nor "destination" in any obvious sense.

IMHO the source/destination makes good sense for two-window commands (e.g. warp) but single window commands should always take their argument in the same place.

**Comment by koekeishiya** [comment]
All single-window argument commands do take their argument at the front. See e.g the window toggle command.

The documentation refers to the front-argument as *the selected window (entity)* and the end-argument as *the given window (entity)*. The focus command is a two-argument command.

**Comment by smackesey** [comment]
@koekeishiya Thanks. I'm not quite sure what you mean by "focus is a two-argument command", though. The manpage just says "Focus the given window", and so far as I can tell changing the "first argument" has no effect. 

I understand that in the current *syntax*, focus is two-argument, but conceptually (unless I'm missing something) it's not. So I guess my question then would be, why is it syntactically two-argument? It's sort of like having a function `square(a,b) -> b^2`, where the first argument is irrelevant. The best I can come up with is that focus is properly conceptualized as "moving" from a source to dest, except in this case the source is always the currently focused window. But then, since the source is fixed, why let the user provide an inevitably ignored value?

BTW, I realize this issue is functionally very minor and I'm not trying to be a pain, I just like yabai a lot and am just trying to provide feedback on making it as user-friendly as possible.

**Comment by dominiklohmann** [comment]
Think of the source argument as an optional argument. The argument for the focus command is not optional.

Also you're not being a pain, this is a good discussion about CLI UX. At least I enjoy these a lot and there's usually always room for improvement.

**Comment by koekeishiya** [comment]
Hmm I'm having trouble putting my thought process into words.. 

So in general the commands are set up so that it is possible to optionally select a window that the command is going to operate on. This is the selector preceding the actual command statement (e.g: `window some_selector --move`). Then there is the actual argument to the command/function, which for some commands are also a selector, e.g: `window some_selector --swap some_selector`

The main reason the focus command is set up to be a "two-argument" command is simply that, to me, it makes more sense that the argument is passed to the command, as it does not fit the optionality requirement that the "act upon" selector enforces. It is also possible to use this to alter the behaviour of the selector given to the focus command. e.g: `yabai -m window largest --focus next` is different from `yabai -m window --focus next`. Not that this is a particularly useful thing to support, but I think it makes sense semantically.

As for the minimize etc. commands I think it makes sense for them to use the optional selector because it lets you decide whether to minimize some window by using a selector, or by omitting the selector you can implicitly make it minimize the window that is currently focused, which I think makes sense.

So the above is what my initial design was based around, but I see how it might also make sense to make the focus command not actually take the second selector as an argument.
You could do `yabai -m window some_selector --focus` and it would focus the "act on" window.
This does sort of make sense without a selector as well, where if you wrote `yabai -m window --focus` it would simply re-focus the already focused window. The reason I think this somewhat makes sense is because we do support focus-follows-mouse *without* raise (aka autofocus), in which there are practical cases where you want to re-focus the focused window to *raise* the window.

I'll let this remain open so that people can post their thoughts and opinion. Note that this is unlikely to change any time soon as it would be a breaking change, and I just did a release with breaking changes in it.

**Comment by smackesey** [comment]
Thanks @koekeishiya. I'll put down a few final thoughts on the matter.

This issue belongs to a common category of UI problem. Basically, there are two dimensions along which commands are differentiated:

1. is the argument optional? (in other words, is it sensible for the command to act on the focused window by default?)
2. does the command act on one or two windows?

Most of the time (1) and (2) point in the same direction: commands that act on two windows have a required argument, and commands that act on one window have no required argument. So it's no problem to make the syntax coherent with both (1) and (2). But with `focus`, we have a breaking of this alignment. In the most obvious conceptualization of focus, it acts on only one window but has a required argument. This disruption of the usual alignment of (1) and (2) breaks semantic-syntax coherence.

Above, you made the case for reconceptualizing focus as either (a) two-argument (comment about `largest --focus next` being different from `--focus next`); (b) needing only an optional argument (comment about focusing the already-focused window). Either reconceptualization could bring (1) and (2) back into alignment and thus restore semantic-syntax coherence.

Now, there is no "one true" conceptualization, so there's not necessarily a right choice. But what you can do is communicate whatever somewhat arbitrary choice you make clearly. This will help users develop the correct expectations. IMHO this would mean a brief paragraph in the manpage describing the design of the API.

Finally, I remain partial to (eventually) converting `focus` to a single-argument command. Here are two more points in favor of this proposition:

(a) You pointed out that the focus command actually does work with two arguments:

> e.g: `yabai -m window largest --focus next` is different from `yabai -m window --focus next`

But if `window largest --focus next` is supported, why not `window largest --minimize next`? The ability to target a single window with two arguments (e.g. next from largest) is no better match for `focus` than `minimize`. So this is another inconsistency.

(b) Currently,`deminimize` also doesn't fit the pattern-- from what I can tell a window is automatically deminimized upon focus, and minimizing a window makes it lose focus. So when would a user ever try to deminimize the currently focused window? In other words, the deminimize argument is conceptually required (like focus), but its syntax aligns with minimize/close. I understand of course that this was probably done because it is natural for minimize/deminimize to have the same syntax.

IMHO, the simplest way to resolve these conflicts is to just make `focus` a single-argument command. Even better (though this would be a much larger change) would be migrating the whole API to place the command immediately after the category (so, `window --focus <WINDOW_SEL>`, `window --swap <WINDOW_SEL_1> <WINDOW_SEL_2>`, etc. From what I can see, this latter option would eliminate a whole class of ambiguities, though obviously you wouldn't want to include such a large breaking change outside of a major release.

**Comment by koekeishiya** [comment]
I probably wouldn't mind migrating the api to be `yabai -m domain --command <arg_1> <arg_2>` instead. As far as the code is implemented, this would take maybe 5minutes to change for the entire program. The documentation would become more verbose as the arguments would be shifted down into the section outlining each commands, but if people think that is more readable and intuitive, I'm open for making that change for whenever v4.0.0 is happening.

**Comment by koekeishiya** [comment]
I think the commands such as window focus, window minimise, window close, space create, space destroy and space balance fall into its own category in which it is sometimes nice to be able to do e.g `yabai -m window foo --minimize bar` , but the most frequently used form would be `yabai -m window --minimize` to act upon the already focused window.

The above commands therefore have an optional given argument: `yabai -m window [<window_sel>] --command [<window_sel>]`.

If both arguments are specified, the given window will offset based on the selected window, e.g: `yabai -m window largest --minimize next`.

If you elide the first argument, that argument will implicitly be treated as the focused window (as all other window commands do as well).

If you elide the second argument, it will act upon the window specified in the first <window_sel>.

E.g. the command `yabai -m window --minimize` will act upon the focused window, or fail if one does not exist.
