### ISSUE TITLE
Ubersicht taking(?) click events on yabai 3.0.2

### ISSUE THREAD

**Issue by arulagrawal** [koekeishiya/yabai#535]
When using yabai 3.0.2 and Ubersicht 1.4 together and I change workspaces then left click in a window to try and interact with it, that window *loses* focus, and it seems like text is being selected in my ubersicht bar.

It seems like when I change the workspace with the trackpad gesture this bug occurs but not when I use a keyboard shortcut but I'm not sure about this.

I was pretty sure I had never seen this happen before, and sure enough if I download the 3.0.1 release and just run the pre-built binary this behaviour does not occur.

I've tried to capture this [here](https://www.youtube.com/watch?v=_nenywtjJ4c&feature=youtu.be). You can see discord/spotify losing focus when I left click on them after a workspace change, and text in ubersicht being selected at the top.

**Comment by oguzserbetci** [comment]
I'm also having the same problem after upgrading to 3.0.2, I wanted to include some output that I though might be helpful:

```
thread: 70164480 | event_signal_transmit: transmitting display_changed to 1 subscriber(s)
thread: 70164480 | EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (10640) is not observable, subscribing to activationPolicy changes
thread: 70164480 | EVENT_HANDLER_APPLICATION_TERMINATED: osascript (10640) (not observed)
```

When I quit uebersicht, I don't get the last two lines, and focussing works as it used to.

**Comment by koekeishiya** [comment]
I don’t understand why this is happening. Yabai does not focus or do anything without the user triggering a command.
The click thing looks more like an issue with Ubersicht than with yabai.

**Comment by oguzserbetci** [comment]
It happens when I send an event to übersicht to update the active space. And if I remove the events from firing everything is ok. But I didn't change anything in my setup and übersicht except for updating yabai to 3.0.2.

**Comment by koekeishiya** [comment]
This just seems like a scenario in which 2 bugs have cancelled each other, and when I fixed the bug in yabai, this one surfaces. As you describe, this occurs when ubersicht respons to a signal from yabai that the space has changed. yabai does not do anything here, it is ubersicht that for some reason decides that it needs to steal focus to update, when it should simply refresh in the background.

**Comment by arulagrawal** [comment]
Perhaps I should post this issue on the Ubersicht GitHub as well?

**Comment by koekeishiya** [comment]
That's probably the way to go. I don't see how yabai could be causing the issues mentioned here.

**Comment by AlaaSaadAbdo** [comment]
I'm also facing the same issue

**Comment by kule** [comment]
Just to add some more information for me this is related to trying to refresh a widget after changing spaces e.g. by using the following in yabairc:

`
yabai -m signal --add event=space_changed \
     action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"
`
With this configured if you ctrl+tab to an app another space or cmd+tab between apps in different spaces - Ubersicht will steal focus.

Interestingly however if you switch spaces using Yabai instead then everything works as normal e.g. using `/usr/local/bin/yabai -m space --focus x`.

**Comment by eramdam** [comment]
I've had the same issue every since 3.0.2 and after digging a bit I _think_ I've found a workaround. The bug manifested itself for me by having some shortcuts not work at all and I had to restart yabai altogether regularly (thankfully, I have a shortcut for that 😅 ).

By curiosity, I tried disabling the "Input monitoring" permission for Übersicht in `Security & Privacy` and it seems to work. I'll need to have a day or two pass to definitely tell but I thought I would post this in there to see if that helps others in the same situation 😁 

<img width="780" alt="Screen Shot 2020-06-07 at 3 25 42 AM" src="https://user-images.githubusercontent.com/1409924/83966453-2a231580-a86f-11ea-9f78-76825b3b1e0c.png">

**Comment by koekeishiya** [comment]
So what is happening is that yabai detects some invisible Übersicth window that fills the entire screen for some reason, concludes that we should not manage said window and make it topmost (due to the setting `window_topmost on`), because all floating/non-managed windows become topmost when taht setting is enabled. This makes it so that the invisible Übersicht window now takes precedence over other windows.

I have resolved this issue by simply blacklisting the Übersicht process from yabai, which makes it so that we no longer attempt to even interact with windows owned by that process. Not sure if this has any downsides to it, but I don't see any other way to fix this.

That said, I do think this is some very weird set up by Übersicht. It is definitely possible to at least not steal click events inside a invisible window, and only allow them to go through in areas where there is an actual widget being drawn.

**Comment by stoffeastrom** [comment]
I wonder if it's a similar issue I have with using [Kap screen recording](http://github.com/wulkano/kap)

Looks like it's using the native screencapture under the hood. After I start recording it's like click events get lost and suddenly it works and stops again.

![kap-screenrecording](https://user-images.githubusercontent.com/682243/84384766-c2fabd80-abee-11ea-9e3d-869421d25fd0.gif)

Using the builtin screencapture works as expected

![native-screencapture](https://user-images.githubusercontent.com/682243/84385566-18839a00-abf0-11ea-9360-a97a6e9c6eb8.gif)

I'll stick with the builtin for now :)

**Comment by koekeishiya** [comment]
I changed this from being a specific Übersicht blacklist to not touching properties of windows that report a role of AXUnknown and AXPopover. This does fix the Übersicht issue, and I believe it should handle most of these types of scenarios.
