### ISSUE TITLE
"scripting-addition" "payload is not installed, some features will not work!"

### ISSUE THREAD

**Issue by RauschUndNot** [koekeishiya/yabai#538]
Hello,

> "scripting-addition
> payload is not installed, some features will not work!"

I keep getting this message after starting yabai. Do I need to fully disable SIP? I believe I followed all of the instructions correctly.

1. Rebooted in cmd-R mode; `csrutil enable --without debug`
2. Compiled and installed via brew
3. `brew services start yabai`
4. Added yabai to the accessibility whitelist 
5. `sudo yabai --install-sa`
6. `brew services stop yabai`
7. `brew services start yabai`

I also can't get it to focus to different spaces. `yabai --check-sa` doesn't return anything. I've also restarted the computer a few times. Output from `csrutil status` is below.

Thank you, I'm excited to get yabai up and running!

MacBook Pro (13-inch, Late 2011)
MacOS High Sierra v10.13.6 (max version supported)
yabai v3.0.2
xCode v9.4.1
```
$ csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
    Apple Internal: disabled
    Kext Signing: enabled
    Filesystem Protections: enabled
    Debugging Restrictions: disabled
    DTrace Restrictions: enabled
    NVRAM Protections: enabled
    BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by koekeishiya** [comment]
I don't actually have a High Sierra system to test on these days, but what I did in the past when I was running 10.13.6:

1. Disable SIP completely. (Reboot into recovery, open terminal and type: `csrutil disable`)
2. After rebooting, install the scripting addition: `sudo yabai --install-sa`. Verify that it installed correctly by checking the exit-code: `echo $?` should output 0. Double check that you now have a folder called `yabai.osax` in `/System/Library/ScriptingAdditions`.
3. Reboot into recovery and reenable SIP, `csrutil enable`. (You can do this since you are still on High Sierra. Mojave and newer cannot reenable.)
4. Reboot and everything should now be fine.
5. If you need to update the scripting addition is the future (should get a notification saying it is out of date if an updated version of yabai has changes to the scripting addition), you need to repeat these steps.

`yabai --check-sa` also does not output anything, but it sets the exit-code which you can check using `echo $?` as mentioned above.

**Comment by RauschUndNot** [comment]
It seems that fully disabling the SIP fixed the issue! No more error message upon starting yabai, and the exit code (`echo $?`) after running `sudo yabai --install-sa` is  `0`. Before fully disabling SIP, it was `1`. 

`yabai.osax` is now in `/System/Library/ScriptingAdditions`.

Thank you!

**Comment by koekeishiya** [comment]
I've edited the wiki instructions.

**Comment by dominiklohmann** [comment]
For what it's worth, this most certainly is a user error.

**Comment by koekeishiya** [comment]
Maybe, I can't verify either way as I only have Catalina installed (and Mojave in a vm for 32bit support). I don't think it is a big deal as people on High Sierra should just re-enable SIP after installing anyway.

**Comment by sundevilyang** [comment]
> I don't actually have a High Sierra system to test on these days, but what I did in the past when I was running 10.13.6:
> 
> 1. Disable SIP completely. (Reboot into recovery, open terminal and type: `csrutil disable`)
> 2. After rebooting, install the scripting addition: `sudo yabai --install-sa`. Verify that it installed correctly by checking the exit-code: `echo $?` should output 0. Double check that you now have a folder called `yabai.osax` in `/System/Library/ScriptingAdditions`.
> 3. Reboot into recovery and reenable SIP, `csrutil enable`. (You can do this since you are still on High Sierra. Mojave and newer cannot reenable.)
> 4. Reboot and everything should now be fine.
> 5. If you need to update the scripting addition in the future (should get a notification saying it is out of date if an updated version of yabai has changes to the scripting addition), you need to repeat these steps.
> 
> `yabai --check-sa` also does not output anything, but it sets the exit-code which you can check using `echo $?` as mentioned above. (exit-code 0 means it is up to date).

hey @koekeishiya  , I need your help , much thanks. The blowing is the info
```shell
> brew list koekeishiya/formulae/yabai --versions
yabai 3.3.10
> echo $?
0
> exa --icons /System/Library/ScriptingAdditions
 Digital Hub Scripting.osax   StandardAdditions.osax
> sudo yabai --install-sa
Password:
> exa --icons /System/Library/ScriptingAdditions
Digital Hub Scripting.osax   StandardAdditions.osax
> echo $?
0
> csrutil status
System Integrity Protection status: disabled.
```

**Comment by marpes** [comment]
Since updating to macOS Monterey Version 12.0.1 I'm getting the same error every minute or so with yabai restarting even if I have disabled SIP completely.

`$ csrutil status
System Integrity Protection status: disabled.
$ sudo yabai --check-sa
$ echo $?
1
$ sudo yabai --uninstall-sa
$ echo $?
0
$ sudo yabai --install-sa
$ echo $?
2
$ brew list koekeishiya/formulae/yabai --versions
yabai 3.3.10 HEAD-39b910b`

**Comment by Liquidmantis** [comment]
@marpes see #923
