### ISSUE TITLE
Window opacity causes black screen on Catalina beta 2

### ISSUE THREAD

**Issue by chriswmartin** [koekeishiya/yabai#54]
after setting

```
yabai -m config window_opacity               on  
yabai -m config active_window_opacity        1.0  
yabai -m config normal_window_opacity        0.90
```

I was left with a blank black screen until removing the lines from my config in safe mode. I'm not sure where to find log files or anything else that could be helpful so if you would like any more information let me know!

**Comment by koekeishiya** [comment]
Could you repost this in #22 

I'd like to keep all Catalina related in one issue, so that people can test / confirm and update if something was fixed in a later Catalina version. There is always a possibility that Apple has introduced bugs in their OS at this early stage.

I personally won't be running Catalina until the GM Version is released publicly, as I don't want to run it on my main machine.
