### ISSUE TITLE
FFM autofocus causes window flashing with print dialog open

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#578]
To reproduce:

- Run `yabai -m config focus_follows_mouse autofocus`
- Open Safari
- Press <kbd>cmd</kbd> + <kbd>P</kbd> to open the print dialog
- Move cursor over Safari (outside of print dialog) and notice flashing

**Comment by koekeishiya** [comment]
I’m thinking of just removing the autofocus functionality in the next breaking release.
Is is not really useful on macOS because interacting with the window after it is focused will actually raise it, which kinda defeats the purpose of this feature, at least how I used to use it in X11.

I think autoraise + window_topmost combined mostly solves these issues.
There are minor issues with window_topmost for some UI elements, but these are fixed by simply toggling topmost off and back off once. I assume this is due to some timing issue with element creation and when yabai iterates through children to set the topmost property.

**Comment by koekeishiya** [comment]
So what is happening is that we detect the Safari window and try to make it the focused window, but since the window has a sheet/drawer window extended from it, we are unable to actually focus the window.

This can be fixed by doing something like:
```
        if (g_window_manager.ffm_mode == FFM_AUTOFOCUS) {
            CFArrayRef window_list = SLSCopyAssociatedWindows(g_connection, window->id);
            int window_count = CFArrayGetCount(window_list);
            for (int i = 0; i < window_count; ++i) {
                uint32_t wid;
                CFNumberGetValue(CFArrayGetValueAtIndex(window_list, i), kCFNumberSInt64Type, &wid);
                struct window *sheet = window_manager_find_window(&g_window_manager, wid);
                if (sheet) {
                    if (CFEqual(window_role(sheet), kAXSheetRole)) {
                        window = sheet;
                        break;
                    }
                }
            }
            window_manager_focus_window_without_raise(&window->application->psn, window->id);
            g_mouse_state.ffm_window_id = window->id;
        } 
         ...
```

I don't know if this will cover *all* cases like this, as we look for specific sheet windows.
A more expensive way to fix this would be to detect the parent-child relationship between the resulting set of windows, and traverse the hierarchy to the leaf child, look up that window and focus that window.

This may not be as expensive as I think, so I'll probably give that a shot before pushing any changes here. These are the only two ways that solves this issue. I did try and look at window tags for a bit, but that broke autofocus for some applications like System Preferences, due to tags not being unique enough to identify this situation correctly.

Regarding the window_topmost situation that I mentioned. The issue there is that a window can *create a new window when e.g: details/show more* button is pressed, and we don't get a notification that this window was created (not even subscribing to kAXWindowCreated on the window itself worked), and that issue is likely impossible to fix/automate.
