### ISSUE TITLE
'yabai -m external_bar main:20:0' returns 'unknown domain 'external_bar''

### ISSUE THREAD

**Issue by ryuta69** [koekeishiya/yabai#604]
I typed the command which introduced below.

https://github.com/koekeishiya/yabai/wiki/Configuration#status-bar

**Comment by dominiklohmann** [comment]
That section was outdated. I removed it.

You can just include the additional padding in your top padding.

**Comment by koekeishiya** [comment]
The section was fine, just a typo. It should be `yabai -m config external_bar ..`.

**Comment by dominiklohmann** [comment]
Oops, fixed. 🙈

**Comment by koekeishiya** [comment]
The difference between this and the *_padding* properties is that *--toggle padding* is not going to remove it, allowing the übersicht bar or whatever to remain visible. I don't personally use a bar, but a lot of people do and since this simple version was fairly trivial to support, I figured why not.

**Comment by ryuta69** [comment]
Great, it worked!
Thank you very much.

**Comment by ryuta69** [comment]
Since @dominiklohmann reopened this issue, I will leave this issue opened.

**Comment by dominiklohmann** [comment]
Just re-opened it because I was fixing my mistake. Glad to see it worked.
