### ISSUE TITLE
Yabai too slow

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#612]
Hello team,

I really like the features that `Yabai` provides however it's too slow in my machine.
Not sure if it's due to `skhd` or `Yabai` alone but whenever I'm using the shortcuts there is a huge delay of *2-3* sec for `Yabai` to trigger the desired action.

Following are my machines specs:
```
OS: macOS Catalina 10.15.4 19E287 x86_64
Host: MacBookPro15,1
Kernel: 19.4.0
Uptime: 43 mins
Packages: 236 (brew)
Shell: fish 3.1.2
Resolution: 2560x1440
DE: Aqua
WM: yabai
CPU: Intel i7-8750H (12) @ 2.20GHz
GPU: Intel UHD Graphics 630, Radeon Pro 555X
Memory: 9156MiB / 16384MiB
```

**Comment by koekeishiya** [comment]
Your shell is the issue. See https://github.com/koekeishiya/skhd/issues/42 or search the issue boards for fish.

Sent from my iPhone

On 16 Jul 2020, at 07:16, Jaideep Rana <notifications@github.com> wrote:

﻿

Hello team,

I really like the features that Yabai provides however it's too slow in my machine.
Not sure if it's due to skhd or Yabai alone but whenever I'm using the shortcuts there is a huge delay of 2-3 sec for Yabai to trigger the desired action.

Following are my machines specs:

OS: macOS Catalina 10.15.4 19E287 x86_64
Host: MacBookPro15,1
Kernel: 19.4.0
Uptime: 43 mins
Packages: 236 (brew)
Shell: fish 3.1.2
Resolution: 2560x1440
DE: Aqua
WM: yabai
CPU: Intel i7-8750H (12) @ 2.20GHz
GPU: Intel UHD Graphics 630, Radeon Pro 555X
Memory: 9156MiB / 16384MiB

**Comment by jaideeprana** [comment]
Thanks a ton :)

It was indeed issue because of the fish shell that I was using. The ticket reference that you gave solved the issue for me :) 👍

**Comment by lawrence-laz** [comment]
Sorry to bump this old issue, but this is one of the first hits in google when searching for this issue.
In my case the issue was with just installed XCode and it somehow was running in the background of the shell and kept asking to accept the license. Once I did that by running `sudo xcodebuild -license` all the lag was gone.

**Comment by alexrenz** [comment]
> Sorry to bump this old issue, but this is one of the first hits in google when searching for this issue. In my case the issue was with just installed XCode and it somehow was running in the background of the shell and kept asking to accept the license. Once I did that by running `sudo xcodebuild -license` all the lag was gone.

Thank you for this, this solved the lag for me too 💛  An alternative to `sudo xcodebuild -license` (which somehow failed for me) is to launch Xcode and accept the license.
