### ISSUE TITLE
terminal windows produce a padding on their right and on the bottom

### ISSUE THREAD

**Issue by pberto** [koekeishiya/yabai#651]
using macOS default terminal app.

For some reason, ONLY the terminal app is producing a gap on its right and bottom edges (left and top edges have zero gap...). All other windows are gapless.

Any idea why this is happening?

**Comment by dominiklohmann** [comment]
Many terminals, including Terminal.app, require their window size to be a multiple of a single character blocks size.

Personally, I use iTerm instead, which has a hidden option for adding padding so that windows can be resized smoothly. As far as I know, no such option exists for the default Terminal.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/4488655/91660485-87c5a780-ead6-11ea-83e5-42f037828b5e.png">

**Comment by pberto** [comment]
Thanks, this is the reason indeed. Closing.
