### ISSUE TITLE
Are dropdown floating windows possible?

### ISSUE THREAD

**Issue by Granitosaurus** [koekeishiya/yabai#657]
Hello, often TWMs offer dropdown functionality for various apps. For example dropdown terminal would display and hide terminal on keypress. Most famous example would be yakuake terminal.

I've been trying to figure out how to do this in Yabai and so far no luck. I'd like to have dropdown window for Kitty terminal.

**Comment by 24unix** [comment]
iTerm has such an option.
Maybe that's an option?

**Comment by Granitosaurus** [comment]
@24unix yeah but I'd be interested in several programs behaving this way: kitty, spotify, todo app etc.

**Comment by Liquidmantis** [comment]
Ahhh, `quake mode` :)  If you don't care about the animation, it'd probably be easy to set the desired apps to be always on top and sticky, then just create a show/hide toggle hotkey for them, even if just for a temporary solution.

**Comment by Granitosaurus** [comment]
@Liquidmantis I figured out the placement and sticky, but how do you hide windows?

**Comment by dominiklohmann** [comment]
You can do this by minimizing windows:

To summon a floating window, move it to the current space while still minimized, set it to floating, move it to its target coordinates on the active space, then deminimize it. Writing a script for this should be trivial.

To remove it again, just press <kbd>cmd</kbd> + <kbd>M</kbd> to minimize it.

**Comment by Granitosaurus** [comment]
I got a command that summons window to current space but I can't figure out how to toggle it away with the same key:

```
# skhdrc
# cmd + o moves kitty to current space
cmd - o : yabai -m window $(yabai -m query --windows | jq '.[] | select(.app=="kitty") | .id') --space $(yabai -m query --spaces | jq '.[] | select(.focused==1) .id')
```

Not sure the rest is possible though.

Can yabai minimize a window? Having two keys to summon window and another to minimize it isn't great 😬

**Comment by dominiklohmann** [comment]
> Can yabai minimize a window? Having two keys to summon window and another to minimize it isn't great 😬

Yes, using `yabai -m window [<window selector>] --minimize`. See also: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#642-command

**Comment by Granitosaurus** [comment]
The closest I've managed to get so far is this:
```
# logic:
# minimize kitty 
# or 
# deminimize kitty & move kitty to current space & focus kitty
cmd - o : yabai -m window $(yabai -m query --windows | jq '.[] | select(.app=="kitty") .id') --minimize ||\
          (yabai -m window $(yabai -m query --windows | jq '.[] | select(.app=="kitty") .id') --deminimize;\
          yabai -m window $(yabai -m query --windows | jq '.[] | select(.app=="kitty") .id') --space mouse;\
          yabai -m window --focus $(yabai -m query --windows | jq '.[] | select(.app=="kitty") .id'))
```

Which ends up just being too clunky and slow to actually be usable :(
Primarily because of minimize/deminimize animation which cannot be disabled.

**Comment by chaoxu** [comment]
I'm having the same problem here.

If you can toggle between this abstract state of hidden and shown, then this is very easy. Since you know what to do when hidden: "move the window and focus it". when it is shown: "do something to hide it and focus on previous window".

There are 3 ways I can think of, all because we cannot add extra information to the windows to yabai. 

1. Create a space specifically for hidden. Say space 1. then you need to config all your hotkeys to not able to access this space. 
2. Use the coordinates to store information. If the coordinate of the window is at x=10000, y=10000, then it means the window is hidden, and you hide the window by moving the window to x=10000, y=10000 (and focus on previous window).
3. Write another script that manages the state. For example, every time command is called, you either write a file on disk or delete that file. the existence of the file indicates if the window is hidden or not.

**Comment by Granitosaurus** [comment]
The way some other tilling window managers handle dropdown windows: there's a "scratchpad" workspace that is a hidden workspace that acts as a storage container. Windows are being sent to scratchapd to be hidden and called back to active space on request. 

Unfortunately neither macos nor Yabai has hidden workspace support so all of the display tools etc will get poluted with the scratchpad workspace. This means you kinda have to reserve one of your workspaces as the temp space.

I wrote this short python script that implements this in Yabai: https://github.com/Granitosaurus/bin/blob/master/dropdown
In short it checks whether app is visible: if not it summons it to current space, otheriwse sends app to scratchpad workspace (which by default is workspace 6).

It works well, however the delay is quite noticable and I think it's just Yabai/macos being a bit slow to move windows around workspaces. It's much faster than the above minimize/maximize approach but still noticably slower than iTerm2's dropdown. 

I'm using it to summon Spotify and it's quite usable in that regard (maybe <0.5 second delay?):
```
# skhdrc
ctrl - o : /Users/me/bin/dropdown Spotify
```
![2563-10-19 15 14 17](https://user-images.githubusercontent.com/5476164/96419112-df060f80-121d-11eb-84f8-249de982f9c9.gif)

Maybe if this could integrated directly into Yabai it could be fast enough for terminal dropdown. It also could be that python's interpreter is the bottle neck though that seems unlikely.

**Comment by paulodiovani** [comment]
I know this is an old discussion, but it helped me as a starting point (especially @Granitosaurus answer) to create my own Drop Drown (Quake mode) terminal much like the one I have on Sway/i3.

I preferred using minimize/restore instead of a dedicated (scratchpad) space as some have suggested.

Features:

- Uses `ctrl - escape` keybinding (or whatever you want)
- Set to use 40% of screen vertical space
- Open a new terminal window or minimize/restore the existing one if any
- Uses window title ("ddterm") as selector, so it shall work with any terminal emulator that allows to set the window title at launch (I use Alacritty)
- Configuration is done in two parts, yabai + skhd

Caveats:

- The minimize/restore animation can't be disabled on Mac OS, or at least I didn't find a way, but you set to `Scale Effect` in `System Settings  -> Desktop & Dock -> Dock`, which make it much less annoying
- Yabai doesn't work quite well with multiple screens and sometimes the "ddterm" might open in the wrong one or have an incorrect grid size when switching between them

Config files:

`~/.config/yabai/yabairc`

```bash
# dropdown terminal (aka "Quake mode")
# see additional config in ~/.config/skhd/skhdrc
yabai -m rule --add title="ddterm" manage=off grid="10:1:0:0:1:4"
```

`~/.config/skhd/skhdrc

```apache
# dropdown terminal (aka "quade mode")
# see additional config in ~/.config/yabai/yabairc
ctrl - escape : WINDOW_ID=$(yabai -m query --windows | jq -e '.[] | select(.title=="ddterm") | .id');   \
                if [ -z "$WINDOW_ID" ]; then                                                            \
                  open -na /Applications/Alacritty.app --args --title "ddterm";                         \
                else                                                                                    \
                  yabai -m window "$WINDOW_ID" --deminimize "$WINDOW_ID" --space mouse --focus ||       \
                  (yabai -m window "$WINDOW_ID" --minimize && yabai -m window mouse --focus);           \
                fi;                                                                                     \
```

My full config files:

- https://github.com/paulodiovani/dot-files/blob/macosx/home/user/.config/yabai/yabairc
- https://github.com/paulodiovani/dot-files/blob/macosx/home/user/.config/skhd/skhdrc

**Comment by garymm** [comment]
Inspired by the above, doing this with kitty:
```bash
WINDOW_TITLE="ddterm"
WINDOW_ID=$(yabai -m query --windows | jq -e ".[] | select(.title==\"$WINDOW_TITLE\") | .id") || true
if [[ -z "$WINDOW_ID" ]]; then
    pgrep -x kitty >/dev/null &&
        kitty @ new-window --title "$WINDOW_TITLE" ||
        open -na /Applications/Kitty.app --args --title "$WINDOW_TITLE"
else
    WINDOW_QUERY=$(yabai -m query --windows --window "$WINDOW_ID")
    IS_HIDDEN=$(echo "$WINDOW_QUERY" | jq '."is-hidden"')
    HAS_FOCUS=$(echo "$WINDOW_QUERY" | jq '."has-focus"')
    if [[ "${HAS_FOCUS}" != "true" ]]; then
        yabai -m window "$WINDOW_ID" --space mouse --move abs:0:0 --grid "10:1:0:0:1:4" --layer above --focus
    fi
    if [[ "${IS_HIDDEN}" != "true" ]]; then
        skhd -k "cmd - h"
    fi
fi
```
