### ISSUE TITLE
Border colors based on window's state: sticky, zoom, float etc.

### ISSUE THREAD

**Issue by Granitosaurus** [koekeishiya/yabai#663]
Sometimes it's a bit difficult to understand the state of a window.  
For example there's no visual difference between 1 normal window and 2 window: 1 normal and 1 zoomed in; or accidently making window sticky and being perplexed why workspace keys have stopped working.

I think it would be great to have border color settings based on window state:
```
# we already have
normal_window_border_color
active_window_border_color
# suggesting:
sticky_window_border_color
zoom_window_border_color
floatt_window_border_color  # this one can be kinda replicated with `window_shadow float`
```
With these configurations there would be always visual feedback on the state of on-screen windows.

**Comment by lpke** [comment]
I second this idea. I'd love to have window borders for tiled windows only and everything else being styled as per OS default.

Any plans on implementing this @koekeishiya? Just curious.

**Comment by Bloumbs** [comment]
@Granitosaurus @lpke I just added these things to [my fork](https://github.com/Bloumbs/yabai#new-stuff) if you still care to try out those features. But fyi, I'm still on macOS 10.15.7, not Big Sur, and my fork isn't fully caught up to the latest in this koekeishiya/yabai because it's just my personal fork for messing around with features like that, so it works fine for me and the way I use it. Also, I'm not the smartest with this stuff, so there may be a thing or two that doesn't work maybe as expected because I missed it lol, I hardly even use the floating/sticky/zoomed window stuff personally, so if you needed to mess with it or put the features in your own fork, the added features code in the commit history is pretty easy to follow.

**Comment by braham-snyder** [comment]
Related: #89
