### ISSUE TITLE
Just a stupid question regarding "Displays have separate Spaces"

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#668]
Hi, just out of curiosity:

If one would remove all the window moving/handling stuff from yabai, only leave the opacity in place, would it be possible to run the remainder with combined spaces?

I tried bsp, found out that floating better fits my needs, but I really like the window opacity.

Kind regards,
  Micha

**Comment by koekeishiya** [comment]
Displays have separate spaces is a requirement because of the APIs we use to manage window state, which space they belong to and other things. As such, it would be hard to simply strip yabai of features and expect opacity to work.
However, this is simply because of the combined complexity of the tasks that yabai is trying to do as a whole, and there is no reason why you could not make some software that simply wants to control window opacity and have that work without the separate spaces requirement.

**Comment by 24unix** [comment]
Many thanks for you reply.

Yesterday I googled around to find out more about the opacity, but all I found was how to change it inside an application. Might you give me some keywords for further research on how yabai accesses the opacity of "foreign" windows?

**Comment by koekeishiya** [comment]
The code responsible for the alpha change is here: https://github.com/koekeishiya/yabai/blob/master/src/osax/payload.m#L788
This is code that has to be injected (through the scripting-addition) into Dock.app to work properly.

After the scripting-addition has been installed and loaded into Dock.app, it is signalled as follows: https://github.com/koekeishiya/yabai/blob/master/src/osax/sa.m#L515
The following shell command could take the place of this code
```
# 2621 is the window id, 1.0 is the requested opacity value, 0.0 is the duration of the alpha change
echo "window_alpha_fade 2621 1.0 0.0" | nc -U /tmp/yabai-sa_$USER.socket
```

**Comment by 24unix** [comment]
Thank you very much.
