### ISSUE TITLE
Empty space does not get focused

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/yabai#687]
I have disabled the desktop because I don't use it, and its just cludder. It causes a weird issue with focus on empty spaces on multi monitors. If I jump to an empty space yabai focuses a window on my other monitor. This causes issues where I cannot refocus the empty space. Note this is only an issue when I want to remove an empty space. My workaround is to move a window to the space and delete the space that way.
```
# TO DISABLE DESKTOP
defaults write com.apple.finder CreateDesktop -bool false
killall Finder

# TO ENABLE DESKTOP
defaults write com.apple.finder CreateDesktop -bool true
killall Finder
```

**Comment by koekeishiya** [comment]
Do you get this bug with desktop enabled, but simply having nothing on it? Is there a reason why that is not a feasible solution for you? I suspect whatever this command is doing, interferes with how we can focus monitors, because we need to do so by actually focusing the invisible finder desktop window, if  no windows are currently visible. There is no API call to simply focus a monitor or space itself.

**Comment by brorbw** [comment]
Yes, the bug only happens when the desktop is disabled but the command only disables icons and desktop, and I'm not sure how that impacts the way spaces are focused

**Comment by WesleyYue** [comment]
@koekeishiya I have a similar problem here in that I cannot do a "move window to next space and focus on next space" command in a multi-monitor setup when there is only one window left in the space. When I try, the window will be moved to the next space, but since there is nothing left in the space, the focus is immediately stolen by my second monitor such that when the "focus on next space" command occurs, it is switching the space in my other monitor.

It seems like the best solution for my issue at least is an atomic command that does both the moving and focusing in one instruction.

**Comment by brorbw** [comment]
@dominiklohmann by that reasoning most bugs could be labelled as unsupported

**Comment by dominiklohmann** [comment]
If you run this command and use multiple displays you cannot even focus the display without yabai if there are no other windows on it. The reason is quite simple: The command stops the Dock from creating the Desktop window, and if there is no window on a display, it also cannot be focused. The command you're using here isn't documented anywhere as far as I can tell.

**Comment by brorbw** [comment]
@dominiklohmann you are absolutely right - but I don't see why this isn't an issue that can be fixed inside yabai.

**Comment by koekeishiya** [comment]
Why do you need to run this command. Can't you just not utilise the desktop; what's the difference?

Creating and managing an invisible window on each space is not actually as trivial as you make it seem, and complexity like this quickly snowballs if we are to support weird quirks (not just this one in particular, but as I said a line has to be drawn at some point).

There are also other issues such as the user manipulating spaces through either mission-control or alternative software that we have no way of interacting with, thus, making our invisible window solution go out of sync. You can argue that this is an edge-case, but my point is simply that for the software to be robust and work well in a consistent manner, such solutions are not something I opt to implement without a very good reason.

**Comment by brorbw** [comment]
This is an egde case, but screenshots etc end up on the desktop and there is afaik no workaround. 

I have no issues with this being unsupported or drawing a line somewhere. The point of the software working in a consistent way does however negate the argument for not implementing a system to handle the oddballs. I'm very pleased with yabai and appreciate the time and effort everyone puts into it. I merely pointed out an observed bug/odd behaviour and wanted to investigate. I off work for Christmas and might look into a solution of using the mouse to focus the monitor. 

Merry Christmas 🎄

**Comment by koekeishiya** [comment]
@brorbw 

If someone can come up with a robust solution for supporting this, then I will happily implement that. The issue I have is implementing workarounds that aren't fully robust solutions, that just snowballs the complexity for something that only solves the issue when particular assumptions are true. If you want to try and investigate this further I am open for suggestions.

Happy Christmas ☃️

**Comment by 24unix** [comment]
@brorbw 

you can use 
defaults write com.apple.screencapture location <mylocation>

**Comment by brorbw** [comment]
@24unix that totally solves the issue

**Comment by ph9t** [comment]
How does that solve the issue? It doesn't even run because the lack of a necessary argument.

**Comment by brorbw** [comment]
It solved my issue as I wanted to have a clean desktop. Previously that was possible with disabling the desktop. However that made it difficult for yabai to focus an empty space.

I take a lot of screenshots for work which end up on the desktop, which made it very messy.

24unix suggestion fixed this as I was able to change the location of the screenshots and keep my desktop free of icons (pure bliss).

>lack of a necessary argument

Sounds like you copied the command directly. You have to specify the location where you want the screenshots to go to.
```
defaults write com.apple.screencapture ~/path/to/wanted/location
```

I understand that this will not solve any issues wrt. yabai not focusing spaces due to misconfiguration or edge cases but it did solve my issue.
