### ISSUE TITLE
Question: Run only when needed?

### ISSUE THREAD

**Issue by KevinFerm** [koekeishiya/yabai#689]
Hey!

I'm looking into starting to use Yabai, looks awesome by the way! But ideally I'd like a specific functionality, in that I want to be able to, through Alfred or something, run a script that toggles Yabai on and off. It boils down to that while programming, I'd rather use something like Yabai, but for day-to-day I want the native MacOS experience.

**Comment by Liquidmantis** [comment]
This is a trivial problem, honestly.  You could just start and stop the Yabai service on-demand:
`brew services start yabai` - yabai on
`brew services stop yabai` - yabai off

Alternatively though, from personal experience I think you'll start to integrate Yabai into your workflow, and it's easier to just toggle a space to Floating rather than BSP.  If you start dabbling with stacking that can become an invaluably powerful alternative to cmd-tab'ing.

**Comment by yanzhang0219** [comment]
You can set a space or more to `float`. Put this into your yabairc: `yabai -m config --space 4 layout float`. Then you can enjoy the native macOS experience in space 4, and when you miss yabai, you could switch to other spaces.

**Comment by edward-mb** [comment]
I use Yabai like this:
`yabai -m config layout                       float` ~ /.yabairc

and then you can change the layout of the current space/desktop by adding to your ~/.skhdrc something like:
```
ctrl + alt - a : yabai -m space --layout bsp
ctrl + alt - d : yabai -m space --layout float
```
