### ISSUE TITLE
Re-introduce border radius

### ISSUE THREAD

**Issue by knowler** [koekeishiya/yabai#715]
https://github.com/koekeishiya/yabai/issues/565#issuecomment-642230037

> The border system does not support border radius and placement like the old system did, and it probably never will; guess we'll see.

Since most windows on Big Sur have rounded corners, I was wondering if re-introducing border radius could be considered.

**Comment by koekeishiya** [comment]
My opinion has not changed since the original comment you referenced. The reasoning is simply that we are not able to query individual windows (or the application) for the corner mask/radius that we would need to properly match any given window.
I find square corners for borders to be the most appropriate for that reason.

**Comment by 24unix** [comment]
As I can see it any window on Big Sur has the same borderradius?

**Comment by Rougemoot** [comment]
Or have it be a config, I'd be happy with being able to set a radius in yabairc and have the same radius on every window

**Comment by zzzeyez** [comment]
this was one of the most elegant features of chunkwm and i miss it!  i don't think anyone's asking that it be perfect or respond differently to separate windows

**Comment by MDangleben** [comment]
This is a must-have for using borders on Big Sur. Will have to roll my own version of this until this is addressed.

**Comment by koekeishiya** [comment]
This will be fixed with the changes being made for #1430
