### ISSUE TITLE
windows border on Big Sur

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/yabai#732]
the border is visible on app startup but as soon as i click to focus the app, the border is not visible any more except the corner.

is this a bug?

on startup

<img width="851" alt="image" src="https://user-images.githubusercontent.com/627278/99826897-89f64a00-2b8b-11eb-8dde-198e262fe9b6.png">

after click the app

<img width="858" alt="image" src="https://user-images.githubusercontent.com/627278/99826952-9da1b080-2b8b-11eb-8146-2305f80e238e.png">

**Comment by koekeishiya** [comment]
So the issue here is that the scripting-addition must be loaded *before* the border is created, because it requires functionality provided by the scripting-addition to properly follow windows.

To fix this, follow the instructions specified in the section  that mentions Big Sur here: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

Snippet explaining this in the sample config: https://github.com/koekeishiya/yabai/blob/master/examples/yabairc#L3

Hopefully the instructions are understandable.

**Comment by tuananh** [comment]
yeah, i already did that.

i copied the code from another comment which installed yabai to another location hence it didn't work at first try

```
<user> ALL = (root) NOPASSWD: /opt/local/bin/yabai --load-sa
```
while yabai is actually at `/usr/local/bin/yabai`

It's working now after i edit the file location. Thanks
