### ISSUE TITLE
[Big Sur] scripting-sa and SIP issue

### ISSUE THREAD

**Issue by wbrydak** [koekeishiya/yabai#742]
Hi!

I'm running macOS Big Sur, I've disabled SIP 

```
❯ csrutil status
System Integrity Protection status: disabled.
```

I've installed  scripting-addition

Freshly after `sudo yabai --instal-sa` `echo $?` returns 0

But right after trying to run a command to i.e focus into another space I'm getting a message: 

```
cannot focus space due to an error with the scripting-addition.
```

After that message `echo $?` returns 1.

**Comment by wrongsyntax** [comment]
I was also having the same issue, doing the following from #712 worked to fix this
```
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
```

This also worked to fix another issue I was having with the borders disappearing behind the active window.
I think it has to do with the last command there, since the [installation instructions](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)) don't mention that command.

**Comment by yanzhang0219** [comment]
@koekeishiya didn't mention that you should run `sudo yabai --load-sa` after `sudo yabai --install-sa` at your first timie installation.

**Comment by wbrydak** [comment]
@wrongsyntax @yanzhang0219 thanks!
Worked like a charm :)

Closing issue for now
