### ISSUE TITLE
I keep getting yabai scripting-addition notification

### ISSUE THREAD

**Issue by ashkan-leo** [koekeishiya/yabai#764]
I keep getting the notification "Yabai scripting-addition payload v1.0.26". It pops non stop, like 10 times each minute. It seems the payload is injected successfully. I am on yabai-v3.3.4 and macOS 10.15.7 (19H114)

**Comment by ashkan-leo** [comment]
I ended up turning off the scripting addition. The payload is actually re-injected in an infinite loop which causes the minimized windows to re-appear again.
I'd appreciate any insight on why this is happening and how to fix it.

**Comment by koekeishiya** [comment]
So unless you've done something in your configuration, the scripting addition will load either when yabai is launched, or when the Dock application is restarted (and yabai is already running).

If you experience an injection-loop, my assumption would be that either the Dock or yabai is continuously crashing on your system and being restarted by the launchd service. You can look in Console.app for crash logs to see if this is the case.

If that is not the case, I would make sure to do a full uninstall of yabai, and do a fresh install of the latest version.

**Comment by webframp** [comment]
I'm having this same problem just now after the last supplement update on 10.15.7

**Comment by WhiteAbeLincoln** [comment]
I'm also having similar problems on macOS Catalina 10.15.7. I do not get the notification, but the dock seems to constantly restart - my background flashes black and windows unfocus and focus. When this happens, I am unable to switch workspaces with yabai, which makes me think it is a scripting addition error. I am seeing logs in Console.app indicating that the scripting addition is crashing:

<details>
<summary>Console.app log</summary>

```
Feb 18 23:36:45 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:36:54 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4283]): Service exited with abnormal code: 1
Feb 18 23:36:54 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4284]): could not terminate service: 3: No such process
Feb 18 23:36:55 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4285]): Service exited with abnormal code: 1
Feb 18 23:36:55 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:05 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4299]): could not terminate service: 3: No such process
Feb 18 23:37:05 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4298]): Service exited with abnormal code: 1
Feb 18 23:37:06 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4300]): Service exited with abnormal code: 1
Feb 18 23:37:06 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:07 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0C000000-0500-0000-0000-000000000000[4144]): Service exited due to SIGKILL | sent by mds[81]
Feb 18 23:37:15 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4313]): Service exited with abnormal code: 1
Feb 18 23:37:17 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4315]): Service exited with abnormal code: 1
Feb 18 23:37:17 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:23 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0400-0000-0000-000000000000[4207]): Service exited due to SIGKILL | sent by mds[81]
Feb 18 23:37:26 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4328]): Service exited with abnormal code: 1
Feb 18 23:37:27 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4330]): Service exited with abnormal code: 1
Feb 18 23:37:27 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:37 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4343]): Service exited with abnormal code: 1
Feb 18 23:37:37 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4344]): could not terminate service: 3: No such process
Feb 18 23:37:38 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4345]): Service exited with abnormal code: 1
Feb 18 23:37:38 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:47 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4358]): Service exited with abnormal code: 1
Feb 18 23:37:48 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4360]): Service exited with abnormal code: 1
Feb 18 23:37:48 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:58 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4373]): Service exited with abnormal code: 1
Feb 18 23:37:59 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4375]): Service exited with abnormal code: 1
Feb 18 23:37:59 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
```
</details>

I'm not sure what to do. I've tried reinstalling the scripting addition and making sure yabai is the latest released version (3.3.7). For what its worth, I installed yabai through nix-darwin instead of homebrew, though I hope this shouldn't make a difference.

**Comment by koekeishiya** [comment]
I have no idea what nix is doing so I can’t comment on that. I do know that I did run yabai on Catalina 10.15.7 without issues.

Please do try to either build from source and run manually from a terminal or install using homebrew.

Sent from my iPhone

On 19 Feb 2021, at 06:40, Abraham White <notifications@github.com> wrote:

﻿

I'm also having similar problems on macOS Catalina 10.15.7. I do not get the notification, but the dock seems to constantly restart - my background flashes black and windows unfocus and focus. When this happens, I am unable to switch workspaces with yabai, which makes me think it is a scripting addition error. I am seeing logs in Console.app indicating that the scripting addition is crashing:

Console.app log

Feb 18 23:36:45 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:36:54 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4283]): Service exited with abnormal code: 1
Feb 18 23:36:54 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4284]): could not terminate service: 3: No such process
Feb 18 23:36:55 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4285]): Service exited with abnormal code: 1
Feb 18 23:36:55 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:05 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4299]): could not terminate service: 3: No such process
Feb 18 23:37:05 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4298]): Service exited with abnormal code: 1
Feb 18 23:37:06 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4300]): Service exited with abnormal code: 1
Feb 18 23:37:06 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:07 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0C000000-0500-0000-0000-000000000000[4144]): Service exited due to SIGKILL | sent by mds[81]
Feb 18 23:37:15 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4313]): Service exited with abnormal code: 1
Feb 18 23:37:17 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4315]): Service exited with abnormal code: 1
Feb 18 23:37:17 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:23 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0400-0000-0000-000000000000[4207]): Service exited due to SIGKILL | sent by mds[81]
Feb 18 23:37:26 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4328]): Service exited with abnormal code: 1
Feb 18 23:37:27 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4330]): Service exited with abnormal code: 1
Feb 18 23:37:27 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:37 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4343]): Service exited with abnormal code: 1
Feb 18 23:37:37 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.dock.extra[4344]): could not terminate service: 3: No such process
Feb 18 23:37:38 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4345]): Service exited with abnormal code: 1
Feb 18 23:37:38 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:47 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4358]): Service exited with abnormal code: 1
Feb 18 23:37:48 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4360]): Service exited with abnormal code: 1
Feb 18 23:37:48 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Feb 18 23:37:58 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (com.apple.Dock.agent[4373]): Service exited with abnormal code: 1
Feb 18 23:37:59 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa[4375]): Service exited with abnormal code: 1
Feb 18 23:37:59 Abrahams-Mac-Pro com.apple.xpc.launchd[1] (org.nixos.yabai-sa): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.


I'm not sure what to do. I've tried reinstalling the scripting addition and making sure yabai is the latest released version (3.3.7). For what its worth, I installed yabai through nix-darwin instead of homebrew, though I hope this shouldn't make a difference.

**Comment by WhiteAbeLincoln** [comment]
I'll try building from source and see if that helps.

**Comment by webframp** [comment]
I had some remnants of nix-darwin testing as well, perhaps that contributing to the problem. I'll dig into that.

Here's the output when yabai is run in the foregroundm ,it just keeps repeating:

```
yabai configuration loaded..
process_is_observable: Dock (3554) is blacklisted! ignoring..
EVENT_HANDLER_DOCK_DID_RESTART:
yabai: scripting-addition successfully injected payload into Dock.app..
yabai: osax version = 1.0.26, osax attrib = 0x3F
process_is_observable: com.apple.dock.extra (3555) was marked as xpc service! ignoring..
process_is_observable: Dock (3569) is blacklisted! ignoring..
EVENT_HANDLER_DOCK_DID_RESTART:
yabai: scripting-addition successfully injected payload into Dock.app..
yabai: osax version = 1.0.26, osax attrib = 0x3F
process_is_observable: com.apple.dock.extra (3570) was marked as xpc service! ignoring..
process_is_observable: Dock (3584) is blacklisted! ignoring..
EVENT_HANDLER_DOCK_DID_RESTART:
yabai: scripting-addition successfully injected payload into Dock.app..
yabai: osax version = 1.0.26, osax attrib = 0x3F
process_is_observable: com.apple.dock.extra (3585) was marked as xpc service! ignoring..
```

**Comment by webframp** [comment]
The problem for me was lingering configuration of nix-darwin installed instance of yabai. After removing nix-darwin and switching back to brew installed yabai version, the service at `/Library/LaunchDaemons/org.nixos.yabai-sa.plist` was left over and competing with the brew install yabai, causing a crashloop. Stopping/Unloading/Removing `org.nixos.yabai-sa` and restarting resolved it for me.

**Comment by WhiteAbeLincoln** [comment]
I removed org.nixos.yabai-sa and that solved the issue. I've wrote my own yabai nix module and manually install the scripting addition after I do a darwin-rebuild, and I'm not getting the bug anymore. It definitely is an issue with the scripting addition service that is added by nix-darwin.

**Comment by andrew-womeldorf** [comment]
@WhiteAbeLincoln I'm having the same issue with the scripting-addition module in nix-darwin:

> ...but the dock seems to constantly restart - my background flashes black and windows unfocus and focus. When this happens, I am unable to switch workspaces with yabai...

Would you mind sharing what your solution was?

**Comment by atremblay** [comment]
Mac mini M1, just updated to 12.2 from 11.x. Had to disable SIP again.

Having this popup constantly. I have uninstalled/reinstalled yabai and the loading script. Still the same problem. I have one space that is floating, the rest are tiling. In the floating space, as soon as I open something it tiles everything. Afterwards I can still move things around.

In the tiling spaces, the windows are reordered based on alphabetical order it seems.

Console.app is not reporting anything in particular.  Given that the issue is opened since 2020 I suppose we are not that many people with this problem?

**Comment by atremblay** [comment]
I tried the dev version and it seems to work if anyone else is in a similar setup as I am.
