### ISSUE TITLE
MacOS 11.1 upgrade - payload doesn't support this MacOS version

### ISSUE THREAD

**Issue by emninger** [koekeishiya/yabai#765]
I did the recent MacOS 11 upgrade and i'm getting now the above error msg. What can/could/should i do or check - if at all ... ?

I tried to install the dev version of yabai instead, but when doing:
`~ >>> codesign -fs 'yabai-cert' $(which yabai)
/usr/local/bin/yabai: replacing existing signature
/usr/local/bin/yabai: resource fork, Finder information, or similar detritus not allowed
`

**Comment by gasper-vrhovsek** [comment]
Can confirm, upgraded to big sur yesterday and i'm getting this also.

**Comment by emninger** [comment]
Hmm. How did you install the dev version? To me, trying to do so, it gave the error:

`/usr/local/bin/yabai: resource fork, Finder information, or similar detritus not allowed`

May be i should completely uninstall and the reinstall ex novo ...

**Comment by gasper-vrhovsek** [comment]
I ran
`brew unlink yabai` 
before. I didn't get the same issue as you. Hoppe it helps.

I did a complete reinstall with the stable version. Then i "upgraded" to DEV.

**Comment by koekeishiya** [comment]
Fixed in release v3.3.6. Upgrade to the new version:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

If you are running Big Sur, read:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
