### ISSUE TITLE
MacOS 11.1 space due to an error with the scripting-addition.

### ISSUE THREAD

**Issue by fjiabinc** [koekeishiya/yabai#766]
Create and destroy spaces
Move spaces
Displays 
<img width="654" alt="截屏2020-12-18 22 34 25" src="https://user-images.githubusercontent.com/38276720/102626886-63bfcc00-4182-11eb-895c-451881e2d948.png">
<img width="1029" alt="截屏2020-12-18 22 41 59" src="https://user-images.githubusercontent.com/38276720/102626891-66222600-4182-11eb-8d00-f8e95d803f22.png">

**Comment by yanzhang0219** [comment]
Do you try to uninstall yabai and reinstall its dev version (refer to https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)). yabai supports 11.1 on the dev (latest master) but it has not been released yet.

**Comment by koekeishiya** [comment]
Fixed in release v3.3.6. Upgrade to the new version:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

If you are running Big Sur, read:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
