### ISSUE TITLE
Consequences of partially turning off SIP?

### ISSUE THREAD

**Issue by bookercodes** [koekeishiya/yabai#798]
Am I understand this correctly?

macOS does not offer a suitable API to manipulate workspaces  🥵 

To work around this in yabai, you have employed a work-around which involves injecting and observing `Dock.app`. `Dock.app` is  located somewhere in `/System`, which is a restricted directory. 

To access this directory and inject `Dock.app`,  **File System Protection** must be permenently  turned off. **Debugging protection** must be turned off too? In other words, we must partially turn off System Integrity Protection. 

Kernel extension protection, NVRAM protection, and DTrace protection remains on.

I have a few questions, I hope you can help with!

* For my own curiosity only, why does **Debugging** need disabling?
* Does Yabai rewrite Dock.app? Meaning, if I uninstall Yabai should I worry about restoring Dock.app?
* Related to the above, can I turn SIP back on after installing Yabai? I read this isn't possible, and I suspect this might have to do with injecting the script each time the system boots, rather than manipulating Dock.app

**Comment by bookercodes** [comment]
I see a lot of confusion about SIP, and the community has made a lot of work-around scripts, which I doubt compare to the native implementation. I am hoping to learn more about how Yabai works under the hood and contribute to the documentation.

**Comment by bookercodes** [comment]
I also think it'd be interesting to hear your perspective on SIP, @koekeishiya. 

I don't mean to misquote you when I recall you saying something like it's over-rated for users who know what they're doing and exercise caution installing third-party applications.

I am trying to understand the implications. It sounds to me that with SIP partially disabled, a malicious app could essentially _hook_ apps and bypass accessibility and keyboard security preferences. 

Disabling debugging might allow a malicious app to read leaked information. As for what information, I am not sure what's contained in this logs or if I even understand the flag that well.

I would _assume_ turning off filesystem protection would not make you any more vulnerable to a rootkit? Especially since kext remains enabled.

**Comment by bookercodes** [comment]
I really want to understand this, so I wrote a [question](https://apple.stackexchange.com/questions/411598/what-are-the-potential-consequences-of-partially-disabling-sip-for-yabai) on Stack Exchange also.

**Comment by wantyapps** [comment]
When I uninstalled yabai Dock.app was corrupted and I had to reinstall macOS

**Comment by koekeishiya** [comment]
> Am I understand this correctly?

> macOS does not offer a suitable API to manipulate workspaces 🥵

> To work around this in yabai, you have employed a work-around which involves injecting and observing Dock.app. Dock.app is located somewhere in /System, which is a restricted directory.

The entire workspaces system in macOS is implemented in the Dock, but uses some underlying API calls that are implemented in SkyLight.framework. To properly interact with workspaces we need to inject code into the Dock process such that we are able to modify and update these internal datastructures. In addition to this the Dock process is also flagged as a _universal owner_; it's connection to the _WindowServer_ has elevated privileges and is authorized to modify window properties that otherwise can only be set by the application whom the window belongs to.

> For my own curiosity only, why does Debugging need disabling?

Debugging needs to be disabled so that we are able to interact with the Dock's task port using the mach API. In particular, the _task_for_pid_ function. With access to the process task port, we are able to spawn remote threads and load code into the processes address space. The scripting addition is simply a bundle of code compiled as a shared library that is loaded into the process memory of a running instance of the Dock process. In short, we simplu expand upon the capabilities of the Dock process without ever interfering or overriding any of the original functionality.

> Does Yabai rewrite Dock.app? Meaning, if I uninstall Yabai should I worry about restoring Dock.app?

As explained above, we do not touch or alter any file on disk at all. Installing or uninstalling yabai and the scripting addition is in no way able to corrupt an installation or a file on your system, assuming you follow the official instructions that are provided in this repo/wiki.

> Related to the above, can I turn SIP back on after installing Yabai? I read this isn't possible, and I suspect this might have to do with injecting the script each time the system boots, rather than manipulating Dock.app

Back on High Sierra 10.13.6 you could re-enable SIP after the installation step, however, Apple changed their policy and  this is simply not possible to do in the later versions. Your assumption is correct, and while I have not tested this, I would assume that one could propably disable AMFI (Apple Mobile File Integrity) and CodeSignature checks, and modify the Dock.app binary on disk, and then perhaps you'd be able to re-activate other parts of the security, but again, there is just no way to do these kinds of things and still have _ALL_ protections enabled.

> I don't mean to misquote you when I recall you saying something like it's over-rated for users who know what they're doing and exercise caution installing third-party applications.

I wouldn't necessarily call it overrated. There are good reasons to keep SIP enabled. What this essentially mean is that malicious applications will be able to interact with the task port of any application on your system; the same way that yabai is able to. Howevr, note that even with SIP partially disabled, this is only possible for software running with elevated privileges (as root).
The disabling of SIP is basically empowering the root user; it is no longer restricted from accessing files under the read-only _/System_ partition.

> I am trying to understand the implications. It sounds to me that with SIP partially disabled, a malicious app could essentially hook apps and bypass accessibility and keyboard security preferences.

Yes, a malicious app running as the root user would be able to read from and write to the memory of _any_ process on that system. They would bypass  accessibility and keyboard security preferences by injecting code into apps with said entitlement, sort of the same way we inject our code into Dock.app to gain privileges that we otherwise would not have.

> I would assume turning off filesystem protection would not make you any more vulnerable to a rootkit? Especially since kext remains enabled.

Well, the only difference would be that they could re-mount the /System partition with write privilieges and hide the rootkit there, which could make it harder to detect.

Please note that I am not an expert in security and I do not claim to have all the answers. This is based on my own experience and understanding, and I only really use my mac for development. Take this with a grain of salt, but hopefully it included some information useful to you.

**Comment by koekeishiya** [comment]
@wantyapps 
> When I uninstalled yabai Dock.app was corrupted and I had to reinstall macOS

This is false. Yabai does _not_ modify any file on disk. You should retrace whatever you did when/while installing yabai, and third party software that you installed or tried to use.

**Comment by wantyapps** [comment]
hmm... So what happened?

**Comment by koekeishiya** [comment]
> hmm... So what happened?

I don't know what other tools you installed or if you followed some user created guide so I can only speculate, but I know that *pywal* has an issue with the symptomps you describe: https://github.com/dylanaraps/pywal/issues/515

**Comment by wantyapps** [comment]
Really?
oh

**Comment by bookercodes** [comment]
@koekeishiya I read and loved ❤️ your answer a couple of weeks ago. I don't have much to add except, thank you!
