### ISSUE TITLE
Question about window borders

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#8]
I'm currently trying yabai in macOS High Sierra. (I adjusted the homebrew formulae and builded it myself)
In my computer, the border's inner radius is always zero, and the border is drawn inside of the window instead of the outside like chunkwm.
As the radius looks like being calculated automatically unlike chunkwm, I have some questions related to macOS versions.

* Is the inner radius being zero because I'm High Sierra, or does it work the same as Mojave?̊̈
* Is it expected for the border to be drawn inside of the window or is it not working in High Sierra?̊̈
<img width="177" alt="스크린샷 2019-05-25 오후 11 01 30" src="https://user-images.githubusercontent.com/37990858/58370443-8277c580-7f41-11e9-91f3-060c2f11d3dc.png">

**Comment by pcr910303** [comment]
<img width="177" alt="스크린샷 2019-05-25 오후 11 01 30" src="https://user-images.githubusercontent.com/37990858/58370436-75f36d00-7f41-11e9-8b4c-5493d95a7076.png">

**Comment by koekeishiya** [comment]
> Is the inner radius being zero because I'm High Sierra, or does it work the same as Mojave?̊̈

The inner radius appears to be zero because of how the radius is calculated, and should appear the same on High Sierra and Mojave. If you look closely at the screenshot in the readme.md it also appears like that.

>  Is it expected for the border to be drawn inside of the window or is it not working in High Sierra?̊̈

The border is drawn exactly on (and thus inside) the window, because it annoys me when borders of multiple windows overlap, because they are outside the window-frame.

I have made some changes on the master branch that adds a small inset to the border frame, and tweaked the radius calculation a bit, such that the inner part of the corners also appear rounded.

By doing this, if you have a *window_gap* of 0, their borders will now partially overlap, as I mentioned above. Can you build from master and let me know if you find this new look to be acceptable?

I'm trying to not expose too much in the config, as while it is important to let people customize the behaviour; requiring too much tweaking to get a usable experience is also not good.

**Comment by pcr910303** [comment]
Hmm... rebuilt yabai from HEAD, but is still seeing the same thing as before :-(
Inner radius is still zero, and borders are still drawn inside: 
<img width="111" alt="스크린샷 2019-05-26 오전 12 07 34" src="https://user-images.githubusercontent.com/37990858/58371225-6c223780-7f4a-11e9-8f89-bd240ace7a18.png">

<img width="1280" alt="스크린샷 2019-05-26 오전 12 07 26" src="https://user-images.githubusercontent.com/37990858/58371237-8e1bba00-7f4a-11e9-8003-0f8258c9ece9.png">

**Comment by koekeishiya** [comment]
Hmm weird, maybe there is a difference between systems then, or your build didn't update properly.

This is how it looks for me now:

<img width="1440" alt="crn" src="https://user-images.githubusercontent.com/6175959/58371754-67429100-7f14-11e9-823c-00e747f6ea91.png">

**Comment by pcr910303** [comment]
@koekeishiya Confirmed! I didn't restart the home-brew service :-(

**Comment by koekeishiya** [comment]
> but I get the feeling that the borders are pixelated...
It doesn't feel right in retina displays... IMHO

Currently it does not render borders using HiDPI as far as I can tell. I am using private APIs to create the border windows because I want to stay out of objective-c and Cocoa APIs as much as possible. There is likely some setting that is required to enable HiDPI support. I'll look into this more at some point.

**Comment by pcr910303** [comment]
> I'll look into this more at some point.
Great... Looking forward :-)
BTW, it looks like the updated code for borders cause borders appear everywhere! 

![yabai-borders](https://user-images.githubusercontent.com/37990858/58371919-20bf5780-7f51-11e9-80e4-77e84f4273e6.gif)

**Comment by koekeishiya** [comment]
Borders are now drawn with HiDPI.

**Comment by dominiklohmann** [comment]
Isn't it wrong to assume a 2x resolution? The default for a new MacBook Pro right now is 1680x1050 on a 2880x1800 display, which is not 2x. Also there might be multi-monitor setups using different scaling factors across multiple displays. Maybe there is a way to get the window resolution / scaling factor of the window you're drawing the border on and re-use that factor?

**Comment by koekeishiya** [comment]
> Isn't it wrong to assume a 2x resolution? The default for a new MacBook Pro right now is 1680x1050 on a 2880x1800 display, which is not 2x. Also there might be multi-monitor setups using different scaling factors across multiple displays. Maybe there is a way to get the window resolution / scaling factor of the window you're drawing the border on and re-use that factor? 

I suppose in the case of a multi-monitor setup, you are correct. For the built-in / Apple screens I would assume this piece of documentation remain accurate. 

> The value of this property is 2.0 for high-resolution scaled display modes, and 1.0 for all other cases.

From https://developer.apple.com/documentation/appkit/nswindow/1419459-backingscalefactor?language=objc

Edge-case: What happens if a window is 50% located on a retina display, and 50% on a non-retina display?

**Comment by koekeishiya** [comment]
I disabled retina resolution on my MBP and started borders still work properly, they are just drawn without HiDPI as expected, so I think that is probably a non-issue. There is likely support in the WindowServer that validates that the window can be drawn with HiDPI on the display it is drawn to, and if that display does not support HiDPI, it will fall back to LowDPI.

**Comment by pcr910303** [comment]
@koekeishiya The updated HIDPI borders look awesome! :-) 
The only thing blocking me turning on borders is the (new?) bug about displaying borders everywhere :-(

**Comment by koekeishiya** [comment]
> bug about displaying borders everywhere 

This won't be fixable until a *window rules* system is in place. Currently, *all* elements on the screen that are reported as *windows* by macOS will get a border. The fix is to first check if the element is an actual window, but many non-windows report that they are, and many windows report that they aren't (e.g: Emacs among others).

**Comment by pcr910303** [comment]
@koekeishiya Ah, will be looking forwards for the window rules :-)
About the window rules, I decided to go to emacs-mac which has a better macOS GUI support :-)

Currently almost migrated to yabai.... 👍

**Comment by koekeishiya** [comment]
> By doing this, if you have a window_gap of 0, their borders will now partially overlap, as I mentioned above.

This started to annoy me again so on the latest master we adjust the window frame if it has a visible border to accommodate for the outset value.

**Comment by pcr910303** [comment]
@koekeishiya What about drawing borders outside if gap > 2 * border-width,
on the borders (like the master before b4f9d32) if 2 * border-width > gap > border-width
and inside if gap <= border-width?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment]
I'll stick with the current border placement for now. Also made it such that borders are only created for actual windows. Applications that report an incorrect role for their windows will not get a border.

Closing this resolved.

**Comment by daphen** [comment]
Hm, I'm having an issue where if I click in a window after activating it, the MacOS border takes over the z-index of the Yabai border and makes it look weird, any ideas?

Active window:
![image](https://user-images.githubusercontent.com/4034320/69002205-9990e200-08ea-11ea-92f2-41da2d975a90.png)

Active window after clicking inside of it:
![image](https://user-images.githubusercontent.com/4034320/69002209-af9ea280-08ea-11ea-92d1-470b80ea8dae.png)

**Comment by koekeishiya** [comment]
@daphen 

See my reply in https://github.com/koekeishiya/yabai/issues/310

**Comment by daphen** [comment]
> @daphen
> 
> See my reply in #310

Thank you!
