### ISSUE TITLE
Ability to configure rounded borders for Mac OS big sur

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#801]
Currently the yabai border isn't rounded making them look ugly on big sur. Adding rounded borders ability would make it look pretty.

**Comment by bookercodes** [comment]
Not sure about yabai's built-in bordering however with [limelight](https://github.com/koekeishiya/limelight), the borders look significantly better when set to `interior`.

**Comment by choco** [comment]
Could this be accomplished with the new border system in yabai 4.0? (to mimic limelight behaviour)

**Comment by weeebdev** [comment]
> Could this be accomplished with the new border system in yabai 4.0? (to mimic limelight behaviour)

same question

**Comment by koekeishiya** [comment]
It is possible to add rounded borders yes, but not sure I want to. The ram usage will skyrocket in comparison, because we would need to enable hiDPI mode, which is not necessary in the current mode,as the pixelation is not visible when drawing straight lines.

I think I made a post on this in another issue, https://github.com/koekeishiya/yabai/issues/984

**Comment by koekeishiya** [comment]
This will be fixed with the changes being made for #1430
