### ISSUE TITLE
SA doesn't support macOS 11.3

### ISSUE THREAD

**Issue by TheCultLeader666** [koekeishiya/yabai#869]
The yabai scripting addition does not seem to support macOS 11.3, as it gives this error upon loading.
![Screen Shot 2021-03-27 at 16 25 46](https://user-images.githubusercontent.com/65368815/112733953-420c7880-8f19-11eb-9cf3-b8bdd07fc6d9.png)
While most features still seem to work, my Übersicht widgets can no longer change, move, or destroy spaces

**Comment by CaninoDev** [comment]
Isn't MacOS 11.3 still in beta? I'd wait until it is finally released before filing this issue.

**Comment by TheCultLeader666** [comment]
Just because it's in beta doesn't mean app developers shouldn't develop with it in mind. If they don't their app will break as soon as the new version is released.

**Comment by CaninoDev** [comment]
@koekeishiya isn't expecting to be paid for this project. Similarly, it's users shouldn't be expecting anything from @koekeishiya

**Comment by TheCultLeader666** [comment]
I'm just saying that this project will quickly lose popularity if it ceases to support new versions. You are suggesting that the developer shouldn't pay any mind to the fact that it's broken in 11.3, simply because it's in beta

**Comment by Ikbosh** [comment]
> I'm just saying that this project will quickly lose popularity if it ceases to support new versions. 
I doubt the developers make this product to gain popularity, and I understand that popularity fosters contribution, however at the same time I don't see many alternatives.

>You are suggesting that the developer shouldn't pay any mind to the fact that it's broken in 11.3, simply because it's in beta. Shouldn't the developer instead think ahead and support beta versions, as those versions are eventually going to make it to release, and it would be bad for the project if it broke after an update and the developer hadn't even payed any attention to the problem, even while the problem had been reported (this issue)?

When the product is provided as-is, free of charge, it's only reasonable that you, the lucky recipient should understand the developer may not work to enable support for a version they themself may not be using. It's more likely that when the developer feels ready to move their Workstation over to the relevant version of the Operating System, it's at that point they would update the software they rely upon. The developers for products like this in most cases develop the product purely for their own use, and from the kindness of their heart share it so people like you can use it - even when they're ungrateful. 

I recommend reflecting upon your attitude on projects like this, it's great that you've contributed with an issue. But rather than complaining, why don't you ask more questions, find out ways you can contribute relevant diagnostic information so that the developer may not have to download and install the Beta version themself to resolve it.

**Comment by dominiklohmann** [comment]
For what it's worth, if you want an update of the SA it's usually helpful to at least upload the current Dock.app, because that must be looked at for the SA to be updated.

11.3 appears to be in its final beta, and the first 11.4 beta is already out. Ultimately this is up to @koekeishiya to update.

**Comment by TheCultLeader666** [comment]
Anyways, having stopped using macOS I cannot comment or help any further on this

**Comment by dominiklohmann** [comment]
I've updated my secondary machine to the beta. @koekeishiya here's the Dock.app for the final 11.3 beta in case you want to be a week ahead and take the risk that no further changes happen. 

[Dock.app.zip](https://github.com/koekeishiya/yabai/files/6378137/Dock.app.zip)

**Comment by koekeishiya** [comment]
I don't run beta versions on my machine, and I am unable to disable SIP when running in a VM. Updates will happen after a final release has been done, and if that is an issue for you I suggest you either a) wait with updating, b) patch it yourself.
