### ISSUE TITLE
Disable rounded borders?

### ISSUE THREAD

**Issue by arzg** [koekeishiya/yabai#87]
Hi,

is it possible to disable rounded borders? I took a look through the documentation, but couldn’t find an option to do so.

Thanks.

**Comment by koekeishiya** [comment]
It is not possible to disable or adjust the border radius. macOS apps have rounded corners by default and as the border is drawn around windows - not overlapping their contents, I found it impractical to allow setting a custom radius. The radius is calculated based on the width of the border in a way that I found to look appropriate at "usable" values.

You can always create a fork and do whatever - take a look at *src/border.c* if you wish to do so. For the radius in particular, just search for *radius* in that file. If you decide to disable the radius you will have to adjust the frame positioning as well to avoid having gaps at the edges of the border and the window.

**Comment by arzg** [comment]
Cool, thanks.

**Comment by pcr910303** [comment]
@tsujp If I understood correctly, I believe this issue is about setting a custom radius for the border that yabai draws when the `window_border` setting is activated, not the radius of windows that macOS draws.

I think your comment should be another feature request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
