### ISSUE TITLE
Toggling  focus-follows-mouse

### ISSUE THREAD

**Issue by boris-sbizzera** [koekeishiya/yabai#873]
Is there a way to toggle this behavior ?

**Comment by CaninoDev** [comment]
If you are controlling yabai's behavior via skhd, just set up a shortcut that will execute (I am assuming you want `autofocus` otherwise substitute in `autoraise`:
```sh
[place shortcut sequence here] : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autofocus || yabai -m config focus_follows_mouse off
```

For example, to map `ctrl`, `alt`, `cmd` and `m` to toggle focus follows mouse behavior, your `skhdrc` would have the following line:
```sh
ctrl + alt + cmd - m : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autofocus || yabai -m config focus_follows_mouse off
```

This utilized the shell's built in conditional operator and command substitution (see `man bash` and read up on `conditiional expressions`)

**Comment by jespertheend** [comment]
I'm using this to toggle both focus follows mouse and mouse follows focus using fn + shift + f:
```bash
fn + shift - f : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autofocus mouse_follows_focus on || yabai -m config focus_follows_mouse off mouse_follows_focus off
```
