### ISSUE TITLE
change window border color when zoom-parent is on?

### ISSUE THREAD

**Issue by jzelner** [koekeishiya/yabai#89]
Hi - 

I am *loving* yabai; it has brought me back to the mac from a few years of i3. One feature I would love to be able to get some of the functionality of, though, is the tabbed windows in i3. Doing this with zoom-parent seems possible, but I sometimes forget that a window is in that state. Is it possible to change the window border color when a window is zoomed? This would at least remind me something may be lurking underneath.

Any suggestions would be great; thanks!

-Jon

**Comment by koekeishiya** [comment]
There is no command to specify the color for a window border upon zoom, however it is possible to change the color of the focused window at any time. You could likely put this together using some scripts now that #90 is resolved, using the *signal* system that *yabai* provides.

Basically what you need to do is create a script that check if the window in question is zoomed or not, and set the color you want. This script can be configured to run when a window has gained focus. 

In *skhd* or whatever program you use to toggle zoom, you need to essentially have the same check, so that the border changes color when you zoom / unzoom a window without having to refocus it.

**Comment by braham-snyder** [comment]
In case it saves someone time, here's my implementation.

Very redundant, but it works. Improvements welcome.

In `.skhdrc` (`fish` shell):
```sh
# TODO I should use aliases and/or sh functions or something to reduce redundancy among these
# commands and the related code in yabairc (where we change colors when we focus a different window
# or application)
zoom < f : skhd -k "escape";\
           yabai -m window --toggle zoom-fullscreen;\
           if yabai -m query --windows --window | jq -er '."zoom-fullscreen" == 1';\
               yabai -m config active_window_border_color 0xff33d6ff;\
           else;\
               yabai -m config active_window_border_color 0xff00ff00;\
           end
```

In `yabairc`:
```sh
####
# Color windows according to zoom-fullscreen status.
#
# TODO I should use aliases and/or sh functions or something to reduce
# redundancy among these commands and the related code in skhdrc (where we change colors
# when we toggle zoom)

yabai -m signal --add label=on_win_color_zoom event=window_focused \
      action=$'
if $(yabai -m query --windows --window | jq -er \'."zoom-fullscreen" == 1\')
then
    yabai -m config active_window_border_color 0xff33d6ff
else
    yabai -m config active_window_border_color 0xff00ff00
fi'

yabai -m signal --add label=on_app_color_zoom event=application_front_switched \
      action=$'
if $(yabai -m query --windows --window | jq -er \'."zoom-fullscreen" == 1\')
then
    yabai -m config active_window_border_color 0xff33d6ff
else
    yabai -m config active_window_border_color 0xff00ff00
fi'
```

**Comment by leohxj** [comment]
I just want to know the current app is in which mode, is there any simple way I can detect?
