### ISSUE TITLE
yabai only runs through terminal

### ISSUE THREAD

**Issue by Catbodi** [koekeishiya/yabai#94]
I've been using chunkwm for quite some time now and it is fantastic. I'm on OS 10.13.6. I installed yabai through brew and grabbed the example .yabairc and .skhdrc as a test run before beginning to customize. I was able to get it running through only typing "yabai" in terminal, using brew services start yabai would say it successfully started however it wouldn't actually tile. When launching from terminal it would work as expected. Any way to fix?

**Comment by dominiklohmann** [comment]
In your Security & Privacy preferences pane under Privacy > Accessibility, make sure you add yabai directly instead of just Terminal.app (or whatever Terminal you use). 

![image](https://user-images.githubusercontent.com/4488655/60755349-cc4ad580-9fee-11e9-85c1-cba53603329b.png)

**Comment by Catbodi** [comment]
> In your Security & Privacy preferences pane under Privacy > Accessibility, make sure you add yabai directly instead of just Terminal.app (or whatever Terminal you use).
> 
> ![image](https://user-images.githubusercontent.com/4488655/60755349-cc4ad580-9fee-11e9-85c1-cba53603329b.png)

I already did this as well as code-signed yabai in /usr/local/bin

**Comment by dominiklohmann** [comment]
You can find see a log stream using `tail -f /usr/local/var/log/yabai/yabai.err.log` (or yabai.out.log at the same path for stdout instead of stderr) when running through `brew services`.

It is likely that you have done something wrong with codesigning or accessibility permissions. Try removing yabai from the list and adding it again.

**Comment by karrot42** [comment]
I also had this problem but it was because when I first installed yabai I kept getting the popup for accessibility permission and kept trying to accept, but couldn't until I just denied it.  What remedied for me was

1. Checked which brew services were running
`brew services list`

2. Saw that yabai was stopped

3. Restarted all brew services
`brew services restart --all`

4. restarted my computer and accepted permissions for dock access and accessibility.

**Comment by denniseffing** [comment]
I have the same issue. `yabai.err.log` and `yabai.out.log` are both empty. I tried adding the following paths of yabai to the accessibility list:
- `/usr/local/Cellar/yabai/2.0.1/bin`
- `/usr/local/bin/yabai`

Rebooting my machine did not help. Running yabai using the terminal works fine.

**Comment by koekeishiya** [comment]
The log files are empty because you are not running yabai with the *--verbose* flag.
