### ISSUE TITLE
Detached firefox tab gets moved to wrong space

### ISSUE THREAD

**Issue by s00500** [koekeishiya/yabai#951]
Hey everyone, I got a strange problem: 
I am running firefox on one display and have an empty space on a second display. If I create a new tab in firefox, then take the tab and move it to the next space it would usually (without yabai running) expand to a fullscreen window on the second display. With yabai running though it clearly gets created on the second display and then yabai moves it back to the main focused display. I also tried to query all windows on the window_created event and I can see that yabai does not get that the window got created on the second display, but thinks it got created on the main display. Interestingly it still shows a window_moved event afterwards...

I believe a fix of this could be done in config, but I feel I am missing a good approach... generally the wrong detection feels like either a strange firefox behaviour or a bug in yabai...

Thanks,
Lukas

**Comment by koekeishiya** [comment]
So this is actually intentional and not really a bug, but I can see how it does seem out of place in this particular case.

What's happening here is that when you separate a tab and a new window is created, yabai does not actually care which display the window spawned at, and forces it to tile on the currently focused display.

The reason for this is that applications/windows on macOS (try to) remember which display they were last at when they reopen. This often caused the window to be tiled at a secondary display, even when the primary display was empty and the actual display I wanted the application to be in.

I am open to invesigating this in more detail to see if it may be possible to have this behaviour be more context-aware.

Sent from my iPhone

On 4 Jul 2021, at 14:00, Lukas Bachschwell ***@***.***> wrote:

﻿

Hey everyone, I got a strange problem:
I am running firefox on one display and have an empty space on a second display. If I create a new tab in firefox, then take the tab and move it to the next space it would usually (without yabai running) expand to a fullscreen window on the second display. With yabai running though it clearly gets created on the second display and then yabai moves it back to the main focused display. I also tried to query all windows on the window_created event and I can see that yabai does not get that the window got created on the second display, but thinks it got created on the main display. Interestingly it still shows a window_moved event afterwards...

I believe a fix of this could be done in config, but I feel I am missing a good approach... generally the wrong detection feels like either a strange firefox behaviour or a bug in yabai...

Thanks,
Lukas

**Comment by s00500** [comment]
Hi @koekeishiya,
Thank you for the detailed explanation!!!
For me it is kind of annoying as it causes another operation with the mouse I did want to avoid....

If there is anything I can do to help you test this I am up for it, I guess a cool way to handle it would be a way to override this behavior using the rule engine... this way we could test if it makes the UX better for apps like firefox


Yabai has been a really awesome addition to my workflow so far, and this is one of the details I still would like to polish
Let me know what I can do to help here 😃

Greetings,
Lukas

**Comment by koekeishiya** [comment]
My initial thoughts for now is to make this configurable with the following alternatives:

1. default macOS behaviour - window is tiled at the display it happens to spawn at

2. focused/current display - window is tiled at the display that has focus (current yabai behaviour)

3.  cursor display - window is tiled at the display that holds the mouse cursor

Altrnative 3 here would be a suitable fix for the old problem that I described earlier, and it should also resolve the issue you are having with detaching tabs to different displays.

I assume there are people who prefer the default macOS setting as well, or Apple would(????) have done something after all these years, so that should be an option too.

Sent from my iPhone

On 13 Aug 2021, at 18:27, Lukas Bachschwell ***@***.***> wrote:

﻿

Hi @koekeishiya<https://github.com/koekeishiya>,
Thank you for the detailed explanation!!!
For me it is kind of annoying as it causes another operation with the mouse I did want to avoid....

If there is anything I can do to help you test this I am up for it, I guess a cool way to handle it would be a way to override this behavior using the rule engine... this way we could test if it makes the UX better for apps like firefox

Yabai has been a really awesome addition to my workflow so far, and this is one of the details I still would like to polish
Let me know what I can do to help here 😃

Greetings,
Lukas

**Comment by s00500** [comment]
Hi @koekeishiya, 
I just compiled and tested the the-future branch and set the config to "cursor"
This causes the exact behavior I was looking for, really nice!!!
As of right now I am on holiday and only use 1 monitor most of the time, (just tested with the TV to check the patch), so I can not say for sure yet if this could cause other unwanted side effects, but I think it should work well, also because this is no default option, so it wont break stuff for now...

I will continue looking out for potential hickups when I get back to my normal 3-display worksetup next week and update this issue if anything comes up

Thanks a lot for addressing the issue!!!
