### ISSUE TITLE
[Feature Request] Reorder windows inside stacks

### ISSUE THREAD

**Issue by nermolov** [koekeishiya/yabai#960]
Expansion of https://github.com/koekeishiya/yabai/issues/203#issuecomment-686590184

Would be very helpful to organize windows more.

**Comment by koekeishiya** [comment]
On master, `yabai -m window --swap <window_sel>` will now also work on windows that are in the same stack, instead of returning an error.


If both windows are in the same stack, the windows will swap place inside that stack.

If windows are in separate stacks, the entire stacks will swap places.

If one window is stand-alone (not a stack), and the other is a stack of windows, it will swap places with the entire stack.
